---
sidebar: sidebar 
permalink: oracle/tiering/oracle-object-store-access-interruptions.html 
keywords: tiering, fabricpool, interruption 
summary: オブジェクトストアへのアクセス中断時のデータベースアクセス 
---
= オブジェクトストアへのアクセスの中断
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
FabricPoolでデータセットを階層化すると、プライマリストレージアレイとオブジェクトストア階層の間に依存関係が生じます。オブジェクトストレージには、さまざまなレベルの可用性を提供するオプションが多数あります。プライマリストレージアレイとオブジェクトストレージ階層の間の接続が失われた場合の影響を理解することが重要です。

ONTAPに対して実行するI/Oで大容量階層のデータが必要になり、ONTAPが大容量階層に到達してブロックを読み出すことができない場合、最終的にI/Oはタイムアウトします。このタイムアウトの影響は、使用するプロトコルによって異なります。NFS環境では、ONTAPはプロトコルに応じてEJUKEBOXまたはEDELAYのいずれかの応答で応答します。一部の古いオペレーティングシステムではエラーと解釈される場合がありますが、現在のオペレーティングシステムとOracle Direct NFSクライアントの現在のパッチレベルでは、これを再試行可能なエラーとして扱い、I/Oの完了を待ち続けます。

環境SAN環境のタイムアウトを短縮します。オブジェクトストア環境のブロックが必要で、2分間アクセスできない場合は、読み取りエラーがホストに返されます。ONTAPボリュームとLUNはオンラインのままですが、ホストOSからファイルシステムにエラー状態のフラグが設定されることがあります。

オブジェクトストレージの接続の問題 `snapshot-only` バックアップデータのみが階層化されるため、ポリシーはそれほど重要ではありません。通信に問題があると、データのリカバリに時間がかかりますが、それ以外の場合はアクティブに使用されているデータに影響。 `auto` および `all` ポリシーを使用すると、アクティブなLUNからコールドデータを階層化できます。つまり、オブジェクトストアデータの読み出し中にエラーが発生すると、データベースの可用性に影響する可能性があります。これらのポリシーを使用したSAN環境は、高可用性を実現するように設計されたエンタープライズクラスのオブジェクトストレージとネットワーク接続でのみ使用してください。NetApp StorageGRIDは優れたオプションです。
