---
sidebar: sidebar 
permalink: oracle/tiering/oracle-log-tiering.html 
keywords: tiering, fabricpool 
summary: Oracleアーカイブログの階層化 
---
= Oracleログの階層化
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
FabricPoolの最も重要な用途は、データベーストランザクションログなどの既知のコールドデータの効率化です。

ほとんどのリレーショナルデータベースは、ポイントインタイムリカバリを実現するためにトランザクションログアーカイブモードで動作します。データベースへの変更は、トランザクションログに変更を記録することによってコミットされ、トランザクションログは上書きされずに保持されます。そのため、大量のアーカイブトランザクションログを保持しなければならない場合があります。同様の例は、保持する必要があるデータを生成する他の多くのアプリケーションワークフローにも存在しますが、アクセスされることはほとんどありません。

FabricPoolは、階層化が統合された単一の解決策を提供することで、これらの問題を解決します。ファイルは通常の場所に保存されてアクセス可能な状態に維持されますが'プライマリ・アレイのスペースはほとんど消費されません



== ポリシー

を使用します `tiering-minimum-cooling-days` 数日間のポリシーを設定すると、最近作成されたファイル（短期的に必要になる可能性が高いファイル）のブロックが高パフォーマンス階層に保持されます。その後、古いファイルのデータブロックが大容量階層に移動されます。

。 `auto` ログが削除されたか、プライマリファイルシステムに引き続き存在しているかに関係なく、クーリングしきい値に達したときに、プロンプト階層化を適用します。必要となる可能性があるすべてのログをアクティブファイルシステムの1つの場所に格納することも、管理を簡易化します。リストアが必要なファイルを特定するためにSnapshotを検索する必要はありません。

Microsoft SQL Serverなどの一部のアプリケーションでは、バックアップ処理中にトランザクションログファイルが切り捨てられ、ログがアクティブファイルシステムに記録されなくなります。容量は、 `snapshot-only` 階層化ポリシー `auto` アクティブファイルシステムにはログデータが冷却されることはほとんどないため、ログデータにはポリシーは役立ちません。
