---
sidebar: sidebar 
permalink: oracle/virtualization/intro.html 
keywords: oracle, database, ontap, virtualization, esx, hyper-v, KVM 
summary: データベース仮想化の概要 
---
= 仮想化
:allow-uri-read: 


[role="lead"]
VMware ESX、Oracle OVM、KVMを使用したデータベースの仮想化は、最もミッションクリティカルなデータベースでさえ仮想化を選択したNetAppのお客様にとって、ますます一般的な選択肢となっています。

仮想化のサポートポリシー、特にVMware製品については、多くの誤解が存在します。実際、Oracleが仮想化をサポートしていないという話は珍しくありません。この概念は正しくないため、仮想化の機会を逃してしまいます。Oracle Doc ID 249212.1では、Oracle環境の既知の問題について説明し、RACのサポートも指定しています。

Oracleが把握していない問題を抱えているお客様は、物理ハードウェアで問題を再現するように依頼されることがあります。最新バージョンの製品を使用しているOracleのお客様は、新しいバグが発見される可能性があるため、仮想化の使用を望まないかもしれません。ただし、一般提供されている製品バージョンを使用している仮想化環境では、このような状況は実際には問題になりませんでした。



== ストレージ提供

データベースの仮想化を検討しているお客様は、ビジネスニーズに基づいてストレージに関する意思決定を行う必要があります。これはすべてのIT意思決定に一般的に当てはまりますが、プロジェクトの規模と範囲が大きく異なるため、仮想化にとって特に重要です。

ストレージプレゼンテーションには、次の4つの基本的なオプションがあります。

* iSCSI LUNをハイパーバイザーではなくVMのiSCSIイニシエータで管理
* NFSファイルシステムを、仮想マシンディスク（VMDK）ではなくVMでマウントする
* ハイパーバイザーデータストア


一般的なルールとして、Oracleファイルにデータストアを使用することは避けてください。この推奨事項には多くの理由があります。

* *透過性。* VMが自身のファイルシステムを所有している場合、データベース管理者やシステム管理者は、データのファイルシステムのソースを簡単に特定できます。
* *パフォーマンス。*テストでは、ハイパーバイザーデータストアを介してすべてのI/Oをチャネリングすることでパフォーマンスに影響があることが示されています。
* *管理性。* VMが自身のファイルシステムを所有している場合、ハイパーバイザーレイヤを使用するかどうかは管理性に影響します。プロビジョニング、監視、データ保護などの手順は、仮想環境と非仮想環境の両方を含め、資産全体で同じです。
* *安定性とトラブルシューティング。* VMが自身のファイルシステムを所有している場合、ストレージスタック全体がVM上に存在するため、優れた安定したパフォーマンスが提供され、問題のトラブルシューティングがはるかに簡単になります。ハイパーバイザーの役割は、FCフレームまたはIPフレームを転送することだけです。構成にデータストアが含まれていると、タイムアウト、パラメータ、ログファイル、および潜在的なバグが新たに発生するため、構成が複雑になります。
* *モビリティ。* VMが自身のファイルシステムを所有している場合、Oracle環境を移動するプロセスははるかにシンプルになります。ファイルシステムは、仮想ゲストと非仮想ゲストの間で簡単に移動できます。
* *ベンダーロックイン。*データをデータストアに配置した後は、別のハイパーバイザーを使用したり、仮想環境からデータを取り出すことは完全に非常に困難になります。
* *スナップショットの有効化。*帯域幅が比較的限られているため、場合によっては、仮想環境でのバックアップが問題になることがあります。たとえば、多くの仮想データベースで日 々 必要とされるパフォーマンスを満たすには、4ポートの10GbEトランクで十分な場合があります。ただし、RMANなどのバックアップ製品を使用してバックアップを実行するには、このようなトランクでは不十分であり、データのフルサイズのコピーをストリーミングする必要があります。
+
VM所有のファイルシステムを使用すると、Snapshotベースのバックアップとリストアを簡単に活用できます。VM所有のファイルシステムを使用すると、ストレージシステムにバックアップ処理がオフロードされます。バックアップウィンドウで帯域幅とCPUの要件をサポートするためだけに、ハイパーバイザー構成を過剰に構築する必要はありません。




TIP: * NetAppでは、最適なパフォーマンスと管理性を実現するために、Oracleデータをデータストアに配置しないことを推奨しています。ゲスト所有のファイルシステム（ゲストまたはRDMで管理されるNFSまたはiSCSIファイルシステムなど）を使用します。



== 準仮想化ドライバ

最適なパフォーマンスを実現するには、準仮想化ネットワークドライバを使用することが重要です。データストアを使用する場合は、準仮想化SCSIドライバが必要です。準仮想化デバイスドライバを使用すると、エミュレートされたドライバとは対照的に、ゲストをハイパーバイザーにより深く統合できます。エミュレートされたドライバでは、ハイパーバイザーは物理ハードウェアの動作を模倣するためにより多くのCPU時間を消費します。

ほとんどのデータベースのパフォーマンスは、ストレージによって制限されます。そのため、ネットワークまたはSCSIドライバによって発生する余分な遅延が特に顕著になります。NetAppカスタマサポートでは、準仮想化ドライバをインストールすることで解決された、パフォーマンスに関する多くの苦情が発生しています。あるお客様のコンセプトの実証（POC）では、同じハードウェアをベアメタルとして実行した場合よりも、ESXを使用した場合の方がデータベースのパフォーマンスが向上しました。テストではI/O負荷が非常に高く、パフォーマンスの違いはESX準仮想化ネットワークドライバを使用したことによるものです。


TIP: * NetAppでは、常に準仮想化ネットワークドライバとSCSIドライバを使用することを推奨しています。



== RAMのオーバーコミット

RAMのオーバーコミットとは、物理ハードウェア上に存在するよりも多くの仮想RAMをさまざまなホストに設定することを意味します。原因で予期しないパフォーマンスの問題が発生する可能性があります。データベースを仮想化する場合、Oracle SGAの基盤となるブロックがハイパーバイザーによってストレージにスワップアウトされないようにする必要があります。このように設定すると、パフォーマンスが非常に不安定になります。


TIP: * NetAppでは、Oracle SGAブロックがスワップアウトされるような方法でハイパーバイザーを設定しないことを推奨しています*。
