---
sidebar: sidebar 
permalink: oracle/oracle-asar2-storage-san-config-lun-sizing.html 
keywords: SAN, ASM, LVM, oracle, lun, sizing, count, ASA r2 
summary: ASA r2 を使用した Oracle データベースの LUN サイズと LUN 数のガイドライン 
searchtitle: ASA r2 を使用した Oracle データベースの LUN サイズと LUN 数 
---
= LUNのサイジングとLUN数
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Oracleデータベースのパフォーマンスと管理性を最適化するには、最適なLUNサイズと使用するLUNの数を選択することが重要です。

LUN は、 ASA r2 システム上のホスティング ストレージ アベイラビリティ ゾーン (SAZ) 内のすべてのドライブに存在するONTAP上の仮想化オブジェクトです。その結果、LUN はどのサイズを選択しても SAZ の潜在的パフォーマンスを最大限に活用するため、LUN のパフォーマンスはそのサイズの影響を受けません。

便宜上、特定のサイズのLUNを使用したい場合があります。たとえば、データベースを2つの1TB LUNで構成されるLVMまたはOracle ASMディスクグループ上に構築する場合、そのディスクグループは1TB単位で拡張する必要があります。8個の500GB LUNでディスクグループを構築し、ディスクグループの増分単位を小さくできるようにすることを推奨します。

汎用性に優れた標準LUNサイズを設定すると、管理が複雑になる可能性があるため、推奨されません。たとえば、標準サイズの100GBのLUNは、1TB~2TBのデータベースまたはデータストアの場合に適していますが、サイズが20TBのデータベースまたはデータストアには200個のLUNが必要です。つまり、サーバのリブート時間が長くなり、さまざまなUIで管理するオブジェクトが増え、SnapCenterなどの製品は多くのオブジェクトに対して検出を実行する必要があります。LUNのサイズを大きくすることで、このような問題を回避できます。

* ASA r2 の考慮事項:*

* ASA r2 の最大 LUN サイズは 128 TB であり、パフォーマンスに影響を与えることなく、より少ない数のより大きな LUN を使用できます。
* ASA r2 は、集約の代わりにストレージ可用性ゾーン (SAZ) を使用しますが、これによって Oracle ワークロードの LUN サイズ設定ロジックは変更されません。
* シン プロビジョニングはデフォルトで有効になっています。LUN のサイズ変更は中断を伴わず、オフラインにする必要もありません。




== LUN数

LUNのサイズとは異なり、LUNの数はパフォーマンスに影響します。アプリケーションのパフォーマンスは、多くの場合、SCSIレイヤを介して並列I/Oを実行できるかどうかに左右されます。その結果、2つのLUNの方が単一のLUNよりもパフォーマンスが向上します。Veritas VxVM、Linux LVM2、Oracle ASMなどのLVMを使用すると、並列処理を強化する最も簡単な方法です。

ASA r2 では、 ONTAP がプラットフォーム間で同様に並列 I/O を処理するため、LUN 数の原則はAFF/ FASと同じままです。ただし、 ASA r2 の SAN 専用アーキテクチャとアクティブ / アクティブ対称パスにより、すべての LUN にわたって一貫したパフォーマンスが保証されます。

NetAppのお客様は、LUNの数を16個以上に増やすことによるメリットはほとんどありませんが、ランダムI/Oが非常に大きい100% SSD環境のテストでは、最大64個のLUNがさらに向上していることが実証されています。

[TIP]
====
* NetAppの推奨事項*：

一般に、特定の Oracleデータベース ワークロードの I/O ニーズをサポートするには、4 ～ 16 個の LUN で十分です。LUN が 4 つ未満の場合、ホスト SCSI 実装の制限によりパフォーマンスが制限される可能性があります。LUN を 16 個以上に増やしても、極端な場合 (非常に高いランダム I/O SSD ワークロードなど) を除き、パフォーマンスが向上することはほとんどありません。

====