---
sidebar: sidebar 
permalink: oracle/oracle-asar2-app-config-rac.html 
keywords: oracle, database, ASA r2, ontap, rac, disktimeout, misscount 
summary: ASA r2 での Oracle RAC タイムアウト 
searchtitle: Oracle Real Application Clusters のASA r2 でのタイムアウト 
---
= RACタイムアウト
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Oracle RACは、クラスタの健常性を監視する複数のタイプの内部ハートビートプロセスを備えたクラスタウェア製品です。

ASA r2 システムはAFF/ FASと同様にONTAP を使用するため、Oracle RAC タイムアウト パラメータにも同じ原則が適用されます。disktimeout または misscount の推奨事項にはASA固有の変更はありません。ただし、 ASA r2 は SAN ワークロードと低レイテンシフェイルオーバー向けに最適化されているため、これらのベスト プラクティスはさらに重要になります。


NOTE: の情報は link:#misscount["MissCount"] このセクションには、ネットワーク ストレージを使用する Oracle RAC 環境に関する重要な情報が含まれています。多くの場合、RAC クラスタがネットワーク パスの変更やストレージ フェイルオーバー操作に耐えられるように、デフォルトの Oracle RAC 設定を変更する必要があります。



== ディスクタイムアウト

プライマリストレージ関連のRACパラメータはです。 `disktimeout`。このパラメータは、投票ファイルI/Oが完了しなければならないしきい値を制御します。状況に応じて `disktimeout` パラメータの値を超えると、そのRACノードがクラスタから削除されます。このパラメータのデフォルトは200です。ストレージのテイクオーバーとギブバックの標準的な手順では、この値で十分です。

テイクオーバーやギブバックには多くの要素が影響するため、NetAppでは、RAC構成を本番環境に導入する前に徹底的にテストすることを強く推奨します。ストレージフェイルオーバーの完了に必要な時間に加えて、Link Aggregation Control Protocol（LACP；リンクアグリゲーション制御プロトコル）の変更が伝播されるまでの時間も長くなります。また、SANマルチパスソフトウェアはI/Oタイムアウトを検出し、代替パスで再試行する必要があります。データベースが非常にアクティブな場合は、投票ディスクI/Oが処理される前に、大量のI/Oをキューに入れて再試行する必要があります。

ストレージのテイクオーバーやギブバックを実際に実行できない場合は、データベースサーバでケーブルを取り外すテストを実行して影響をシミュレートできます。

[TIP]
====
* NetAppの推奨事項*：

* を終了します。 `disktimeout` パラメータを指定します。デフォルト値は200です。
* RAC構成は常に十分にテストしてください。


====


== MissCount

。 `misscount` パラメータは通常、RACノード間のネットワークハートビートにのみ影響します。デフォルトは30秒です。Gridバイナリがストレージアレイ上にある場合やOSのブートドライブがローカルでない場合は、このパラメータが重要になることがあります。これには、ブートドライブがFC SANに配置されたホスト、NFSブートOS、およびVMDKファイルなどの仮想データストアに配置されたブートドライブが含まれます。

ブートドライブへのアクセスがストレージのテイクオーバーやギブバックによって中断された場合、Gridバイナリの場所またはOS全体が一時的に停止する可能性があります。ONTAPがストレージ処理を完了するのに必要な時間、およびOSがパスを変更してI/Oを再開するのに必要な時間が、 `misscount` しきい値。そのため、ブートLUNまたはGridバイナリへの接続がリストアされたあと、ノードはただちに削除されます。ほとんどの場合、削除とその後のリブートは実行されますが、リブートの理由を示すログメッセージは表示されません。すべての構成に影響するわけではないので、RAC環境内のSANブート、NFSブート、またはデータストアベースのホストをテストして、ブートドライブへの通信が中断してもRACが安定した状態になるようにします。

ローカルでないブートドライブまたはローカルでないファイルシステムをホストしている場合 `grid` バイナリ、 `misscount` 一致するように変更する必要があります `disktimeout`。このパラメータを変更した場合は、さらにテストを行い、ノードのフェイルオーバー時間など、RACの動作への影響を特定します。

[TIP]
====
* NetAppの推奨事項*：

* そのままにします。 `misscount` 次のいずれかの条件が適用されない場合は、デフォルト値の30のパラメータを使用します。
+
** `grid` バイナリは、iSCSI、FC、データストアベースのドライブなどのネットワーク接続ドライブ上に配置されます。
** OSがSANブートである。


* このような場合は、ネットワークの中断がOSへのアクセスに影響するか、 `GRID_HOME` ファイルシステム：このような中断によって原因Oracle RACデーモンが停止し、 `misscount`-ベースのタイムアウトおよび削除。タイムアウトのデフォルトは27秒です。これは `misscount` マイナス `reboottime`。このような場合、 `misscount` 200にして一致させる `disktimeout`。


====
[NOTE]
====
* ASA r2 の SAN 最適化設計によりフェイルオーバーの遅延は短縮されますが、ネットワーク ブートまたはグリッド バイナリのタイムアウトは依然として調整する必要があります。
* 拡張 RAC またはアクティブ / アクティブセットアップ ( SnapMirrorアクティブ シンクなど) の場合、ゼロ RPO アーキテクチャではタイムアウトの調整が依然として重要です。


====