---
sidebar: sidebar 
permalink: oracle/oracle-dp-snaprestore.html 
keywords: ontap, snaprestore 
summary: スナップショットによる高速Oracleデータベース リカバリ 
searchtitle: スナップショットによる高速Oracleデータベース リカバリ 
---
= SnapRestore
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAPでのSnapshotからの迅速なデータリストアは、NetApp SnapRestoreテクノロジによって提供され、AFFボリュームまたはASA LUNの状態を瞬時にリストアできます。

重要なデータセットが使用できないと、重要なビジネス処理が停止します。テープが破損する可能性があり、ディスク・ベースのバックアップからリストアする場合でも、ネットワーク上での転送に時間がかかることがあります。SnapRestoreでは、データセットをほぼ瞬時にリストアできるため、このような問題を回避できます。ペタバイト規模のデータベースでも、わずか数分で完全にリストアできます。

基本的なテクノロジは AFF と ASA のプラットフォームで同じですが、使用方法は若干異なります。



== AFFの概要

AFF システムには、SnapRestore の 2 つの形式があります。ファイルベースとボリュームベースです：

* 個々のAFFファイル、LUN、ネームスペース、および個々のASA LUNとネームスペースは、2TBのLUNでも4KBのファイルでも、数秒で復元できます。
* AFFボリュームの完全な内容は、10GBでも100TBでも、データ量に関わらず数秒で復元できます。


SnapRestoreがこれほど迅速かつ効率的に動作するのは、スナップショットの性質によるものです。スナップショットとは、基本的に、ボリューム、LUN、またはネームスペースの内容を特定の時点において並列的に読み取り専用で表示したものです。アクティブブロックとは、実際に変更可能なブロックのことです。一方、スナップショットとは、スナップショットが作成された時点でのファイルやLUNを構成するブロックの状態を読み取り専用で表示したものです。

ONTAPはスナップショットデータへの読み取り専用アクセスのみを許可しますが、データはSnapRestoreで再アクティブ化できます。スナップショットはデータの読み書きビューとして再度有効になり、データは以前の状態に戻ります。SnapRestoreは、ボリューム、ファイル、LUN、またはネームスペースのレベルで操作できます。基本的な技術は同じですが、動作に若干の違いがあります。



=== AFF ボリュームSnapRestore

ボリュームベースSnapRestoreは、ボリューム全体の内容を以前の状態に戻します。この処理ではデータの移動は不要なため、リストア プロセスは基本的に瞬時に完了しますが、APIまたはCLI処理には数秒かかる場合があります。1GBのデータをリストアすることは、1PBのデータをリストアすることと比べて、複雑さや時間の面で何ら変わりはありません。この機能は、多くの企業顧客がONTAPストレージ システムに移行する主な理由です。最大規模のデータセットでも、RTOを数秒単位で実現します。

ボリュームベースSnapRestoreの欠点の1つは、ボリューム内の変更が時間の経過とともに累積されることが原因です。したがって、各Snapshotとアクティブなファイルデータは、その時点までの変更に依存します。ボリュームを以前の状態にリバートすると、データに対する以降の変更がすべて破棄されます。ただし、これには以降に作成されたスナップショットが含まれることはあまり明白ではありません。これは必ずしも望ましいとは限りません。

たとえば、データ保持のSLAで夜間バックアップを30日間指定するとします。ボリュームSnapRestoreを使用して5日前に作成されたSnapshotにデータセットをリストアすると、過去5日間に作成されたSnapshotがすべて破棄され、SLAに違反します。

この制限に対処するために、いくつかのオプションが用意されています。

. ボリューム全体のSnapRestoreを実行するのではなく、以前のSnapshotからデータをコピーできます。この方法は、データセットが小さい場合に最も適しています。
. Snapshotはリストアではなくクローニングできます。このアプローチの制限事項は、ソーススナップショットがクローンの依存関係であることです。したがって、クローンも削除されるか、独立したボリュームにスプリットされないかぎり、削除することはできません。
. ファイルベースのSnapRestoreの使用。




=== AFF ファイルSnapRestore

ファイルベースSnapRestoreは、AFFボリュームで使用される、Snapshotベースのより詳細なリストア プロセスです。ボリューム全体の状態を元に戻すのではなく、個々のファイル、LUN、またはネームスペースの状態を元に戻します。Snapshotを削除する必要はなく、また、この処理によって以前のSnapshotへの依存関係が生じることもありません。ファイルまたはLUNは、アクティブ ボリューム内で即座に使用可能になります。

SnapRestoreによるファイルまたはLUNのリストア中に、データ移動は必要ありません。ただし、リストアされたデータの基盤となるブロックがSnapshotとアクティブ ボリュームの両方に存在するという事実を反映するために、一部の内部メタデータの更新が必要です。パフォーマンスへの影響はありませんが、このプロセスが完了するまでSnapshotの作成がブロックされます。処理速度は、リストアされるファイルの合計サイズに基づいて約5GBps（18TB/時間）です。



== ASA LUN/ネームスペースのリストア

ASAでのデータのリストアは、AFF SnapRestoreと同様です。データは単に以前の状態にリストアされるだけです。この処理はほぼ瞬時に完了し、データの移動も不要です。また、同様の制限事項もあり、スナップショットをリストアすると、その後に削除されたスナップショットも削除されるという要件が含まれます。これが問題となる場合は、2つの選択肢があります。まず、ソース ボリュームを変更せずに、以前のスナップショットからLUN/ネームスペースをクローニングすることができます。これは瞬時に完了し、スペース効率に優れたプロセスです。これは基本的に、スナップショット内のブロックへの読み取り専用ポインタの読み書き可能なコピーを作成するものです。2つ目の選択肢はREST APIを使用する方法で、AFFシステムで使用されているものと同じ単一ファイルSnapRestoreロジックを使用できます。その結果、スナップショットのデータを使用してLUN/ネームスペースが瞬時にリストアされ、すべてのスナップショットが保持されます。
