---
sidebar: sidebar 
permalink: oracle/oracle-dr-smas-fail-interconnect.html 
keywords: Oracle, SnapMirror active sync, SMBC, failover 
summary: OracleとSnapMirrorのアクティブな同期フェイルオーバー 
---
= SnapMirrorアクティブ同期- Oracle RACレプリケーションが停止
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Oracle RACレプリケーションリンクが失われると、SnapMirror接続が切断されますが、デフォルトでタイムアウトが短くなる点が異なります。デフォルト設定では、Oracle RACノードはストレージ接続が失われてから200秒待機してから削除されますが、RACネットワークハートビートが失われてからは30秒しか待機しません。

CRSメッセージは次のようになります。30秒のタイムアウトの経過が表示されます。CSS_CRITICALはサイトAにあるjfs12に設定されているため、これが存続するサイトとなり、サイトBのjfs13が削除されます。

....
2024-09-12 10:56:44.047 [ONMD(3528)]CRS-1611: Network communication with node jfs13 (2) has been missing for 75% of the timeout interval.  If this persists, removal of this node from cluster will occur in 6.980 seconds
2024-09-12 10:56:48.048 [ONMD(3528)]CRS-1610: Network communication with node jfs13 (2) has been missing for 90% of the timeout interval.  If this persists, removal of this node from cluster will occur in 2.980 seconds
2024-09-12 10:56:51.031 [ONMD(3528)]CRS-1607: Node jfs13 is being evicted in cluster incarnation 621599354; details at (:CSSNM00007:) in /gridbase/diag/crs/jfs12/crs/trace/onmd.trc.
2024-09-12 10:56:52.390 [CRSD(6668)]CRS-7503: The Oracle Grid Infrastructure process 'crsd' observed communication issues between node 'jfs12' and node 'jfs13', interface list of local node 'jfs12' is '192.168.30.1:33194;', interface list of remote node 'jfs13' is '192.168.30.2:33621;'.
2024-09-12 10:56:55.683 [ONMD(3528)]CRS-1601: CSSD Reconfiguration complete. Active nodes are jfs12 .
2024-09-12 10:56:55.722 [CRSD(6668)]CRS-5504: Node down event reported for node 'jfs13'.
2024-09-12 10:56:57.222 [CRSD(6668)]CRS-2773: Server 'jfs13' has been removed from pool 'Generic'.
2024-09-12 10:56:57.224 [CRSD(6668)]CRS-2773: Server 'jfs13' has been removed from pool 'ora.NTAP'.
....