---
sidebar: sidebar 
permalink: oracle/oracle-asar2-config-failover.html 
keywords: failover, takeover, ASA r2, oracle 
summary: Oracle データベースの操作がこれらの操作によって中断されないようにするには、ストレージ テイクオーバー機能について理解する必要があります。さらに、テイクオーバー操作で使用される引数は、誤って使用されるとデータの整合性に影響を与える可能性があります。 
searchtitle: ASA r2 での Oracle データベースとONTAPコントローラのフェイルオーバー 
---
= ONTAPフェイルオーバー
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
これらの操作中に Oracle データベースの操作が中断されないようにするには、ストレージ テイクオーバー機能について理解する必要があります。さらに、テイクオーバー操作で使用される引数は、誤って使用されるとデータの整合性に影響を与える可能性があります。

通常の状況では、特定のコントローラへの着信書き込みは、その HA パートナーに同期的にミラーリングされます。SnapMirror Active Sync (SM-as) を備えたASA r2 環境では、書き込みはセカンダリ サイトのリモート コントローラにもミラーリングされます。書き込みが不揮発性メディアのすべての場所に保存されるまで、ホスト アプリケーションに確認応答されません。

書き込みデータを保存するメディアは不揮発性メモリ (NVMEM) と呼ばれます。これは、不揮発性ランダム アクセス メモリ (NVRAM) と呼ばれることもあり、キャッシュではなく書き込みジャーナルと考えることができます。通常の動作中、 NVMEMからのデータは読み取られず、ソフトウェアまたはハードウェア障害が発生した場合にデータを保護するためだけに使用されます。データがドライブに書き込まれる場合、データはNVMEMからではなくシステム RAM から転送されます。

テイクオーバー操作中、HA ペアの 1 つのノードがパートナーから操作を引き継ぎます。ASA r2 では、 MetroClusterがサポートされていないため、スイッチオーバーは適用されません。代わりに、 SnapMirror Active Sync によってサイト レベルの冗長性が提供されます。定期メンテナンス中のストレージ引き継ぎ操作は、ネットワーク パスの変更による操作の短時間の一時停止を除き、透過的である必要があります。ネットワークは複雑でエラーが発生しやすいため、 NetApp、ストレージ システムを実稼働させる前にテイクオーバー操作を徹底的にテストすることを強くお勧めします。そうすることが、すべてのネットワーク パスが正しく構成されていることを確認する唯一の方法です。SAN環境では、次のコマンドを使用してパスのステータスを確認します。 `sanlun lun show -p` または、オペレーティング システムのネイティブ マルチパス ツールを使用して、予想されるすべてのパスが利用可能であることを確認します。ASA r2 システムは LUN のすべてのアクティブな最適化されたパスを提供しますが、NVMe パスは sanlun によってカバーされていないため、NVMe 名前空間を使用する顧客は OS ネイティブ ツールに依存する必要があります。

強制買収を発行する際には注意が必要です。ストレージ構成を強制的に変更すると、ドライブを所有するコントローラの状態は無視され、代替ノードが強制的にドライブを制御することになります。強制テイクオーバーによってNVMEMの内容が破棄される可能性があるため、テイクオーバーを誤って強制すると、データの損失や破損が発生する可能性があります。引き継ぎが完了した後、そのデータが失われると、ドライブに保存されたデータは、データベースの観点から見ると少し古い状態に戻る可能性があります。

通常の HA ペアでは強制テイクオーバーが必要になることはほとんどありません。ほとんどすべての障害シナリオでは、ノードがシャットダウンし、自動フェイルオーバーが行われるようにパートナーに通知します。ノード間の相互接続が失われ、その後 1 つのコントローラーに障害が発生するローリング障害など、強制テイクオーバーが必要となるエッジ ケースがいくつかあります。このような状況では、コントローラの障害発生前にノード間のミラーリングが失われ、残りのコントローラには進行中の書き込みのコピーが残っていないことになります。その場合、強制的に引き継ぎを行う必要があり、データが失われる可能性があります。

[TIP]
====
NetApp、次の予防措置を講じることを推奨しています。

* 誤って強制的に買収を行わないよう十分注意してください。通常、強制する必要はありませんが、強制的に変更するとデータが失われる可能性があります。
* 強制テイクオーバーが必要な場合は、アプリケーションがシャットダウンされ、すべてのファイル システムがマウント解除され、論理ボリューム マネージャ(LVM) ボリューム グループが varyoff されていることを確認します。ASM ディスクグループをアンマウントする必要があります。
* SM-as の使用時にサイトレベルの障害が発生した場合、 ONTAP Mediator による自動計画外フェイルオーバーが存続クラスタで開始され、I/O が短時間停止した後、存続クラスタからデータベースの移行が続行されます。詳細については、 https://docs.netapp.com/us-en/asa-r2/data-protection/configure-snapmirror-active-sync.html["ASA r2 システムでのSnapMirrorアクティブ同期"] 詳細な設定手順については、こちらをご覧ください。


====