---
sidebar: sidebar 
permalink: oracle/oracle-tiering-backups.html 
keywords: tiering, fabricpool 
summary: Oracleバックアップの階層化 
searchtitle: Oracleデータベースバックアップの階層化 
---
= バックアップの階層化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
従来のアプリケーションバックアップには、Oracle Recovery Managerなどの製品が含まれています。Oracle Recovery Managerは、元のデータベースの場所以外にファイルベースのバックアップを作成します。

 `tiering-minimum-cooling-days` policy of a few days preserves the most recent backups, and therefore the backups most likely to be required for an urgent recovery situation, on the performance tier. The data blocks of the older files are then moved to the capacity tier.
。 `auto` ポリシーは、バックアップデータに最も適したポリシーです。これにより、ファイルが削除されたか、プライマリファイルシステムに引き続き存在しているかに関係なく、クーリングしきい値に達したときに迅速に階層化されます。必要となる可能性があるすべてのファイルをアクティブファイルシステムの1つの場所に格納することも、管理を簡易化します。リストアが必要なファイルを特定するためにSnapshotを検索する必要はありません。

。 `snapshot-only` ポリシーは機能するように設定できますが、アクティブファイルシステムに存在しなくなった環境ブロックのみが対象となります。そのため、データを階層化するには、まずNFS共有またはSMB共有上のファイルを削除する必要があります。

LUNからファイルを削除するとファイル参照がファイルシステムのメタデータから削除されるだけなので、このポリシーはLUN設定の場合はさらに効率的ではありません。LUN上の実際のブロックは、上書きされるまでそのまま維持されます。このような状況では、ファイルが削除されてブロックが上書きされて階層化の候補になるまでに長時間の遅延が発生する可能性があります。の移動にはいくつかの利点があります。 `snapshot-only` ブロックは大容量階層に移動しますが、全体的にはバックアップデータのFabricPool管理が最適なのは、 `auto` ポリシー：


NOTE: このアプローチは、バックアップに必要なスペースをより効率的に管理するのに役立ちますが、FabricPool自体はバックアップテクノロジではありません。バックアップファイルをオブジェクトストアに階層化すると、ファイルは元のストレージシステムに引き続き表示されるため、管理が簡易化されますが、オブジェクトストアデスティネーションのデータブロックは元のストレージシステムに依存します。ソースボリュームが失われると、オブジェクトストアのデータを使用できなくなります。
