---
sidebar: sidebar 
permalink: oracle/oracle-asar2-network-config-fc.html 
keywords: SAN, zoning, ASA r2 
summary: ASA r2 を使用した Oracle データベースの FC ネットワーク構成 
searchtitle: ASA r2 を使用した Oracle データベースの FC SAN 構成 
---
= FC SAN構成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ASA r2 システム上の Oracle データベース用に FC SAN を構成するには、主に標準の SAN ベスト プラクティスに従う必要があります。

ASA r2 は SAN のみのワークロード向けに最適化されているため、原則はAFF/ FASと同じで、パフォーマンス、復元力、シンプルさに重点が置かれています。これには、ホストとストレージ システム間の SAN に十分な帯域幅があることを確認する、必要なすべてのデバイス間にすべての SAN パスが存在することを確認する、FC スイッチ ベンダーが要求する FC ポート設定を使用する、ISL の競合を回避する、適切な SAN ファブリック モニタリングを使用するなどの一般的な計画対策が含まれます。



== ゾーニング

FCゾーンに複数のイニシエータを含めることはできません。このような配置は最初は機能しているように見えるかもしれませんが、最終的にはイニシエータ間のクロストークがパフォーマンスと安定性の妨げになります。

マルチターゲットゾーンは一般に安全とみなされますが、まれに、ベンダーが異なるFCターゲットポートの動作が問題を引き起こすことがあります。たとえば、NetAppとネットアップ以外のストレージアレイのターゲットポートを同じゾーンに配置することは避けてください。また、NetAppストレージシステムとテープデバイスを同じゾーンに配置すると、原因の問題が発生する可能性がさらに高くなります。

[NOTE]
====
* ASA r2 は集約の代わりにストレージ可用性ゾーンを使用しますが、これによって FC ゾーン分割の原則は変更されません。
* マルチパス (MPIO) は依然として主要な復元力メカニズムですが、対称アクティブ / アクティブマルチパスをサポートするASA r2 システムでは、LUN へのすべてのパスがアクティブになり、同時に I/O に使用されます。


====