---
sidebar: sidebar 
permalink: oracle/oracle-dr-snapmirror-basics.html 
keywords: ontap, snapmirror 
summary: SnapMirrorとSyncMirror 
---
= SnapMirrorとSyncMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ほぼすべてのアプリケーションでデータレプリケーションが必要です。

最も基本的なレベルでは、レプリケーションとは、オフサイトに保管されたテープ上のコピー、またはスタンバイロケーションへのアプリケーションレベルのレプリケーションを意味します。ディザスタリカバリとは、サービスが壊滅的に失われた場合に、これらのレプリカコピーを使用してサービスをオンラインにすることです。

ONTAPには、ストレージアレイ内でネイティブにさまざまな要件に対応するための複数のレプリケーションオプションが用意されており、あらゆるニーズに対応します。これらのオプションには、同じプラットフォームでディザスタリカバリと高可用性の両方を実現する、完全に自動化された同期解決策まで、リモートサイトへのシンプルなバックアップレプリケーションが含まれます。

アプリケーションに適用される主要なONTAPレプリケーションテクノロジは、NetAppのSnapMirrorテクノロジとNetApp SyncMirrorテクノロジです。これらはアドオン製品ではなく、ONTAPに完全に統合され、ライセンスキーを追加するだけでアクティブ化されます。また、ストレージレベルのレプリケーションだけが選択肢ではありません。Oracle DataGuardなどのアプリケーションレベルのレプリケーションを、ONTAPに基づくデータ保護戦略に統合することもできます。

適切な選択は、特定のレプリケーション、リカバリ、保持の要件によって異なります。



== ONTAP SnapMirror

SnapMirrorは、NetAppの非同期レプリケーション解決策です。データベースやその関連アプリケーションなど、複雑で動的な大規模データセットの保護に最適です。主な値は次のとおりです。

* *管理性。* SnapMirrorは、ストレージソフトウェアに標準で組み込まれているため、設定と管理が容易です。アドオン製品は必要ありません。レプリケーション関係は数分で確立でき、ストレージシステム上で直接管理できます。
* *シンプルさ。*レプリケーションはボリュームに基づいています。FlexVolボリュームはLUNまたはファイルのコンテナであり、単一の整合グループとしてレプリケートされます。
* *効率性。*最初のレプリケーション関係が確立されると、変更のみがレプリケートされます。さらに、重複排除や圧縮などの効率化機能が維持されるため、リモートサイトに転送するデータ量がさらに削減されます。
* *柔軟性。*ミラーを一時的に切断して災害復旧手順をテストできるため、完全な再ミラーリングを必要とせずにミラーリングを簡単に再確立できます。ミラーを同期状態に戻すには、変更されたデータのみを適用する必要があります。ミラーリングを反転することで、災害が終了して元のサイトが稼働状態に戻ったあとに迅速に再同期することもできます。最後に、レプリケートされたデータの読み取り/書き込みクローンをテストと開発に使用できます。


ONTAPにはさまざまなレプリケーションテクノロジが用意されていますが、最も柔軟性に優れたのは、ボリューム間の非同期ミラーリングオプションであるSnapMirrorです。

前述したように、FlexVolボリュームは、SnapshotベースのバックアップとSnapRestoreベースのリカバリの基本的な管理単位です。FlexVolボリュームは、SnapMirrorベースのレプリケーションの基本単位でもあります。最初に、ソースボリュームからデスティネーションボリュームへのベースラインミラーを確立します。このミラー関係を初期化すると、以降のすべての処理は変更されたデータのみのレプリケーションに基づいて行われます。

リカバリの観点から見ると、SnapMirrorの主な価値は次のとおりです。

* SnapMirrorの操作は理解しやすく、簡単に自動化できます。
* SnapMirrorレプリカを単純に更新するには、差分の変更のみをレプリケートする必要があるため、帯域幅の需要が減り、更新頻度が向上します。
* SnapMirrorは非常にきめ細かな機能です。シンプルなボリューム間の関係に基づいているため、独立して管理される数百個のレプリカやレプリケーション間隔を作成できます。レプリケーションを万能である必要はありません。
* 変更だけに基づいて関係を更新する機能を維持しながら、ミラーリングの方向を簡単に反転できます。これにより、電源障害などの災害後にプライマリサイトが復旧したあとに、迅速なフェイルバック機能が提供されます。変更のみをソースに同期化する必要があります。
* ミラーは簡単に破損し、効率的に再同期することで、ディザスタリカバリ手順のリハーサルを行うことができます。
* SnapMirrorはフルブロックレベルのレプリケーションモードで動作し、ボリューム内のデータだけでなくSnapshotもレプリケートします。この機能は、ディザスタリカバリサイトにデータのコピーと完全なバックアップセットの両方を提供します。


SnapMirrorはバージョンに依存しないモードで動作するため、特定のSnapshotをレプリケートでき、プライマリサイトとセカンダリサイトで異なる保持期間を設定できます。



== SnapMirror Synchronous

SnapMirror Synchronous（SM-S）は、RPO=0の同期レプリケーションを提供するSnapMirrorの機能拡張です。同期ミラーリングが必要なデータの一部しかないストレージアーキテクチャでよく使用されます。

SM-Sは、SyncとStrictSyncの2つのわずかに異なるモードで動作できます。

同期モードでは、確認される前に変更がレプリケートされます。これにより、レプリケーションが稼働しているかぎり、RPOはゼロになります。変更を複製できない場合、SM-Sは同期モードを終了し、操作を続行できます。これにより、通常の状況ではRPO=0になりますが、レプリケーション先が使用できない場合にデータプロセスが完全に停止することはありません。

StrictSyncはRPO = 0を保証します。変更のレプリケートに失敗するとI/Oエラーが発生し、通常はアプリケーションがシャットダウンします。

SM-Sの詳細については、を参照してください。 https://www.netapp.com/media/17174-tr4733.pdf?v=1221202075448P["TR-4733"^] ONTAPの公式ドキュメントを参照してください。ONTAPの新しいバージョンでは、機能が継続的に追加されています。



== 整合グループ

ONTAPでは整合グループSnapshotを作成できます。9.13.1以降では、ONTAPでボリュームのグループを整合グループとしてレプリケートできます（ONTAP用語のボリュームはLUNではなく、1つ以上のファイルまたはLUNで構成される管理コンテナです）。

SnapMirrorレプリケーションとCG SnapMirror関係の解除では、ボリューム間で整合性が維持され、SnapMirror SynchronousとSnapMirror Business Continuityはどちらもコンスティチュエントボリューム間で整合性が維持されます。

その結果、複数ボリュームのデータセットをレプリケートして、すべてのボリュームの整合性を確保できます。特に、アプリケーションやデータベースのリカバリを追加することなく、ミラーを解除してDR処理を実行できます。



== MetroClusterとSyncMirror

MetroClusterは、大規模なミッションクリティカルなワークロードを対象とした同期レプリケーション解決策でもあります。レプリケーションはSyncMirrorに基づいています。最も単純なレイヤでは、SyncMirrorは2つの異なる場所にRAID保護データの完全なセットを作成します。データセンター内の隣接する部屋に配置することも、数キロメートル離れた場所に配置することもできます。

SyncMirrorはONTAPと完全に統合されており、RAIDレベルのすぐ上で動作します。そのため、Snapshotコピー、SnapRestore、NetApp FlexCloneなど、ONTAPの通常の機能はすべてシームレスに動作します。これはONTAPであり、同期データミラーリングの追加レイヤが含まれているだけです。

SyncMirrorデータを管理するONTAPコントローラの集まりをNetApp MetroCluster構成と呼びます。MetroClusterの主な目的は、一般的な障害やディザスタリカバリのさまざまな障害シナリオにおいて、同期ミラーリングされたデータへの高可用性アクセスを提供することです。

MetroClusterとSyncMirrorを使用したデータ保護の主な価値は次のとおりです。

* 通常運用時には、SyncMirrorは複数のサイト間の同期ミラーリングを保証します。書き込み処理は、両方のサイトの不揮発性メディアに存在するまで確認応答されません。
* サイト間の接続に障害が発生すると、SyncMirrorは自動的に非同期モードに切り替わり、接続が回復するまでプライマリサイトがデータを提供し続けます。リストア時には、プライマリサイトに蓄積された変更を効率的に更新することで、迅速な再同期を実現します。完全な再初期化は必要ありません。


SnapMirrorは、SyncMirrorベースのシステムとも完全に互換性があります。たとえば、プライマリデータベースが2つの地理的なサイトに分散したMetroClusterクラスタで実行されているとします。このデータベースは、長期アーカイブやDevOps環境でのクローン作成のために、バックアップを第3のサイトにレプリケートすることもできます。
