---
sidebar: sidebar 
permalink: oracle/oracle-asar2-app-config-block-sizes.html 
keywords: oracle, database, ASA r2, ontap, SAN, ASM, blocks 
summary: ASA r2 を使用した Oracle データベースのブロック サイズ 
searchtitle: ASA r2 を使用した Oracle データベースのブロック サイズ 
---
= ブロックサイズ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP は内部的に可変ブロック サイズを使用するため、Oracle データベースは任意のブロック サイズで構成できます。ただし、ファイルシステムのブロック サイズはパフォーマンスに影響を与える可能性があり、場合によっては、REDO ブロック サイズを大きくするとパフォーマンスが向上することがあります。

ASA r2 では、 AFF/ FASシステムと比較して、Oracle ブロック サイズの推奨事項に変更はありません。ONTAP の動作はすべてのプラットフォームで一貫しています。



== データファイルのブロックサイズ

OSによっては、ファイルシステムのブロックサイズを選択できます。Oracleデータファイルをサポートするファイルシステムでは、圧縮を使用する場合にブロックサイズを8KBにする必要があります。圧縮が不要な場合は、8KBまたは4KBのブロックサイズを使用できます。

512バイトのブロックを使用するファイルシステムにデータファイルが配置されていると、ファイルのミスアライメントが発生する可能性があります。LUNとファイルシステムはNetAppの推奨事項に基づいて適切にアライメントされていても、ファイルI/Oはミスアライメントされます。このようなミスアライメントが発生すると、原因で重大なパフォーマンス問題が発生します。



== Redoブロックサイズ

Redoログをサポートするファイルシステムでは、Redoブロックサイズの倍数のブロックサイズを使用する必要があります。そのためには、通常、RedoログファイルシステムとRedoログ自体の両方で512バイトのブロックサイズを使用する必要があります。

Redo率が非常に高い場合は、少ない処理で効率よくI/Oを実行できるため、4KBのブロックサイズの方がパフォーマンスが向上する可能性があります。Redo率が50MBpsを超える場合は、4KBのブロックサイズをテストすることを検討してください。

一部のお客様では、ブロックサイズが512バイトのRedoログをブロックサイズが4KBのファイルシステムで使用し、非常に小さなトランザクションが大量に発生するという問題が報告されています。このパフォーマンスの問題は、複数の512バイトの変更を4KBの単一のファイルシステムブロックに適用する際のオーバーヘッドが原因で発生していましたが、ファイルシステムのブロックサイズを512バイトに変更することで解決されました。


TIP: * NetAppでは、関連するカスタマーサポートまたはプロフェッショナルサービス部門から指示があった場合、または正式な製品ドキュメントに基づく場合を除き、Redoブロックサイズを変更しないことを推奨しています*。
