---
sidebar: sidebar 
permalink: oracle/oracle-tiering-snapshots.html 
keywords: tiering, fabricpool 
summary: Oracleスナップショットの階層化 
---
= Oracleスナップショットの階層化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
FabricPoolの初期リリースでは、バックアップのユースケースを対象としていました。階層化できるブロックのタイプは、アクティブファイルシステム内のデータに関連付けられなくなったブロックだけです。そのため、大容量階層に移動できるのはSnapshotデータブロックだけです。これは、パフォーマンスに影響を与えないようにする必要がある場合に、最も安全な階層化オプションの1つです。



== ポリシー-ローカルSnapshot

アクセス頻度の低いSnapshotブロックを大容量階層に階層化する方法は2つあります。まず、 `snapshot-only` ポリシーはSnapshotブロックのみを対象としています。ただし、 `auto` ポリシーには、 `snapshot-only` ブロックの場合は、アクティブファイルシステムのブロックも階層化されます。これは望ましくない可能性があります。

。 `tiering-minimum-cooling-days` この値は、リストア時に必要となる可能性のあるデータを高パフォーマンス階層で使用できるようにする期間に設定する必要があります。たとえば、重要な本番環境データベースのリストアシナリオのほとんどには、過去数日間のある時点のリストアポイントが含まれます。セッテイ `tiering-minimum-cooling-days` 値を3に設定すると、ファイルをリストアしたときにパフォーマンスがすぐに最大になるようにファイルが作成されます。アクティブファイル内のすべてのブロックは、大容量階層からリカバリすることなく高速ストレージに残ります。



== ポリシー-レプリケートされたSnapshot

リカバリのみに使用されるSnapMirrorまたはSnapVaultでレプリケートされるSnapshotには、一般にFabricPoolを使用する必要があります。 `all` ポリシー：このポリシーでは、メタデータはレプリケートされますが、すべてのデータブロックがただちに大容量階層に送信されるため、パフォーマンスが最大限に向上します。ほとんどのリカバリプロセスではシーケンシャルI/Oが発生しますが、これは本質的に効率的です。オブジェクトストアのデスティネーションからのリカバリ時間を評価する必要がありますが、適切に設計されたアーキテクチャでは、このリカバリプロセスにローカルデータからのリカバリよりも大幅に時間がかかる必要はありません。

レプリケートされたデータをクローニングにも使用する場合は、 `auto` ポリシーはより適切であり、 `tiering-minimum-cooling-days` クローニング環境で定期的に使用されることが期待されるデータを含む価値。たとえば、データベースのアクティブなワーキングセットには、過去3日間に読み書きされたデータが含まれている場合がありますが、さらに6カ月分の履歴データが含まれている場合もあります。その場合は、 `auto` SnapMirrorデスティネーションでポリシーを設定すると、作業セットを高パフォーマンス階層で使用できるようになります。
