---
sidebar: sidebar 
permalink: oracle/oracle-asar2-dp-nvfail.html 
keywords: oracle, nvfail, ASA r2 
summary: ASA r2 上の Oracle データベースを保護するための NVFAIL の設定 
searchtitle: Oracle データベースとASA r2 上の NVFAIL 
---
= NVFail
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NVFAIL は、壊滅的なフェイルオーバー シナリオ中にデータの整合性を保証するONTAP機能です。

ASA r2 は簡素化された SAN アーキテクチャ (ボリュームの代わりに SAZ とストレージ ユニット) を使用しますが、この機能はASA r2 システムにも適用できます。

データベースは大きな内部キャッシュを保持しているため、ストレージ フェイルオーバー イベント中に破損する危険性が高くなります。壊滅的なイベントによりONTAPフェイルオーバーを強制する必要がある場合、全体的な構成の健全性に関係なく、結果として以前に確認された変更は事実上破棄される可能性があります。ストレージ アレイの内容は過去に遡り、データベース キャッシュの状態はディスク上のデータの状態を反映しなくなります。この不整合により、データ破損。

キャッシュはアプリケーション層またはサーバー層で発生する可能性があります。たとえば、プライマリ サイトとリモート サイトの両方でサーバーがアクティブになっている Oracle Real Application Cluster (RAC) 構成では、Oracle SGA 内にデータがキャッシュされます。強制フェイルオーバー操作によってデータが失われると、SGA に格納されているブロックがディスク上のブロックと一致しない可能性があるため、データベースが破損するリスクが生じます。

キャッシュのあまり知られていない使用法は、OS ファイル システム層です。プライマリ サイトにある LUN に基づくクラスター化されたファイル システムをリモート サイトのサーバーにマウントし、再度データをキャッシュすることができます。このような状況でNVRAMに障害が発生したり、強制的に引き継がれたりすると、ファイル システムが破損する可能性があります。

ONTAP は、NVFAIL とその関連設定を使用してデータベースとオペレーティング システムをこのシナリオから保護します。NVFAIL と関連設定は、キャッシュされたデータを無効にして、フェイルオーバー後に影響を受けるファイル システムを再マウントようにホストに信号を送ります。このメカニズムは、 AFF/ FASの場合と同様に、 ASA r2 LUN および名前空間に適用されます。

[NOTE]
====
ASA r2 の主な考慮事項:

* NVFAIL は SAZ レベルではなく、LUN レベル (ストレージ ユニット) で動作します。
* Oracle データベースの場合、重要なコンポーネント (データファイル、REDO ログ、制御ファイル) をホストするすべての LUN で NVFAIL を有効にする必要があります。
* MetroClusterはASA r2 ではサポートされていないため、NVFAIL は主にローカル HA フェイルオーバー シナリオに適用されます。
* NFS はASA r2 ではサポートされていないため、NVFAIL の考慮事項は SAN ベースのワークロード (FC/iSCSI/NVMe) にのみ適用されます。


====