---
sidebar: sidebar 
permalink: oracle/oracle-asar2-storage-san-config-lun-alignment.html 
keywords: SAN, ASM, LVM, oracle, ASA r2 
summary: ASA r2上のOracleデータベースとのLUNアライメント 
searchtitle: ASA r2 を使用した Oracle データベース I/O の LUN アライメント 
---
= LUNアライメント
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
LUNアライメントとは、基盤となるファイルシステムのレイアウトに合わせてI/Oを最適化することです。

ASA r2 システムは、 AFF/ FASと同じONTAPアーキテクチャを使用しますが、構成モデルは簡素化されています。ASA r2 システムは、アグリゲートの代わりにストレージ アベイラビリティ ゾーン (SAZ) を使用しますが、 ONTAP はプラットフォーム間で一貫してブロック レイアウトを管理するため、アライメントの原則は同じままです。ただし、次のASA固有の点に注意してください。

* ASA r2 システムは、すべての LUN に対してアクティブ / アクティブ対称パスを提供するため、アライメント中のパスの非対称性に関する懸念が排除されます。
* ストレージ ユニット (LUN) はデフォルトでシンプロビジョニング。アライメントによってこの動作は変更されません。
* SnapshotリザーブとSnapshotの自動作成削除は、LUN の作成中に設定できます (ONTAP 9.18.1 以降)。


ONTAPシステムでは、ストレージは4KB単位で編成されます。データベースまたはファイルシステムの8KBブロックは、4KBブロック2個に正確にマッピングする必要があります。LUNの構成エラーによってアライメントがいずれかの方向に1KBずれた場合、8KBの各ブロックは、4KBのストレージブロックが2つではなく3つに配置されます。このようにすると、原因によってレイテンシが増加し、ストレージシステム内で実行される原因の追加I/Oが発生します。

アライメントはLVMアーキテクチャにも影響します。論理ボリュームグループ内の物理ボリュームがドライブデバイス全体に定義されている場合（パーティションは作成されません）、LUN上の最初の4KBブロックがストレージシステム上の最初の4KBブロックとアライメントされます。これは正しいアライメントです。パーティションで問題が発生するのは、OSがLUNを使用する開始場所が変わるためです。オフセットが4KB単位でずれているかぎり、LUNはアライメントされます。

Linux環境では、ドライブデバイス全体に論理ボリュームグループを構築します。パーティションが必要な場合は、アライメントをチェックするためにを実行し、各パーティションが8の倍数で開始されていることを確認します `fdisk -u`。つまり、パーティションは8の倍数の512バイトセクター（4KB）から開始されます。

圧縮ブロックのアライメントに関するセクションも参照してくださいlink:oracle-ontap-config-efficiency.html["効率性"]。8KBの圧縮ブロックの境界でアライメントされたレイアウトも、4KBの境界でアライメントされます。



== ミスアライメントノケイコク

データベースのRedo /トランザクションログでは通常、アライメントされていないI/Oが生成されるため、ONTAPでLUNがミスアライメントされているという警告が原因で誤って表示される可能性があります。

ロギングは、さまざまなサイズの書き込みでログファイルのシーケンシャルライトを実行します。4KBの境界にアライメントされないログ書き込み処理では、次のログ書き込み処理でブロックが完了するため、通常は原因のパフォーマンスの問題は発生しません。その結果、一部の4KBブロックが2つの別 々 の処理で書き込まれていても、ONTAPはほぼすべての書き込みを完全な4KBブロックとして処理できます。

次のようなユーティリティを使用してアライメントを検証します。 `sio` または `dd` 定義されたブロック サイズで I/O を生成できます。ストレージシステムのI/Oアライメント統計は、 `stats` 指示。見る link:../notes/wafl_alignment_verification.html["WAFLアライメントの検証"] 詳細についてはこちらをご覧ください。

Solaris環境ではアライメントがより複雑になります。を参照してください http://support.netapp.com/documentation/productlibrary/index.html?productID=61343["ONTAP SAN ホスト構成"^] を参照してください。

[CAUTION]
====
Solaris x86環境では、ほとんどの構成に複数のパーティションレイヤがあるため、適切なアライメントにさらに注意してください。Solaris x86パーティションスライスは通常、標準のマスターブートレコードパーティションテーブルの上に存在します。

====
追加のベストプラクティス:

* HBA ファームウェアと OS 設定をNetApp Interoperability Matrix Tool (IMT) と照合して検証します。
* sanlun ユーティリティを使用して、パスの健全性と配置を確認します。
* Oracle ASM および LVM の場合、アライメントの問題を回避するために、構成ファイル (/etc/lvm/lvm.conf、/etc/sysconfig/oracleasm) が適切に設定されていることを確認してください。

