---
sidebar: sidebar 
permalink: oracle/oracle-asar2-host-config-aix.html 
keywords: oracle, database, ASA r2, ontap, aix, cio 
summary: ASA r2 上の AIX を使用した Oracle データベース 
searchtitle: ASA r2 上の IBM AIX を使用した Oracle データベース 
---
= AIX の場合
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ASA r2 ONTAPを搭載した IBM AIX 上の Oracle データベースの構成トピック。

[NOTE]
====
次の条件を満たす場合、AIX は Oracle データベースのホスティング用にNetApp ASA r2 でサポートされます。

* Oracle を同時 I/O 用に適切に構成します。
* サポートされている SAN プロトコル (FC/iSCSI/NVMe) を使用します。
* ASA r2 でONTAP 9.16.x 以降を実行します。


====


== 同時I/O

ASA r2 を搭載した IBM AIX で最適なパフォーマンスを実現するには、同時 I/O を使用する必要があります。同時 I/O がない場合、AIX はシリアル化されたアトミック I/O を実行するため、大きなオーバーヘッドが発生し、パフォーマンスが制限される可能性があります。

当初、 NetAppは `cio` ファイルシステム上で同時 I/O を強制するマウントオプションがありましたが、このプロセスには欠点があり、現在は必要ありません。AIX 5.2 および Oracle 10gR1 の導入以降、AIX 上の Oracle は、ファイル システム全体で同時 I/O を強制するのではなく、同時 I/O 用に個々のファイルを開くことができます。

同時I/Oを有効にする最適な方法は、 `init.ora` パラメータ `filesystemio_options` 終了： `setall`。これにより、Oracleが特定のファイルを開いて同時I/Oで使用できるようになります。

cio をマウント オプションとして使用すると、同時 I/O の使用が強制され、悪影響が生じる可能性があります。たとえば、同時 I/O を強制すると、ファイル システムでの先読みが無効になり、ファイルのコピーやテープ バックアップの実行など、Oracle データベース ソフトウェアの外部で発生する I/O のパフォーマンスが低下する可能性があります。さらに、Oracle GoldenGate や SAP BR*Tools などの製品は、特定のバージョンの Oracle では cio マウント オプションの使用と互換性がありません。

[TIP]
====
* NetAppの推奨事項*：

* を使用しないでください `cio` ファイルシステムレベルのマウントオプション。代わりに、を使用して同時I/Oを有効にします。 `filesystemio_options=setall`。
* のみを使用してください `cio` 設定できない場合はマウントオプション `filesystemio_options=setall`。


====

NOTE: ASA r2 は NAS をサポートしていないため、AIX 上のすべての Oracle デプロイメントではブロック プロトコルを使用する必要があります。



== AIX JFS / JFS2のマウントオプション

次の表に、AIX JFS / JFS2のマウントオプションを示します。

|===
| ファイルタイプ | マウントオプション 


| ADRホーム | デフォルト値です 


| 制御ファイル | デフォルト値です 


| データファイル | デフォルト値です 


| Redo logs | デフォルト値です 


| ORACLE_HOME を参照してください | デフォルト値です 
|===
AIXを使用する前に `hdisk` データベースを含むあらゆる環境のデバイスでは、パラメータをチェックします `queue_depth`。このパラメータはHBAのキュー深度ではなく、個々のSCSIキュー深度に関係します。 `hdisk device`。ASA r2 LUNの設定方法に応じて、 `queue_depth` 良好なパフォーマンスを得るには低すぎる可能性があります。テストの結果、最適値は 64 であることが分かりました。
