---
sidebar: sidebar 
permalink: oracle/oracle-dp-planning.html 
keywords: data protection, DR, snapshots, CG 
summary: Oracleデータベースのデータ保護計画 
searchtitle: Oracleデータベースのデータ保護計画 
---
= データ保護計画
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Oracleデータベースに最適なデータ保護アーキテクチャは、データの保持、リカバリ性、さまざまなイベント時のシステム停止に対する耐性に関するビジネス要件によって異なります。

たとえば、対象となるアプリケーション、データベース、重要なデータセットの数を考えてみましょう。管理するオブジェクトが少ないため、一般的なSLAへの準拠を保証する単一データセットのバックアップ戦略の構築は非常に簡単です。データセットの数が増えるにつれて監視が複雑になり、バックアップの失敗に対処するために、管理者がますます多くの時間を費やすことになる可能性があります。環境がクラウドに到達し、サービスプロバイダが拡張するにつれて、まったく異なるアプローチが必要になります。

データセットのサイズも戦略に影響します。たとえば、データセットが非常に小さいため、100GBのデータベースのバックアップとリカバリには多くのオプションがあります。従来のツールを使用してバックアップメディアからデータをコピーするだけで、リカバリに十分なRTOが得られます。通常、100TBのデータベースでは、RTOによって複数日の停止が許容される場合を除き、まったく異なる戦略が必要になります。その場合は、従来のコピーベースのバックアップおよびリカバリの手順で十分かもしれません。

最後に、バックアップとリカバリのプロセス自体以外にもさまざまな要因があります。たとえば、重要な本番環境のアクティビティをサポートしているデータベースがあり、熟練したDBAだけがリカバリを実行するまれなイベントになっているとしますか。あるいは、データベースは、リカバリが頻繁に発生し、ジェネラリストのITチームが管理する大規模な開発環境に含まれていますか。



== Snapshotはバックアップですか？

データ保護戦略としてSnapshotを使用することに対する一般的な反対意見の1つは、「実際の」データとSnapshotデータが同じドライブに配置されていることです。これらのドライブが失われると、プライマリデータとバックアップの両方が失われます。

これは有効な問題です。ローカルSnapshotは、日 々 のバックアップとリカバリのニーズに使用され、その点でSnapshotはバックアップです。NetApp環境のすべてのリカバリシナリオの99%近くが、最も厳しいRTO要件を満たすためにSnapshotを使用しています。

ただし、ローカルSnapshotが唯一のバックアップ戦略であるべきではありません。そのため、NetAppでは、SnapMirrorレプリケーションなどのテクノロジを使用して、独立したドライブセットにSnapshotを迅速かつ効率的にレプリケートできます。スナップショットとスナップショットレプリケーションを使用して適切に設計された解決策では、テープの使用を最小限に抑えて四半期ごとのアーカイブを作成することも、完全に排除することもできます。



== crash-consistentバックアップ

crash-consistentバックアップでは、単一のアトミックなポイントインタイムでデータセット（または複数のデータセット）の状態をキャプチャします。データベースを例にとると、データファイル、ログ ファイル、およびデータベースに直接関連するその他のファイルなど、すべてのデータベース コンポーネントが含まれます。これは、Oracle RDBMS、Microsoft SQL Server、SAP HANA、PostgreSQL、MySQL、MariaDBなど、ほぼすべてのリレーショナル データベース製品で機能します。整合性グループ バックアップを使用してVMware構成を保護する場合も同様で、すべてのデータストアと場合によってはESXブートLUNを単一のアトミックなポイントインタイムでキャプチャします。

このようなバックアップの作成は、本質的にクラッシュをシミュレートすることであり、そのためこのようなバックアップはcrash-consistentバックアップと呼ばれます。復旧シナリオへの対応に関して懸念が生じる場合もありますが、通常は復旧手順は必要ないことを理解しておくことが重要です。整合性グループのバックアップを復元した後、アプリケーションが起動すると、通常のログ回復プロセス、ファイルシステムジャーナルの再生、およびその他のタスクを実行して、バックアップ時点で実行中だったすべてのI/Oを再生します。その後、アプリケーションは通常どおり起動します。

基本的に、データの破損なしに電源障害やサーバクラッシュに耐えることができるアプリケーションは、この方法で保護できます。この機能は、さまざまなベンダーの同期および非同期ミラーリング製品で保護されている膨大な数のアプリケーションによっても実証できます。プライマリサイトで突然災害が発生した場合、レプリカサイトには、災害が発生した時点の元の環境の整合性のあるイメージが格納されます。繰り返しになりますが、特別なリカバリ手順は必要ありません。

このアプローチにおけるRPO（目標復旧時点）は、通常、バックアップ時点に限定されます。一般的に、crash-consistentバックアップの最小RPOは1時間です。たとえば、48時間ごとのスナップショットに加えて、さらに30日間の夜間スナップショットを保持することは妥当であり、過剰な数のスナップショットを保持する必要は生じません。RPOを1時間未満に抑えることはより困難になり、事前にNetApp Professional Servicesに相談して環境、規模、データ保護要件を理解することなく実行することは推奨されません。

RTO（復旧時間）は通常、秒単位で測定されます。アプリケーションがシャットダウンされると、NFSボリューム、LUN、またはNVMeネームスペースが復元され、アプリケーションが再起動されます。

最も簡単な方法は、すべてのファイルまたはLUNを単一のAFFボリュームまたはASA LUN/名前空間に配置することです。データセットが複数のストレージリソースにまたがる必要がある場合、整合性グループが必要となります。これはSystem ManagerまたはRESTful API呼び出しを使用して構成できます。また、SnapCenterはシンプルな整合性グループのSnapshotを作成できます。



== レプリケーションとディザスタリカバリのアーキテクチャ

ここでは、セキュアなオフサイトストレージとディザスタリカバリを目的として、データをリモートサイトにレプリケートするリモートデータ保護について説明します。これらのテーブルは、同期ミラーリングのデータ保護には対応していません。この要件については、およびを含むNetApp MetroClusterのドキュメントを参照してください。link:oracle-dr-mcc-failover.html["MetroCluster"]link:oracle-dr-smas-overview.html["SnapMirrorアクティブ同期"]

DRのRPOは、使用可能なネットワーク帯域幅と保護対象のデータの合計サイズによって制限されます。初回のベースライン転送の作成後は、変更されたデータのみに基づいて更新が行われます。これは通常、例外もありますが、総データ容量に占める割合は低くなります。

たとえば、週単位の変更率が10%の10TBデータベースでは、1時間あたりの合計変更量は約6GBです。10Gbの接続では、このデータベースの転送に約6分かかります。変更率はデータベースの変更率の変動に応じて変化しますが、全体的には更新間隔が15分であるため、RPOが15分になるはずです。このようなデータベースが100個ある場合、データの転送に600分かかります。したがって、RPOを1時間にすることはできません。同様に、100TBの単一データベースのレプリカのサイズが週に10%の変更率であれば、1時間で確実に更新することはできません。

レプリケーションには、レプリケーションのオーバーヘッドや同時実行レプリケーション操作数の制限など、その他の要因も影響を与える可能性があります。しかし、単一リソースのレプリケーション戦略の全体的な計画は、利用可能な帯域幅に基づいて行うことができ、1時間のレプリケーションRPOは一般的に達成可能です。RPOを1時間未満に抑えることはより困難になり、NetAppプロフェッショナル サービスに相談した後にのみ実施すべきです。非常に良好な拠点間ネットワーク接続環境であれば、場合によっては15分で完了することも可能です。しかし、全体的に見て、1時間未満のRPOが求められる場合、マルチリソースログ再生アーキテクチャの方がより良い結果が得られます。

ディザスタリカバリシナリオにおける整合グループレプリケーションを使用したRTOは非常に優れており、ストレージの観点から見れば、通常は数秒で測定されます。最も簡単な方法は、単にミラーを解除することであり、データベースを起動する準備ができています。通常、データベースの起動時間は約10秒ですが、大量のトランザクションがログに記録された非常に大規模なデータベースには数分かかることがあります。

RTOを決定するうえで最も重要な要素は、ストレージシステムではなく、ストレージシステムを実行するアプリケーションとホストオペレーティングシステムです。たとえば、レプリケートされたデータを1秒または2秒で使用できるようにすることができますが、これはデータのみを表します。また、データを使用できるアプリケーションバイナリを備えた、適切に構成されたオペレーティングシステムも必要です。

場合によっては、オペレーティングシステムで事前に検出されたストレージを使用して、ディザスタリカバリのインスタンスを事前に準備していることもあります。このような場合、ディザスタリカバリシナリオをアクティブ化するには、ミラーを解除してアプリケーションを起動するだけです。また、OSと関連するアプリケーションをデータベースとともにESX Virtual Machine Disk（VMDK；仮想マシンディスク）としてミラーリングする場合もあります。このような場合のRPOは、お客様がVMDKを迅速にブートしてアプリケーションを起動できるように自動化にどれだけ投資したかによって決まります。

保持時間は、Snapshot制限によって部分的に制御されます。たとえば、ONTAPのAFFボリュームとASA LUNには、1024個のSnapshotという制限があります。場合によっては、お客様は多重化レプリケーションを使用して制限を引き上げています。たとえば、2000日分のバックアップが必要な場合、ソースを2つの異なるデスティネーションにレプリケートし、更新を隔日で実行することができます。これには初期に必要なスペースの増加が必要となりますが、複数のフル バックアップを必要とする従来型のバックアップ システムよりもはるかに効率的なアプローチです。



=== 単一ボリューム整合性グループ（AFF）

最も簡単な方法は、すべてのファイルまたはLUNを単一のボリュームに配置することです。ボリュームはそれ自体が一貫性グループであり、つまりSnapMirrorおよびSnapVaultの更新はストレージ システム上で直接スケジュール設定できます。外部ソフトウェアは不要です。



=== 単一LUN/ネームスペース整合性グループ（ASA）

データベース全体を単一のLUN/ネームスペースに配置するのは奇妙に思えるかもしれないが、実際にはますます一般的になりつつある。ボリューム マネージャが最初に開発された理由は、物理ドライブの性能と容量の限界を克服するためだった。最新のアレイでは、ホストに提示される単一のブロックデバイスは、すでに複数のドライブにまたがって抽象化されている。サイズは動的に調整可能で、性能は単体ドライブよりもはるかに優れている。

その結果、ESXデータストアからOracleデータベースまで、さまざまなワークロードを単一のブロックデバイス上でホストできる場合が多くなった。これはデータ管理を大幅に簡素化するだけでなく、検出する必要のあるデバイスの数が減るため、ホストの再起動時間が短縮されるなど、有益な副次的効果ももたらします。



=== マルチボリューム整合グループ

データベースが複数のAFFボリュームまたはASA LUN/ネームスペースにまたがる必要がある場合、整合性グループのSnapshotが必要です。上記のように、これはSystem ManagerまたはRESTful API呼び出しを使用して設定できます。また、SnapCenterは、シンプルな整合性グループのSnapshotを作成できます。

また、ディザスタリカバリを目的としたAFF複数ボリュームまたはASA複数LUNにわたる整合性のあるスナップショットの使用に関して、考慮すべき点がもう1つあります。複数のSnapMirror関係の更新を実行する際、転送処理が進行中に障害が発生する可能性があります。その結果、互いに整合性のないボリューム、LUN、またはネームスペースのセットが生成されてしまいます。この場合、「crash consistent state（障害など予期しないシャットダウン時と同様）」の状態で使用可能なデータベース イメージを提供するために、一部のボリュームを以前のスナップショットの状態に復元する必要があります。



== ディザスタリカバリ:アクティブ化



=== NFS

ディザスタリカバリコピーをアクティブ化するプロセスは、ストレージのタイプによって異なります。NFSでは、ファイルシステムをディザスタリカバリサーバに事前にマウントできます。これらは読み取り専用状態であり、ミラーが解除されると読み取り/書き込みになります。これにより、RPOが非常に低くなり、管理するパーツが少ないため、ディザスタリカバリプロセス全体の信頼性が向上します。



=== SAN

ディザスタリカバリ時にSAN構成をアクティブ化することは、より複雑になります。最も簡単なオプションは、通常、ミラーを一時的に解除してSANリソースをマウントすることです。たとえば、LVM構成（Oracle Automatic Storage Management[ASM]などのアプリケーション固有の機能を含む）を検出したり、/etc/fstabにエントリを追加したりします。

その結果、LUNデバイスパス、ボリュームグループ名、およびその他のデバイスパスがターゲットサーバに認識されます。その後、これらのリソースをシャットダウンし、その後ミラーをリストアできます。その結果、サーバはアプリケーションを迅速にオンラインにできる状態になります。ボリュームグループのアクティブ化、ファイルシステムのマウント、データベースとアプリケーションの起動の手順は簡単に自動化できます。

ディザスタリカバリ環境が最新の状態であることを確認する必要があります。たとえば、新しいLUNがソースサーバに追加されることが多いため、ディザスタリカバリプランが想定どおりに機能するように、デスティネーションで新しいLUNを事前に検出しておく必要があります。
