---
sidebar: sidebar 
permalink: oracle/oracle-dr-smas-overview.html 
keywords: Oracle,SM-as,active sync 
summary: OracleとSnapMirrorのアクティブな同期 
searchtitle: OracleとSnapMirrorのアクティブ同期の概要 
---
= 概要
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
SnapMirror Active Syncを使用すると、非常に高可用性のOracleデータベース環境を構築できます。この環境では、2つの異なるストレージクラスタからLUNを使用できます。

SnapMirrorのアクティブな同期では、データの「プライマリ」コピーと「セカンダリ」コピーはありません。各クラスタはデータのローカルコピーから読み取りIOを提供でき、各クラスタはパートナーに書き込みをレプリケートします。その結果、対称IOビヘイビアが作成されます。

これにより、Oracle RACを両方のサイトで運用インスタンスを持つ拡張クラスタとして実行できます。または、RPO=0のアクティブ/パッシブデータベースクラスタを構築して、サイト停止中にシングルインスタンスデータベースをサイト間で移動できます。このプロセスは、PacemakerやVMware HAなどの製品を使用して自動化できます。これらすべてのオプションの基盤となるのは、SnapMirror Active Syncで管理される同期レプリケーションです。



== 同期レプリケーション

通常の運用では、1つの例外を除いて、SnapMirrorアクティブ同期は常にRPO=0同期レプリカを提供します。データをレプリケートできない場合、ONTAPでは、データのレプリケートという要件が解除され、一方のサイトのLUNがオフラインになる間に、一方のサイトでIOの提供が再開されます。



== ストレージハードウェア

他のストレージディザスタリカバリソリューションとは異なり、SnapMirrorアクティブ同期は非対称プラットフォームの柔軟性を提供します。各サイトのハードウェアが同一である必要はありません。この機能を使用すると、SnapMirrorアクティブ同期をサポートするために使用するハードウェアのサイズを適正化できます。リモートストレージシステムは、本番環境のワークロードを完全にサポートする必要がある場合はプライマリサイトと同一にすることができますが、災害によってI/Oが減少した場合は、リモートサイトの小規模システムよりも対費用効果が高くなります。



== ONTAPメディエーター

ONTAPメディエーターは、NetAppサポートからダウンロードするソフトウェアアプリケーションで、通常は小規模な仮想マシンに導入されます。ONTAPメディエーターは、SnapMirrorのアクティブな同期ではTiebreakerになりません。これは、SnapMirrorのアクティブな同期レプリケーションに含まれる2つのクラスタの代替通信チャネルです。自動処理は、パートナーから直接接続またはメディエーター経由で受け取った応答に基づいてONTAPによって実行されます。
