= AFF SSDアグリゲートとASA Storage Availability Zones
:allow-uri-read: 


空き領域とは、実際のデータに使用されていない領域を指し、アグリゲート自体の未割り当て領域と、構成ボリューム内の未使用領域が含まれます。シンプロビジョニングも検討する必要があります。たとえば、AFF ボリュームには1TBのLUNが含まれている可能性があり、そのうち実際のデータによって使用されているのは50%のみです。シンプロビジョニング環境では、これは正しく500GBの容量を消費しているように見えます。しかし、完全にプロビジョニングされた環境では、1TBの全容量が使用されているように見えます。割り当てられていない500GBの領域は非表示になっています。この領域は実際のデータには使用されていないため、総空き容量の計算に含める必要があります。

エンタープライズアプリケーションに使用するストレージシステムに関するNetAppの推奨事項は次のとおりです。



== AFF SSDアグリゲートとASA Storage Availability Zones


TIP: * NetAppでは*最低10%の空き容量を推奨しています。これには、アグリゲートまたはボリューム内の空きスペース、フルプロビジョニングのために割り当てられているが実際のデータには使用されていない空きスペースなど、すべての未使用スペースが含まれます。論理スペースは重要ではありません。問題は、データストレージに実際に使用できる物理的な空きスペースの量です。

推奨される10%の空きスペースは非常に控えめな値です。SSDアグリゲートでは、パフォーマンスに影響を与えることなく、さらに高い利用率でワークロードをサポートできます。ただし、アグリゲートの使用率が高くなると、使用率を注意深く監視しないと、スペースが不足するリスクも高まります。さらに、容量99%でシステムを実行している場合はパフォーマンスが低下することはありませんが、ハードウェアの追加発注時にシステムが完全にいっぱいにならないように管理作業が必要になる可能性があり、追加のドライブの調達と取り付けに時間がかかることがあります。



== HDDアグリゲート（Flash Poolアグリゲートを含む）


TIP: * NetAppでは*回転式ドライブを使用する場合は、最低15%の空き容量を確保することを推奨しています。これには、アグリゲートまたはボリューム内の空きスペース、フルプロビジョニングのために割り当てられているが実際のデータには使用されていない空きスペースなど、すべての未使用スペースが含まれます。空きスペースが10%に近づくとパフォーマンスが低下します。
