= ファイバーチャネル
:allow-uri-read: 




[[fiber-channel]]
=== ファイバーチャネル

ONTAP 9.19.1 以降、従来型の FC-SAN（SCSI）と一部のストレージシステム FC アダプタを使用した NVMe/FC の両方で、ダイレクト接続 FC がサポートされています。HBA は標準的なポイントツーポイント FC 接続を確立します。ONTAP 9.19.1 より前のバージョンでは、ONTAP ストレージシステムには NPIV が必要です。つまり、ストレージシステムは NPIV をサポートする FC スイッチに接続されている必要があります。



[[iscsi-and-nvmetcp]]
=== iSCSIとNVMe/TCP

iSCSIまたはNVMe/TCPを使用するホストは、ストレージシステムに直接接続して正常に動作することができます。その理由はパス設定です。2つの異なるストレージコントローラに直接接続すると、データフローが2つの独立したパスになります。パス、ポート、またはコントローラが失われても、他のパスの使用が妨げられることはありません。



[[nfs]]
=== NFS

直接接続されたNFSストレージも使用できますが、フェイルオーバーには大きな制限があります。スクリプト作成にはお客様の責任が伴います。

直接接続されたNFSストレージで無停止フェイルオーバーが複雑になるのは、ローカルOSで発生するルーティングが原因です。たとえば、ホストのIPアドレスが192.168.1.1/24で、IPアドレスが192.168.1.50/24のONTAPコントローラに直接接続されているとします。フェールオーバー中、192.168.1.50アドレスはもう一方のコントローラにフェールオーバーでき、ホストが使用できるようになりますが、ホストはそのアドレスの存在をどのように検出しますか。元の192.168.1.1アドレスは、動作中のシステムに接続されていないホストNICに残っています。192.168.1.50宛てのトラフィックは、動作不能なネットワークポートに引き続き送信されます。

2 番目の OS NIC は 192.168.1.2 として構成でき、フェイルオーバーした 192.168.1.50 アドレスと通信できますが、ローカル ルーティング テーブルはデフォルトで 1 つのアドレス*のみ*を使用して 192.168.1.0/24 サブネットと通信します。システム管理者は、ネットワーク接続の障害を検出し、ローカル ルーティング テーブルを変更したり、インターフェースを起動／停止したりするスクリプト フレームワークを作成できます。具体的な手順は、使用している OS によって異なります。

実際にはNetAppを使用していますが、通常はフェイルオーバー中のIO一時停止が許容されるワークロードのみが対象です。ハードマウントを使用する場合は、一時停止中にIOエラーが発生しないようにしてください。ホスト上のNIC間でIPアドレスを移動するためのフェイルバックまたは手動操作によって、サービスが復元されるまでIOはハングします。
