= スペース管理
:allow-uri-read: 


シンプロビジョニングにはさまざまな形式があり、ONTAPがエンタープライズアプリケーション環境に提供する多くの機能に欠かせない機能です。シンプロビジョニングも効率化テクノロジと密接に関連しています。効率化機能を使用すると、ストレージシステムに実際に存在するよりも多くの論理データを格納できます。

Snapshotを使用する場合、シンプロビジョニングが必要になります。たとえば、NetAppストレージ上の一般的な10TBのデータベースには、約30日間のSnapshotが含まれています。この構成では、アクティブファイルシステムに表示されるデータは約10TB、Snapshot専用のデータは300TBになります。合計310TBのストレージは、通常、約12~15TBのスペースに配置されます。アクティブデータベースは10TBを消費しますが、残りの300TBのデータは元のデータに加えられた変更のみが格納されるため、2TB~5TBのスペースしか必要としません。

クローニングもシンプロビジョニングの一例です。NetAppの主要なお客様が、80TBのデータベースのクローンを40個作成し、開発用に使用しました。これらのクローンを使用している40人の開発者全員がすべてのデータファイルのすべてのブロックを上書きした場合、3.2PBを超えるストレージが必要になります。実際には書き替え率は低く、変更のみがドライブに格納されるため、必要なスペースは合計で40TBに近くなります。



== スペース管理

データの変更率が予期せず増加する可能性があるため、アプリケーション環境のシンプロビジョニングには注意が必要です。たとえば、データベーステーブルのインデックスを再作成したり、VMwareゲストに大規模なパッチを適用したりすると、Snapshotによるスペース消費が急増します。バックアップの配置が間違っていると、非常に短時間で大量のデータが書き込まれる可能性があります。最後に、ファイルシステムの空きスペースが予期せず不足した場合、一部のアプリケーションのリカバリが困難になることがあります。

幸いなことに、これらのリスクは慎重に構成することで対処できます。 `volume-autogrow` および `snapshot-autodelete` ポリシー：名前からわかるように、これらのオプションを使用すると、Snapshotによって消費されるスペースを自動的にクリアしたり、追加データに対応するためにボリュームを拡張したりするポリシーを作成できます。多くのオプションが用意されており、ニーズはお客様によって異なります。

を参照してください link:https://docs.netapp.com/us-en/ontap/volumes/index.html["論理ストレージ管理に関する文書"] を参照してください。



== フラクショナルリザベーション

フラクショナルリザーブは、ボリューム内でのスペース効率に関するLUNの動作です。オプション `fractional-reserve` が100%に設定されている場合、ボリュームのスペースを使い切ることなく、任意のデータパターンでボリューム内のすべてのデータを100%書き替えることができます。

たとえば、AFFシステムの1TBボリューム内の単一の250GB LUN上のデータベースについて考えてみます。Snapshotを作成すると、ボリューム内に250GBの追加スペースが即座に予約され、いかなる理由であれボリュームのスペースが不足しないことが保証されます。fractional reserveの使用は一般的に無駄です。データベース ボリューム内のすべてのバイトを上書きする必要が生じる可能性は極めて低いためです。決して発生しないイベントのためにスペースを予約する理由はありません。ただし、お客様がストレージ システムのスペース消費量を監視できず、スペースが不足しないことを確実にする必要がある場合は、Snapshotを使用するために100% fractional reserveが必要になります。


TIP: ボリューム抽象化はSAN専用のASAには存在しないため、このプラットフォームでは部分リザーブを使用しません。



== 圧縮と重複排除

圧縮と重複排除はどちらもシンプロビジョニングの形式です。たとえば、50TBのデータ容量を30TBに圧縮すると、20TBが削減されます。圧縮によってメリットが得られるようにするには、20TBの一部を他のデータに使用するか、50TB未満のストレージシステムを購入する必要があります。その結果、ストレージシステムで実際に使用可能な量よりも多くのデータが格納されます。データの観点から見ると、ドライブでは30TBしか占有していないにもかかわらず、50TBのデータがあります。

データセットの圧縮率が変化する可能性は常にあり、その結果、実際のストレージ容量の消費量が増加する可能性がある。この消費量の増加は、他のシンプロビジョニングと同様に、監視の観点から圧縮を管理する必要があることを意味し、AFFシステムでは `volume-autogrow`および `snapshot-autodelete`を使用する。

圧縮機能と重複排除機能の詳細については、efficiency.htmlのリンクを参照してください。



=== 圧縮とフラクショナルリザベーション

圧縮はシンプロビジョニングの一形態です。フラクショナルリザベーションは圧縮の使用に影響します。スペースはSnapshotの作成前にリザーブされる点に注意してください。通常、フラクショナルリザーブが重要になるのはSnapshotが存在する場合のみです。Snapshotがない場合、フラクショナルリザーブは重要ではありません。これは、圧縮の場合には当てはまりません。圧縮が有効なボリュームでLUNを作成すると、ONTAPではSnapshotに対応するためのスペースが確保されます。この動作は設定時に混乱を招く可能性がありますが、これは想定される動作です。

たとえば、10GBのボリュームに5GBのLUNが格納され、2.5GBに圧縮されてSnapshotが作成されていないとします。次の2つのシナリオを検討します。

* フラクショナルリザーブ= 100では7.5GBが使用されます。
* フラクショナルリザーブ= 0の場合、2.5GBの使用率が得られます。


最初のシナリオでは、現在のデータ用に2.5GBのスペースが使用され、スナップショットの使用を想定してソースの100%の切り替えに使用される5GBのスペースが使用されます。2番目のシナリオでは、追加のスペースは確保されません。

この状況は混乱しているように見えるかもしれませんが、実際に遭遇することはほとんどありません。圧縮はシンプロビジョニングを意味し、LUN環境でのシンプロビジョニングにはフラクショナルリザベーションが必要です。圧縮されたデータは圧縮不可能なデータで上書きされる可能性があります。つまり、圧縮によって削減効果が得られるように、ボリュームをシンプロビジョニングする必要があります。

[TIP]
====
*NetAppでは、*AFFおよびFASプラットフォームで次のリザーブ構成を推奨します：

* 設定 `fractional-reserve` 基本的な容量監視と `volume-autogrow` および `snapshot-autodelete`。
* 設定 `fractional-reserve` 監視機能がない場合、または何らかの状況でスペースを使い切ることができない場合は、100にします。


====