= デフォルト
:allow-uri-read: 




== デフォルト

すべてのFabricPoolボリュームの初期設定は `default`これは、動作が「cloud-retrieval-policy」によって制御されることを意味します。'正確な動作は、使用する階層化ポリシーによって異なります。

* `auto`-ランダムリードデータのみを取得
* `snapshot-only`-すべてのシーケンシャルまたはランダムリードデータを取得
* `none`-すべてのシーケンシャルまたはランダムリードデータを取得
* `all`-大容量階層からデータを取得しない




== オンリード

設定 `cloud-retrieval-policy` をオンリードに設定するとデフォルトの動作が無効になるため、階層化されたデータが読み取られた場合、そのデータはパフォーマンス階層に返されます。

たとえば、ボリュームは、 `auto` 階層化ポリシーとほとんどのブロックが階層化されます。

ビジネスニーズの予期しない変化によって、特定のレポートを作成するために一部のデータを繰り返しスキャンする必要がある場合は、 `cloud-retrieval-policy` 終了： `on-read` シーケンシャルデータとランダムリードデータの両方を含む、読み取りされるすべてのデータがパフォーマンス階層に返されます。これにより、ボリュームに対するシーケンシャルI/Oのパフォーマンスが向上します。



== プロモート

昇格ポリシーの動作は階層化ポリシーによって異なります。階層化ポリシーがの場合 `auto`をクリックし、 `cloud-retrieval-policy `to `promote` 次回の階層化スキャンで大容量階層のすべてのブロックを戻します。

階層化ポリシーがの場合 `snapshot-only`を指定すると、アクティブファイルシステムに関連付けられているブロックのみが返されます。通常、これは効果がありません。これは、 `snapshot-only` ポリシーは、Snapshotにのみ関連付けられたブロックになります。アクティブファイルシステムに階層化されたブロックはありません。

ただし、ボリュームSnapRestoreまたはSnapshotからのファイルクローン操作によってボリューム上のデータがリストアされた場合、Snapshotにのみ関連付けられていたために階層化されたブロックの一部がアクティブファイルシステムで必要になることがあります。一時的に `cloud-retrieval-policy` ポリシーの宛先 `promote` ローカルで必要なすべてのブロックを迅速に取得できます。



== なし

大容量階層からブロックを取得しないでください。
