---
sidebar: sidebar 
permalink: mssql/mssql-ag-snapcenter.html 
keywords: MSSQL,SQL Server, data protection, snapmirror, availability group 
summary: SnapCenterを使用したMicrosoft SQL Server可用性グループ 
searchtitle: SnapCenterを使用したMicrosoft SQL Server可用性グループ 
---
= SnapCenterを使用したSQL Server可用性グループ
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
SnapCenterでは、Windowsフェイルオーバークラスタで構成されたSQL Server可用性グループデータベースのバックアップがサポートされます。

SnapCenter Plugin for Microsoft SQL Serverは、Windowsサーバフェイルオーバークラスタのすべてのノードにインストールする必要があります。SnapCenterプラグインをセットアップするための前提条件と手順を参照してくださいlink:https://docs.netapp.com/us-en/snapcenter/protect-scsql/concept_prerequisites_for_using_snapcenter_plug_in_for_microsoft_sql_server.html["ドキュメント"]。

SnapCenterでは、Windowsホスト内のすべてのデータベース、インスタンス、および可用性グループが検出され、SnapCenterのリソースページにリソースが列挙されます。



=== Always-On可用性グループのデータベースの保護

可用性グループ内のデータベースは、複数の方法で保護できます。

* データベースレベルのバックアップ：データベースリソースページの可用性データベースを選択し、フル/ログバックアップを含むポリシーを追加し、バックアップをスケジュールします。SnapCenterは、プライマリレプリカであるかセカンダリレプリカであるかに関係なく、データベースのロールに関係なくバックアップを実行します。リソースグループにデータベースを追加して保護を設定することもできます。
* インスタンスレベルのバックアップ：インスタンスを選択すると、選択したポリシーに基づいてインスタンスで実行されているすべてのデータベースが保護されます。プライマリレプリカまたはセカンダリレプリカとして実行されている可用性データベースを含め、すべてのデータベースがSnapCenterを使用してバックアップされます。リソースグループにインスタンスを追加して保護を設定することもできます。
* 可用性グループレベルのバックアップ：ポリシーの設定時に、SnapCenterには可用性グループレベルのバックアップの詳細オプションがあります。ポリシーの可用性グループ設定を使用すると、バックアップのレプリカ設定を選択できます。プライマリレプリカ、セカンダリレプリカ、またはそれらのすべてを選択できます。デフォルトのオプションは、SQL Server可用性グループ構成のバックアップレプリカセットに基づいています。


SnapCenterポリシーの可用性グループ設定は、可用性グループレベルのバックアップが可用性グループデータベースの保護に使用されている場合にのみ適用され、データベースレベルまたはインスタンスレベルのバックアップには適用されません。


TIP: * NetAppでは、可用性レベルのバックアップを使用して、NetApp ONTAPストレージで実行されているすべてのレプリカをバックアップすることを推奨しています。



=== SnapCenterでのログバックアップの設定

可用性グループをスタンドアロンSQL Serverセットアップでセットアップする場合は、Windowsサーバフェイルオーバークラスタの各ノードに専用ディスクをマウントする必要があります。トランザクションログバックアップを保存するログディレクトリを設定するには、専用ディスクを使用する必要があります。

SQL Serverフェイルオーバークラスタで可用性グループが設定されている場合は、SQL Serverフェイルオーバークラスタインスタンス上にホストログディレクトリへのクラスタディスクを作成する必要があります。



=== SnapCenterを使用した可用性グループセットアップでのデータベースのリストア

* SnapCenterには再シードオプションがあり、セカンダリレプリカにある最新のSnapshotからデータベースを自動的にリカバリできます。再シード処理を実行すると、データベースバックアップが自動的にリストアされて可用性グループに追加されます。
* 可用性グループ内のレプリカデータベースをリストアするもう1つの方法は、可用性グループを解除し、完全なフルリストアとログリストアを実行することです。SnapCenterを使用してデータベースをノーリカバリモードでリストアし、SQL Server Management StudioまたはT-SQLを使用してデータベースを可用性グループに戻します。
* データのサブセットだけをリカバリするには、SnapCenterのクローニング機能を使用してデータベースのクローンコピーを作成します。データベースのコピーは、SnapCenterを使用して数分以内に作成され、SQL Serverのネイティブツールを使用してプライマリレプリカにデータをエクスポートします。


RTOとRPOの要件を満たすようにデータベースストレージレイアウトを設定するためのベストプラクティスについては、を参照してくださいlink:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714：NetApp SnapCenterを使用したMicrosoft SQL Serverのベストプラクティス"]。


NOTE: SnapCenterでは、分散可用性グループと含まれる可用性グループはサポートされません。
