---
sidebar: sidebar 
permalink: mssql/mssql-storage-considerations-ASA.html 
keywords: MSSQL,SQL Server, volumes, LUN, SnapCenter 
summary: ASAシステムでのMicrosoft SQL Serverストレージに関する考慮事項 
searchtitle: Microsoft SQL Serverストレージに関する考慮事項 
---
= 概要
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
NetApp ASA R2は、ミッションクリティカルなワークロードを実行するSANのみのお客様向けの、シンプルで強力なソリューションです。ONTAPストレージソリューションを実行するASA R2プラットフォームとMicrosoft SQL Serverを組み合わせることで、今日の最も要求の厳しいアプリケーション要件を満たすエンタープライズレベルのデータベースストレージ設計が可能になります。

次のASAプラットフォームは、すべてのSANプロトコル（iSCSI、FC、NVMe/FC、NVMe/TCP）をサポートするASA R2システムに分類されます。iSCSI、FC、NVMe/FC、NVMe/TCPの各プロトコルでは、対称アクティブ/アクティブアーキテクチャのマルチパスがサポートされているため、ホストとストレージの間のすべてのパスがアクティブ/最適化されます。

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20


詳細については、を参照してください。 link:https://docs.netapp.com/us-en/asa-r2/index.html["NetApp ASA"]

SQL Server on ONTAPソリューションを最適化するには、SQL ServerのI/Oパターンと特性を理解する必要があります。SQL Serverデータベース用のストレージレイアウトを適切に設計するには、SQL Serverのパフォーマンス要件を満たしながら、インフラ全体の管理性を最大限に高める必要があります。また、ストレージレイアウトを適切に配置すれば、初期導入を成功させ、ビジネスの成長に合わせて環境をスムーズに拡張できます。



== データストレージ設計

Microsoftでは、データファイルとログファイルを別 々 のドライブに配置することを推奨しています。データを同時に更新して要求するアプリケーションでは、ログファイルに書き込み負荷がかかり、（アプリケーションによっては）データファイルの読み取り/書き込み負荷が高くなります。データを取得する場合、ログファイルは必要ありません。そのため、データの要求は、そのドライブに配置されたデータファイルから満たすことができます。

新しいデータベースを作成するときは、データとログ用に別 々 のドライブを指定することを推奨します。データベース作成後にファイルを移動するには、データベースをオフラインにする必要があります。Microsoftのその他の推奨事項については、 link:https://docs.microsoft.com/en-us/sql/relational-databases/policy-based-management/place-data-and-log-files-on-separate-drives?view=sql-server-ver15["データファイルとログファイルを別 々 のドライブに配置"^]。



=== ストレージユニットに関する考慮事項

ASAのストレージユニットとは、SCSI / FCホストの場合はLUN、NVMeホストの場合はNVMeネームスペースを指します。サポートされるプロトコルに基づいて、LUN、NVMeネームスペース、またはその両方を作成するように求められます。データベース導入用のストレージユニットを作成する前に、SQL ServerのI/Oパターンと特性がワークロードやバックアップとリカバリの要件に応じてどのように変わるかを理解しておくことが重要です。ストレージユニットに関する次のNetAppの推奨事項を参照してください。

* 管理の複雑さを避けるため、同じホスト上で実行される複数のSQL Server間で同じストレージユニットを共有しないでください。同じホストで複数のSQL Serverインスタンスを実行する場合は、ノードのストレージユニット数の上限に近い場合を除き、共有は避け、データ管理を容易にするために、ホストごとにインスタンスごとにストレージユニットを個別に配置してください。
* ドライブレターではなくNTFSマウントポイントを使用して、Windowsのドライブレターの制限（26文字）を超えます。
* Snapshotスケジュールと保持ポリシーを無効にします。代わりに、SnapCenterを使用して、SQL ServerデータストレージユニットのSnapshotコピーを調整します。
* SQL Serverシステムデータベースは専用のストレージユニットに配置します。
* tempdbは、特にI/O負荷の高いDBCC CHECKDB処理のために、SQL Serverが一時的なワークスペースとして使用するシステムデータベースです。したがって、このデータベースは専用のストレージユニットに配置します。ストレージユニットの数が課題となる大規模な環境では、慎重に計画したあとに、tempdbとシステムデータベースを同じストレージユニットに統合できます。tempdbのデータ保護は、SQL Serverを再起動するたびにこのデータベースが再作成されるため、優先度の高いものではありません。
* (`.mdf`ランダムな読み取り/書き込みワークロードであるため、ユーザデータファイルを別のストレージユニットに配置します。トランザクションログバックアップは、データベースバックアップよりも頻繁に作成するのが一般的です。このため、トランザクションログファイル(`.ldf`）をデータファイルとは別のストレージユニットまたはVMDKに配置し、それぞれに個別のバックアップスケジュールを作成できるようにします。また、この分離により、ログファイルのシーケンシャルライトI/Oとデータファイルのランダムリード/ライトI/Oが分離され、SQL Serverのパフォーマンスが大幅に向上します。
* ユーザデータベースファイルとログバックアップを格納するログディレクトリは、バックアップポリシーのSnapMirror機能でSnapshotが保持ポリシーによって上書きされないように、別 々 のストレージユニットに配置してください。
* データベースファイルとデータベース以外のファイル（フルテキスト検索関連ファイルなど）を同じストレージユニットに混在させないでください。
* データベースのセカンダリファイルを（ファイルグループの一部として）別のストレージユニットに配置すると、SQL Serverデータベースのパフォーマンスが向上します。この分離は、データベースのファイルがそのストレージユニットを他のファイルと共有していない `.mdf`場合にのみ有効 `.mdf`です。
* Windowsサーバのディスクマネージャを使用してディスクをフォーマットするときは、パーティションの割り当て単位サイズが64Kに設定されていることを確認してください。
* マウントポイントをホストするストレージユニットにユーザデータベースまたはシステムデータベースを配置しないでください。
* を参照してください link:https://www.netapp.com/media/10680-tr4080.pdf["最新SANに対するONTAPのベストプラクティスに基づくMicrosoft WindowsとネイティブMPIO"] WindowsのマルチパスサポートをMPIOプロパティのiSCSIデバイスに適用するには、次の手順を実行します。
* Always Onフェイルオーバークラスタインスタンスを使用している場合は、Windowsサーバフェイルオーバークラスタノード間で共有されるストレージユニットにユーザデータベースを配置する必要があります。また、物理ディスククラスタリソースは、SQL Serverインスタンスに関連付けられたクラスタグループに割り当てられます。

