---
sidebar: sidebar 
permalink: mssql/mssql-log-directory.html 
keywords: MSSQL,SQL Server, volumes, LUN, SnapCenter 
summary: Microsoft SQL Serverログディレクトリ 
---
= Microsoft SQL Serverログディレクトリ
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
ログディレクトリは、トランザクションログバックアップデータをホストレベルで格納するためにSQL Serverで指定します。SnapCenterを使用してログファイルをバックアップする場合は、SnapCenterで使用される各SQL Serverホストに、ログバックアップを実行するようにホストログディレクトリを設定する必要があります。SnapCenter にはデータベースリポジトリがあるため、バックアップ、リストア、クローニングの処理に関連するメタデータは中央のデータベースリポジトリに格納されます。

ホストログディレクトリのサイズは、次のように計算されます。
ホストログディレクトリのサイズ=（（最大DB LDFサイズx日次ログ変更率%）x（Snapshot保持率）÷（1 LUNオーバーヘッドスペース%）
ホストログディレクトリのサイジング式では、LUNオーバーヘッドスペースが10%であることを前提としています。

ログディレクトリは専用のボリュームまたはLUNに配置します。ホストログディレクトリのデータ量は、バックアップのサイズとバックアップを保持する日数によって異なります。SnapCenterでは、SQL Serverホストごとに1つのホストログディレクトリのみが許可されます。ホストログディレクトリは、SnapCenter -->ホスト-->プラグインの設定で設定できます。

[TIP]
====
* NetAppでは、ホストログディレクトリに次のことを推奨しています*。

* ホストログディレクトリが、バックアップSnapshotデータを破損する可能性のある他のタイプのデータと共有されていないことを確認してください。
* マウントポイントをホストするLUNにユーザデータベースまたはシステムデータベースを配置しないでください。
* SnapCenterによるトランザクション・ログのコピー先となる専用ボリュームに、ホスト・ログ・ディレクトリを作成します。
* SnapCenterウィザードを使用してデータベースをNetAppストレージに移行し、データベースを有効な場所に格納できるようにすることで、SnapCenterのバックアップおよびリストア処理を正常に実行できます。移行プロセスはシステムの停止を伴うため、移行の実行中にデータベースを原因でオフラインにする可能性があることに注意してください。
* SQL Serverのフェイルオーバークラスタインスタンス（FCI）では、次の条件が満たされている必要があります。
+
** フェイルオーバークラスタインスタンスを使用している場合は、ホストログディレクトリLUNがSnapCenter、バックアップ対象のSQL Serverインスタンスと同じクラスタグループ内のクラスタディスクリソースである必要があります。
** フェイルオーバークラスタインスタンスを使用している場合は、SQL Serverインスタンスに関連付けられたクラスタグループに割り当てられた物理ディスククラスタリソースである共有LUNにユーザデータベースを配置する必要があります。




====