---
sidebar: sidebar 
permalink: mssql/mssql-overview.html 
keywords: MSSQL,SQL Server,TR-4590, SnapCenter, ONTAP 
summary: ONTAP上のMicrosoft SQL Server 
searchtitle: ONTAP上のMicrosoft SQL Server 
---
= 概要
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAPは解決策、Microsoft SQL Serverデータベースにエンタープライズクラスのセキュリティとパフォーマンスを提供すると同時に、環境を管理するためのワールドクラスのツールも提供します。


NOTE: このドキュメントは、以前に公開されたテクニカルレポート_TR-4590：『Best Practice Guide for Microsoft SQL Server with ONTAP』の内容を置き換えます。

NetAppは、読者が以下について実用的な知識を持っていることを前提としています。

* ONTAP
* Microsoft SQL Serverのアーキテクチャと管理
* SnapCenterバックアップソフトウェア（次のコンポーネントを含む）
* バックアップソフトウェアとしてのNetApp SnapCenterには、次のものが含まれます。
+
** SnapCenter Plug-in for Microsoft Windows の略
** SQL Server向けSnapCenterプラグイン




このベストプラクティスセクションの範囲は、NetAppがストレージインフラに推奨する原則と推奨される標準に基づいた技術設計に限定されます。エンドツーエンドの実装は範囲外です。

NetApp製品間の互換性については、を参照してくださいlink:https://mysupport.netapp.com/matrix/["ネットアップの Interoperability Matrix Tool （ IMT ）"^]。



== Microsoft SQL Serverのワークロード

SQL Serverを導入する前に、SQL Serverデータベースインスタンスがサポートするアプリケーションのワークロード要件を理解しておく必要があります。容量、パフォーマンス、可用性に関する要件はアプリケーションごとに異なるため、各データベースはこれらの要件を最適にサポートするように設計する必要があります。多くの組織では、アプリケーション要件を使用してSLAを定義し、データベースを複数の管理階層に分類しています。SQL Serverのワークロードは、次のように分類されます。

* OLTP：多くの場合、組織で最も重要なデータベースです。これらのデータベースは通常、顧客向けのアプリケーションをバックアップし、企業の中核業務に不可欠であると考えられています。ミッションクリティカルなOLTPデータベースとサポート対象のアプリケーションには、高いパフォーマンスが必要で、パフォーマンスの低下の影響を受けやすく、最大限の可用性が求められるSLAが用意されていることがよくあります。また、Always-OnフェイルオーバークラスタやAlways-On可用性グループの候補になることもあります。これらのタイプのデータベースでのI/O構成は、通常、ランダムリードが75~90%、書き込みが25~10%という特徴があります。
* 意思決定支援システム（DSS）データベース。データウェアハウスと呼ばれることもあります。これらのデータベースは、ビジネスの分析に依存している多くの組織にとってミッションクリティカルです。これらのデータベースは、クエリの実行時にCPU利用率やディスクからの読み取り処理の影響を受けます。多くの組織では、DSSデータベースは月、四半期、年末に最も重要なデータベースです。このワークロードは一般にほぼ100%の読み取りI/O構成であり、多くの場合、IOPSよりもI/Oスループットの方が重要です。

