---
sidebar: sidebar 
permalink: mssql/mssql-shared-vs-dedicated.html 
keywords: MSSQL,SQL Server, multiple instances, dedicated instance, ONTAP 
summary: Microsoft SQL Serverインスタンスの導入 
searchtitle: Microsoft SQL Serverインスタンスの導入 
---
= 共有インスタンスと専用インスタンス
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SQL Serverは、サーバごとに1つのインスタンスとして設定することも、複数のインスタンスとして設定することもできます。通常、適切な決定は、サーバを本番用と開発用のどちらに使用するか、インスタンスがビジネスの運用やパフォーマンスの目標にとって重要であると判断されるかなどの要因によって決まります。

共有インスタンスの設定は、最初は簡単に設定できますが、リソースが分割されたりロックされたりする問題が発生し、共有SQL Serverインスタンスでデータベースがホストされている他のアプリケーションでパフォーマンスの問題が発生する可能性があります。

どのインスタンスがルート原因であるかを把握する必要があるため、パフォーマンスの問題のトラブルシューティングは複雑になります。この質問は、オペレーティングシステムライセンスとSQL Serverライセンスのコストと比較して検討されます。アプリケーションのパフォーマンスを最優先する場合は、専用インスタンスを使用することを推奨します。

Microsoftでは、SQL Serverのライセンスは、インスタンス単位ではなく、コア単位でサーバレベルで付与されます。このため、データベース管理者は、ライセンスコストを削減するために、サーバで処理できる数のSQL Serverインスタンスをインストールしようとします。これは、後で大きなパフォーマンスの問題につながる可能性があります。


TIP: * NetAppでは、最適なパフォーマンスを得るために、可能な限り専用のSQL Serverインスタンスを選択することを推奨しています。
