---
sidebar: sidebar 
permalink: mssql/mssql-storage-considerations.html 
keywords: MSSQL,SQL Server, volumes, LUN, SnapCenter 
summary: Microsoft SQL Serverストレージに関する考慮事項 
searchtitle: Microsoft SQL Serverストレージに関する考慮事項 
---
= 概要
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAPストレージソリューションとMicrosoft SQL Serverを組み合わせることで、今日の最も要求の厳しいアプリケーション要件を満たすエンタープライズレベルのデータベースストレージ設計が可能になります。

SQL Server on ONTAPソリューションを最適化するには、SQL ServerのI/Oパターンと特性を理解する必要があります。SQL Serverデータベース用のストレージレイアウトを適切に設計するには、SQL Serverのパフォーマンス要件を満たしながら、インフラ全体の管理性を最大限に高める必要があります。また、ストレージレイアウトを適切に配置すれば、初期導入を成功させ、ビジネスの成長に合わせて環境をスムーズに拡張できます。



== データストレージ設計

SnapCenter を使用してバックアップを実行しないSQL Serverデータベースについては、データファイルとログファイルを別 々 のドライブに配置することを推奨します。データを同時に更新して要求するアプリケーションでは、ログファイルに書き込み負荷がかかり、（アプリケーションによっては）データファイルの読み取り/書き込み負荷が高くなります。データを取得する場合、ログファイルは必要ありません。そのため、データの要求は、そのドライブに配置されたデータファイルから満たすことができます。

新しいデータベースを作成するときは、データとログ用に別 々 のドライブを指定することを推奨します。データベース作成後にファイルを移動するには、データベースをオフラインにする必要があります。Microsoftのその他の推奨事項については、 link:https://docs.microsoft.com/en-us/sql/relational-databases/policy-based-management/place-data-and-log-files-on-separate-drives?view=sql-server-ver15["データファイルとログファイルを別 々 のドライブに配置"^]。



== AFFアグリゲート

アグリゲートは、AFF ストレージ構成における最下位レベルのストレージコンテナです。インターネット上には、I/O 処理を異なる基盤となるドライブ群に分離することを推奨する古いドキュメントがいくつか存在します。これは ONTAP では推奨されません。NetApp は、データファイルとトランザクションログファイルを分離した状態で、共有および専用のアグリゲートを使用して、さまざまな I/O ワークロード特性評価テストを実施しました。テスト結果によると、より多くの RAID グループとドライブを備えた大規模なアグリゲートを 1 つ使用することで、ストレージのパフォーマンスが最適化および向上し、次の 2 つの理由から管理者にとって管理が容易になることが示されています：

* 1つの大きなアグリゲート/SAにより、すべてのドライブのI/O機能をすべてのファイルで利用できるようになります。
* 1 つの大きなアグリゲートで、最も効率的なディスクスペースを使用できます。


高可用性（HA）を実現するには、SQL Server Always On可用性グループのセカンダリ同期レプリカを、アグリゲート内の別のStorage Virtual Machine（SVM）に配置します。ディザスタリカバリを目的とした場合は、DRサイト内の別のストレージクラスタの一部であるアグリゲートに非同期レプリカを配置し、NetApp SnapMirrorテクノロジを使用してコンテンツをレプリケートします。NetAppでは、ストレージのパフォーマンスを最適化するために、アグリゲートに利用可能な空きスペースを少なくとも10%確保することを推奨しています。



== 個のボリューム

ボリュームはアグリゲート内に作成されて格納されます。ONTAPボリュームがLUNではないため、この用語を使用すると混乱が生じることがあります。ONTAPボリュームはデータの管理コンテナです。ボリュームには、ファイル、LUN、さらにはS3オブジェクトが含まれている可能性があります。ボリュームはスペースを消費せず、格納されたデータの管理にのみ使用されます。



=== ボリュームの設計に関する考慮事項

データベースボリュームの設計を作成する前に、SQL ServerのI/Oパターンと特性がワークロードやバックアップとリカバリの要件に応じてどのように変わるかを理解しておくことが重要です。フレキシブルボリュームについては、NetAppに関する次の推奨事項を参照してください。

* ホスト間でのボリュームの共有は避けてください。たとえば、1つのボリュームに2つのLUNを作成し、各LUNを別のホストで共有することは可能ですが、管理が複雑になる可能性があるため、この方法は避けてください。同じホストで複数のSQL Serverインスタンスを実行する場合は、ノードのボリューム制限に近い場合を除き、ボリュームの共有は避け、データ管理を容易にするためにホストごとにインスタンスごとに個別のボリュームを作成してください。
* ドライブレターではなくNTFSマウントポイントを使用して、Windowsのドライブレターの制限（26文字）を超えます。ボリュームマウントポイントを使用する場合は、ボリュームラベルにマウントポイントと同じ名前を付けることを一般的に推奨します。
* 必要に応じて、スペース不足が発生しないようにボリュームのオートサイズポリシーを設定します。
* SQL ServerをSMB共有にインストールする場合は、フォルダを作成するためにSMBボリュームでUnicodeが有効になっていることを確認してください。
* 運用面からの監視を容易にするために、ボリュームのスナップショット予約値をゼロに設定します。
* Snapshotスケジュールと保持ポリシーを無効にします。代わりに、SnapCenterを使用してSQL ServerデータボリュームのSnapshotコピーを調整します。
* SQL Serverシステムデータベースを専用ボリュームに配置します。
* tempdbは、特にI/O負荷の高いDBCC CHECKDB処理のために、SQL Serverが一時的なワークスペースとして使用するシステムデータベースです。したがって、このデータベースは、独立したスピンドルセットを持つ専用ボリュームに配置します。ボリューム数が課題となる大規模な環境では、慎重に計画を立てたあと、tempdbを少数のボリュームに統合し、他のシステムデータベースと同じボリュームに格納できます。tempdbのデータ保護は、SQL Serverを再起動するたびにこのデータベースが再作成されるため、優先度の高いものではありません。
* (`.mdf`ランダムな読み取り/書き込みワークロードであるため、ユーザデータファイルを別 々 のボリュームに配置します。トランザクションログバックアップは、データベースバックアップよりも頻繁に作成するのが一般的です。このため、トランザクションログファイル(`.ldf`）をデータファイルとは別のボリュームまたはVMDKに配置して、それぞれに個別のバックアップスケジュールを作成できるようにします。また、この分離により、ログファイルのシーケンシャルライトI/Oとデータファイルのランダムリード/ライトI/Oが分離され、SQL Serverのパフォーマンスが大幅に向上します。




== LUN

* ユーザデータベースファイルとログバックアップを格納するログディレクトリが別 々 のボリュームにあることを確認して、SnapVaultテクノロジでSnapshotが使用されている場合に保持ポリシーによって上書きされないようにしてください。
* データベースファイルとデータベース以外のファイル（フルテキスト検索関連ファイルなど）を同じLUNに混在させないでください。
* データベースのセカンダリファイルを（ファイルグループの一部として）別 々 のボリュームに配置すると、SQL Serverデータベースのパフォーマンスが向上します。この分離は、データベースのファイルがLUNを他のファイルと共有していない `.mdf`場合にのみ有効 `.mdf`です。
* DiskManagerなどのツールを使用してLUNを作成する場合は、LUNをフォーマットするときに、パーティションの割り当て単位サイズが64Kに設定されていることを確認してください。
* を参照してください link:https://www.netapp.com/media/10680-tr4080.pdf["最新SANに対するONTAPのベストプラクティスに基づくMicrosoft WindowsとネイティブMPIO"] WindowsのマルチパスサポートをMPIOプロパティのiSCSIデバイスに適用するには、次の手順を実行します。

