---
sidebar: sidebar 
permalink: mssql/mssql-disaster-recovery-ASA.html 
keywords: MSSQL,SQL Server, disaster recovery, snapmirror 
summary: ONTAPを使用したMicrosoft SQL Serverディザスタリカバリ 
searchtitle: ONTAPを使用したMicrosoft SQL Serverディザスタリカバリ 
---
= ディザスタリカバリ
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
エンタープライズデータベースやアプリケーションインフラでは、自然災害や予期しないビジネスの中断からダウンタイムを最小限に抑えて保護するために、レプリケーションが必要になることがよくあります。

SQL Server Always-On可用性グループレプリケーション機能は優れたオプションであり、NetAppには、データ保護とAlways-Onを統合するためのオプションが用意されています。ただし、場合によっては、次のオプションを使用してONTAPレプリケーションテクノロジを検討することもできます。



== SnapMirror

SnapMirrorテクノロジーは、LANおよびWAN経由でデータを複製するための高速で柔軟なエンタープライズソリューションを提供します。最初のミラーリングの作成後は、変更されたデータブロックのみがデスティネーションに転送されるため、必要なネットワーク帯域幅が大幅に削減されますSnapMirror。同期モードまたは非同期モードのいずれかで設定できます。NetApp ASAでのSnapMirror同期レプリケーションは、SnapMirrorアクティブ同期を使用して設定します。



== SnapMirrorアクティブ同期

多くのお客様にとって、ビジネス継続性には、単にデータのリモートコピーを所有するだけでなく、SnapMirrorのアクティブ同期を使用してNetApp ONTAPで可能なデータを迅速に利用できる機能が必要です。

SnapMirrorアクティブ同期を使用すると、基本的には2つの異なるONTAPシステムでLUNデータの独立したコピーを維持しながら、このLUNの単一インスタンスを提供できます。ホストの観点からは、単一のLUNエンティティです。SnapMirrorアクティブ同期は、iSCSI / FCベースのLUNでサポートされます。

SnapMirrorアクティブ同期はRPO=0のレプリケーションを提供し、2つの独立したクラスタ間で簡単に実装できます。データの2つのコピーが同期されると、2つのクラスタは書き込みをミラーリングするだけで済みます。一方のクラスタで書き込みが発生すると、もう一方のクラスタにレプリケートされます。書き込みの確認応答がホストに送信されるのは、両方のサイトで書き込みが完了した場合だけです。このプロトコルスプリット動作以外では、2つのクラスタは通常のONTAPクラスタです。

SM-ASの主なユースケースの1つに、きめ細かなレプリケーションがあります。すべてのデータを1つのユニットとしてレプリケートしたくない場合や、特定のワークロードを選択的にフェイルオーバーできる必要がある場合があります。

SM-ASのもう1つの主なユースケースは、アクティブ/アクティブ処理です。アクティブ/アクティブ処理では、データの完全に使用可能なコピーを、同じパフォーマンス特性を持つ2つの異なるクラスタに配置し、必要に応じてSANをサイト間で拡張する必要がありません。アプリケーションがサポートされていれば、両方のサイトでアプリケーションをすでに実行しておくことができます。これにより、フェイルオーバー処理中の全体的なRTOが削減されます。
