---
sidebar: sidebar 
permalink: mssql/mssql-data-protection.html 
keywords: MS-SQL,mssql,SQL Server, SnapCenter, data protection 
summary: ONTAPを使用したMicrosoft SQL Serverのデータ保護 
---
= ONTAPを使用したMicrosoft SQL Serverのデータ保護
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
データベースの保護は、どのような組織にとっても重要です。データのサイズとデータベースの数が増えるにつれて、目標復旧時間（RTO）と目標復旧時点（RPO）を維持することが非常に重要になります。

データベースバックアップの主な考慮事項は、NetAppのSnapshotテクノロジの活用です。アプリケーションと整合性のあるバックアップとデータベースのレイアウトも、NetApp SnapCenterによるオーケストレーションが可能なRTOとRPOを達成するための重要な考慮事項です。



== SnapCenter

SnapCenterは、エンタープライズアプリケーション向けのNetAppデータ保護ソフトウェアです。NetApp SnapCenterソフトウェアとPlug-in for SQL ServerおよびPlug-in for Microsoft Windowsを併用することで、SQL Serverデータベースを迅速かつ簡単に保護できます。

この製品を使用すると、アプリケーションと整合性のあるバックアップ、自動クローニング、SQL Serverデータベース、インスタンス、可用性グループのリストアとリカバリを実行できます。


TIP: * NetAppでは* SnapCenterを使用してSnapshotコピーを作成することを推奨しています。

SQL Server Plug-in for SnapCenterの詳細については、を参照してください。 link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714：『Best Practice Guide for SQL Server using NetApp SnapCenter』"^]。



== T-SQLスナップショットを使用したデータベースの保護

SQL Server 2022では、MicrosoftがT-SQLスナップショットを導入しました。これは、データベース管理者が簡単に使用できなかった従来の方法よりも利点が組み込まれています。ONTAP REST APIを利用すると、Snapshotボリュームに対するコマンドを呼び出すことができます。

次に、バックアップワークフローの例を示します。

. ALTERコマンドを使用してデータベースをフリーズします。基盤となるストレージで整合性のあるスナップショットを実行できます。その後、backupコマンドを使用してデータベースを解凍し、Snapshotを記録できます。
. 新しいbackup groupコマンドとbackup serverコマンドを使用して、ストレージボリューム上の複数のデータベースのスナップショットを同時に実行します。
. フルバックアップまたはCOPY_ONLYフルバックアップを実行します。これらのバックアップもmsdbに記録されます。
. スナップショットフルバックアップ後に通常のストリーミング方式で作成されたログバックアップを使用して、ポイントインタイムリカバリを実行します。必要に応じて、ストリーミング差分バックアップもサポートされます。


詳細については、を参照してください link:https://learn.microsoft.com/en-us/sql/relational-databases/databases/create-a-database-snapshot-transact-sql?view=sql-server-ver16["T-SQLスナップショットについて知るためのMicrosoftのドキュメント"^]。
