---
sidebar: sidebar 
permalink: mssql/mssql-disaster-recovery.html 
keywords: MSSQL,SQL Server, disaster recovery, snapmirror 
summary: ONTAPを使用したMicrosoft SQL Serverディザスタリカバリ 
---
= ONTAPを使用したMicrosoft SQL Serverディザスタリカバリ
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
エンタープライズデータベースやアプリケーションインフラでは、自然災害や予期しないビジネスの中断からダウンタイムを最小限に抑えて保護するために、レプリケーションが必要になることがよくあります。

SQL Server Always-On可用性グループレプリケーション機能は優れたオプションであり、NetAppには、データ保護とAlways-Onを統合するためのオプションが用意されています。ただし、ONTAPレプリケーションテクノロジを検討する必要がある場合もあります。3つの基本的なオプションがあります。



== SnapMirror

SnapMirrorテクノロジーは、LANおよびWAN経由でデータを複製するための高速で柔軟なエンタープライズソリューションを提供します。最初のミラーリングの作成後は、変更されたデータブロックのみがデスティネーションに転送されるため、必要なネットワーク帯域幅が大幅に削減されますSnapMirror。同期モードまたは非同期モードのいずれかで設定できます。



== NetApp MetroCluster

MetroCluster構成は、アプリケーション、データベース、仮想化プラットフォームに高可用性とデータ損失ゼロのストレージソリューションを提供するのに役立ちます。このソリューションは、アレイベースのクラスタリングと同期レプリケーションを組み合わせて実装され、ストレージおよびホスト環境全体の保護レイヤを強化します。



== SnapMirrorアクティブ同期（旧称SnapMirrorビジネス継続性）

SnapMirrorアクティブ同期は、SnapMirror同期に基づいており、書き込み順序の整合性を維持しながら複数のLUNをレプリカストレージにレプリケートする機能を備えています。MetroClusterでは、ネットワーク構成を含むONTAPコントローラがサイト間で同一である必要があります。SnapMirrorアクティブ同期を使用すると、基本的には2つの異なるONTAPシステムでLUNデータの独立したコピーを維持しながら、このLUNの単一インスタンスを提供できます。ホストの観点からは、単一のLUNエンティティです。

MetroClusterとSnapMirrorのアクティブ同期の主な違いは、きめ細かさと拡張性です。特定のワークロードのみを同期レプリケーション対象として選択する必要がある場合や、LUNを両方のサイトで読み取り/書き込み処理できるようにする必要がある場合は、SnapMirrorアクティブ同期が適しています。環境全体やデータセンターをレプリケートする必要がある場合は、MetroClusterをお勧めします。また、SnapMirrorアクティブ同期は現在SAN専用ですが、MetroClusterはSAN、NFS、SMBなどのマルチプロトコルです。

SnapMirrorの詳細については、を参照してくださいlink:https://www.netapp.com/pdf.html?item=/media/17229-tr4015pdf.pdf["TR-4015：『SnapMirrorの設定およびベストプラクティスガイド- ONTAP 9』"^]。
