---
sidebar: sidebar 
permalink: mssql/storage-efficiency.html 
keywords: MS-SQL,mssql,SQL Server 
summary: ONTAP上のMicrosoft SQL Server 
---
= ONTAPによるMicrosoft SQL ServerのStorage Efficiency
:allow-uri-read: 


[role="lead"]
Storage Efficiencyとは、消費するストレージスペースを最小限に抑えながら、システム全体のパフォーマンスにほとんど影響を与えずに、SQL Serverデータを格納、管理できる機能です。

Storage Efficiencyは、RAID、プロビジョニング（全体的なレイアウトと利用率）、ミラーリング、その他のデータ保護テクノロジを組み合わせたものです。Snapshotコピー、シンプロビジョニング、FlexCloneなどのNetAppテクノロジを使用すると、インフラ内の既存のストレージを最適化し、将来のストレージ支出を先送りまたは回避することで、コスト削減を実現できます。これらのテクノロジを組み合わせて使用するほど、削減効果が大きくなります。詳細については、を参照してください link:../common/ontap/thin-provisioning.html["プロビジョニングの推奨事項"]

ストレージの圧縮、コンパクション、重複排除などのStorage Efficiencyオプションを使用すると、特定の物理ストレージに収まる論理データの量を増やすことができます。詳細については、を参照してください link:../common/ontap/efficiency.html["効率化のベストプラクティス"]。

SQL Serverには、データを圧縮して効率的に管理する機能もあります。SQL Serverでは現在、行圧縮とページ圧縮の2種類のデータ圧縮がサポートされています。

行圧縮を使用すると、データストレージ形式が変更されます。たとえば、整数と小数を、ネイティブの固定長形式ではなく可変長形式に変更します。また、空白スペースを排除することで、固定長の文字列を可変長形式に変更します。ページ圧縮では、行圧縮と他の2つの圧縮方式（プレフィックス圧縮とディクショナリ圧縮）が実装されます。ページ圧縮の詳細については、 link:https://learn.microsoft.com/en-us/sql/relational-databases/data-compression/page-compression-implementation?view=sql-server-ver16&redirectedfrom=MSDN["ページ圧縮の実装"^]。

データ圧縮は現在、SQL Server 2008以降のEnterprise、Developer、およびEvaluationエディションでサポートされています。圧縮はデータベース自体で実行できますが、SQL Server環境ではほとんど実行されません。

SQL Serverデータファイルのスペース管理の推奨事項は次のとおりです。

* SQL Server環境でシンプロビジョニングを使用すると、スペース利用率を向上し、スペースギャランティ機能を使用する場合に必要なストレージ全体を削減できます。
* ストレージ管理者が監視する必要があるのはアグリゲート内のスペース使用量だけであるため、一般的な構成では自動拡張を使用します。
* バックアップから単一ボリュームへのデータベースのリストアなど、同じデータのコピーがボリュームに複数含まれていることがわかっている場合を除き、SQL Serverデータファイルを含むボリュームで重複排除を有効にしないことを推奨します。




== スペース再生

スペース再生は、LUN内の未使用スペースをリカバリするために定期的に開始できます。SnapCenterでは、次のPowerShellコマンドを使用してスペース再生を開始できます。

[listing]
----
Invoke-SdHostVolumeSpaceReclaim -Path drive_path
----
スペース再生を実行する必要がある場合は、最初にホストのサイクルを消費するため、アクティビティが少ない時間帯にこのプロセスを実行する必要があります。
