---
sidebar: sidebar 
permalink: mssql/Storage-considerations.html 
keywords: MS-SQL,mssql,SQL Server, database layout 
summary: ONTAP上のMicrosoft SQL Server 
---
= Microsoft SQL Serverストレージに関する考慮事項
:allow-uri-read: 


[role="lead"]
NetAppストレージソリューションとMicrosoft SQL Serverを組み合わせることで、今日の最も要求の厳しいアプリケーション要件を満たすエンタープライズレベルのデータベースストレージ設計を作成できます。

両方のテクノロジを最適化するには、SQL ServerのI/Oパターンと特性を理解することが重要です。SQL Serverデータベース用の適切に設計されたストレージレイアウトは、SQL ServerのパフォーマンスとSQL Serverインフラの管理をサポートします。また、ストレージレイアウトを適切に配置すれば、初期導入を成功させ、ビジネスの成長に合わせて環境をスムーズに拡張できます。



== データストレージ設計

SnapCenter を使用してバックアップを実行しないSQL Serverデータベースについては、データファイルとログファイルを別 々 のドライブに配置することを推奨します。データを同時に更新して要求するアプリケーションでは、ログファイルに書き込み負荷がかかり、（アプリケーションによっては）データファイルの読み取り/書き込み負荷が高くなります。データを取得する場合、ログファイルは必要ありません。そのため、データの要求は、そのドライブに配置されたデータファイルから満たすことができます。

新しいデータベースを作成するときは、データとログ用に別 々 のドライブを指定することを推奨します。データベース作成後にファイルを移動するには、データベースをオフラインにする必要があります。Microsoftのその他の推奨事項については、 link:https://docs.microsoft.com/en-us/sql/relational-databases/policy-based-management/place-data-and-log-files-on-separate-drives?view=sql-server-ver15["データファイルとログファイルを別 々 のドライブに配置"^]。



== アグリゲート

アグリゲートはNetAppストレージ構成のプライマリストレージコンテナであり、データディスクとパリティディスクの両方で構成される1つ以上のRAIDグループを含みます。NetAppは、データファイルとトランザクションログファイルを分離した共有アグリゲートと専用アグリゲートを使用して、さまざまなI/Oワークロードの特性評価テストを実施してきました。このテストでは、1つの大規模アグリゲートに複数のRAIDグループとスピンドルを配置することで、ストレージのパフォーマンスが最適化されて向上し、管理者が管理しやすくなることがわかりました。その理由は次の2つです。

* 1つの大きなアグリゲートで、すべてのスピンドルのI/O機能をすべてのファイルで使用できます。
* 1 つの大きなアグリゲートで、最も効率的なディスクスペースを使用できます。


高可用性（HA）を実現するには、SQL Server Always On可用性グループのセカンダリ同期レプリカを、アグリゲート内の別のStorage Virtual Machine（SVM）に配置します。ディザスタリカバリを目的とした場合は、DRサイト内の別のストレージクラスタの一部であるアグリゲートに非同期レプリカを配置し、NetApp SnapMirrorテクノロジを使用してコンテンツをレプリケートします。NetAppでは、ストレージのパフォーマンスを最適化するために、アグリゲートに利用可能な空きスペースを少なくとも10%確保することを推奨しています。



== 個のボリューム

NetApp FlexVolボリュームはアグリゲート内に作成され、格納されます。1つのアグリゲートに多数のボリュームを作成し、各ボリュームを拡張、縮小、アグリゲート間で移動できます。ユーザのダウンタイムは発生しません。



=== ボリュームの設計に関する考慮事項

データベースボリュームの設計を作成する前に、SQL ServerのI/Oパターンと特性がワークロードやバックアップとリカバリの要件に応じてどのように変わるかを理解しておくことが重要です。フレキシブルボリュームについては、NetAppに関する次の推奨事項を参照してください。

* フレキシブルボリュームを使用してSQL Serverデータベースファイルを格納し、ホスト間でボリュームを共有しないようにします。
* ドライブレターではなくNTFSマウントポイントを使用して、Windowsのドライブレターの制限（26文字）を超えます。ボリュームマウントポイントを使用する場合は、ボリュームラベルにマウントポイントと同じ名前を付けることを一般的に推奨します。
* 必要に応じて、スペース不足が発生しないようにボリュームのオートサイズポリシーを設定します。17 ONTAPを使用したMicrosoft SQL Serverのベストプラクティスガイド©2022 NetApp、Inc. 無断転載を禁じます。
* SQL ServerデータベースのI/Oプロファイルが、意思決定支援システムのワークロードなど、大部分がラージシーケンシャルリードで構成されている場合は、ボリュームの読み取り再割り当てを有効にします。読み取り再割り当ては、パフォーマンスを向上させるためにブロックを最適化します。
* SQL ServerをSMB共有にインストールする場合は、フォルダを作成するためにSMB/CIFSボリュームでUnicodeが有効になっていることを確認してください。
* 運用面からの監視を容易にするために、ボリュームのNetApp Snapshotコピーリザーブの値を0に設定します。
* ストレージSnapshot™コピースケジュールと保持ポリシーを無効にします。代わりに、SnapCenterを使用してSQL ServerデータボリュームのSnapshotコピーを調整します。
* SQL Serverシステムデータベースを専用のボリュームまたはVMDKに配置します。
* tempdbは、特にI/O負荷の高いDBCC CHECKDB処理のために、SQL Serverが一時的なワークスペースとして使用するシステムデータベースです。したがって、このデータベースは、独立したスピンドルセットを持つ専用ボリュームに配置します。ボリューム数が課題となる大規模な環境では、慎重に計画を立てたあと、tempdbを少数のボリュームに統合し、他のシステムデータベースと同じボリュームに格納できます。tempdbのデータ保護は、SQL Serverを再起動するたびにこのデータベースが再作成されるため、優先度の高いものではありません。
* ランダムな読み取り/書き込みワークロードであるため、ユーザデータファイル（.mdf）を別 々 のボリュームに配置します。トランザクションログバックアップは、データベースバックアップよりも頻繁に作成するのが一般的です。そのため、トランザクションログファイル（.ldf）をデータファイルとは別のボリュームまたはVMDKに配置して、それぞれに個別のバックアップスケジュールを作成できるようにします。この分離により、ログファイルのシーケンシャルライトI/Oがデータファイルのランダムリード/ライトI/Oから分離され、SQL Serverのパフォーマンスが大幅に向上します。




== LUN

* ユーザデータベースファイルとログバックアップを格納するログディレクトリが別 々 のボリュームにあることを確認して、SnapVaultテクノロジでSnapshotが使用されている場合に保持ポリシーによって上書きされないようにしてください。
* SQL Serverデータベースが、フルテキスト検索関連ファイルなど、データベース以外のファイルを持つLUNとは別のLUN上に存在することを確認します。
* データベースのセカンダリファイルを（ファイルグループの一部として）別 々 のボリュームに配置すると、SQL Serverデータベースのパフォーマンスが向上します。この分離は、データベースの.mdfファイルがLUNを他の.mdfファイルと共有していない場合にのみ有効です。
* DiskManagerなどのツールを使用してLUNを作成する場合は、LUNをフォーマットするときに、パーティションの割り当て単位サイズが64Kに設定されていることを確認してください。
* を参照してください link:https://www.netapp.com/media/10680-tr4080.pdf["最新SANに対するONTAPのベストプラクティスに基づくMicrosoft WindowsとネイティブMPIO"] WindowsのマルチパスサポートをMPIOプロパティのiSCSIデバイスに適用するには、次の手順を実行します。




=== ログディレクトリ

ログディレクトリは、トランザクションログバックアップデータをホストレベルで格納するためにSQL Serverで指定します。SnapCenterを使用してログファイルをバックアップする場合は、SnapCenterで使用される各SQL Serverホストに、ログバックアップを実行するようにホストログディレクトリを設定する必要があります。SnapCenter にはデータベースリポジトリがあるため、バックアップ、リストア、クローニングの処理に関連するメタデータは中央のデータベースリポジトリに格納されます。

ホストログディレクトリのサイズは、次のように計算されます。
ホストログディレクトリのサイズ=（（最大DB LDFサイズx日次ログ変更率%）x（Snapshot保持率）÷（1 LUNオーバーヘッドスペース%）
ホストログディレクトリのサイジング式では、LUNオーバーヘッドスペースが10%であることを前提としています。

ログディレクトリは専用のボリュームまたはLUNに配置します。ホストログディレクトリのデータ量は、バックアップのサイズとバックアップを保持する日数によって異なります。SnapCenterでは、SQL Serverホストごとに1つのホストログディレクトリのみが許可されます。ホストログディレクトリは、SnapCenter -->ホスト-->プラグインの設定で設定できます。

[TIP]
====
* NetAppでは、ホストログディレクトリに次のことを推奨しています*。

* ホストログディレクトリが、バックアップSnapshotデータを破損する可能性のある他のタイプのデータと共有されていないことを確認してください。
* マウントポイントをホストするLUNにユーザデータベースまたはシステムデータベースを配置しないでください。
* SnapCenterによるトランザクション・ログのコピー先となる専用のFlexVolボリューム上に、ホスト・ログ・ディレクトリを作成します。
* SnapCenterウィザードを使用してデータベースをNetAppストレージに移行し、データベースを有効な場所に格納できるようにすることで、SnapCenterのバックアップおよびリストア処理を正常に実行できます。移行プロセスはシステムの停止を伴うため、移行の実行中にデータベースを原因でオフラインにする可能性があることに注意してください。
* SQL Serverのフェイルオーバークラスタインスタンス（FCI）では、次の条件が満たされている必要があります。
+
** フェイルオーバークラスタインスタンスを使用している場合は、ホストログディレクトリLUNがSnapCenter、バックアップ対象のSQL Serverインスタンスと同じクラスタグループ内のクラスタディスクリソースである必要があります。
** フェイルオーバークラスタインスタンスを使用している場合は、SQL Serverインスタンスに関連付けられたクラスタグループに割り当てられた物理ディスククラスタリソースである共有LUNにユーザデータベースを配置する必要があります。




====