---
sidebar: sidebar 
permalink: mssql/workloads.html 
keywords: MS-SQL,mssql,SQL Server 
summary: ONTAP上のMicrosoft SQL Server 
---
= Microsoft SQL Serverのワークロード
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SQL Serverデータベースプラットフォームは、多くのアプリケーションをサポートできます。

SQL Serverを導入する前に、SQL Serverインスタンスがサポートするアプリケーションのデータベースワークロード要件を理解しておく必要があります。容量、パフォーマンス、可用性に関する要件はアプリケーションごとに異なるため、各データベースはこれらの要件を最適にサポートするように設計する必要があります。多くの組織では、アプリケーション要件を使用してSLAを定義し、データベースを複数の管理階層に分類しています。SQL Serverのワークロードは次のように記述できます。

* OLTPデータベースは、多くの場合、組織で最も重要なデータベースでもあります。これらのデータベースは通常、顧客向けのアプリケーションをバックアップし、企業の中核業務に不可欠であると考えられています。ミッションクリティカルなOLTPデータベースとサポート対象のアプリケーションには、高レベルのパフォーマンスが必要で、パフォーマンスの低下や可用性の影響を受けやすいSLAが設定されていることがよくあります。また、Always-OnフェイルオーバークラスタやAlways-On可用性グループの候補になることもあります。これらのタイプのデータベースのI/O構成は、通常、ランダムリードが75~90%、書き込みが25~10%という特徴があります。
* 意思決定支援システム(DSS)データベースは、データウェアハウスとも呼ばれます。これらのデータベースは、ビジネスの分析に依存している多くの組織でミッションクリティカルです。これらのデータベースは、クエリの実行時にCPU利用率やディスクからの読み取り処理の影響を受けます。多くの組織では、DSSデータベースは月、四半期、年末に最も重要なデータベースです。このワークロードは、一般に100%の読み取りI/O構成です。




== ベンチマーク

Transaction Process Council（TPC）は、トランザクション処理とデータベースのベンチマークを定義し、客観的で検証可能なTPCパフォーマンスデータを業界に広めるために設立された非営利団体です。TPCテストは、ユーザがデータベースに対してトランザクションを実行する完全なコンピューティング環境をシミュレートします。

[cols="1,1,1"]
|===


| ワークロードの種類 | シナリオ（ Scenario ） | 読み取り/書き込み比率（割合） 


| OLTP | TPC-C | ～75/25 


| OLTP | TPC-E | ～90/10 


| DSS | TPC-H | ~100/0 
|===
さまざまなワークロード生成オプションを利用できますが、一般的には、トランザクションワークロードを処理する際のSQL Serverデータベースのパフォーマンス測定に重点を置いており、MicrosoftのTPC-EツールやHammerDB（link:http://www.hammerdb.com/document.html["HammerDB.com"]^）。これらの特定のベンチマークの使用方法の詳細な手順は、このドキュメントでは説明していません。
