---
sidebar: sidebar 
permalink: vmware/vmware-srm-ontap-tools-features.html 
keywords: vmware, site, recovery manager, vsrm, vsphere, ipv6, support, rest, api, replication, ccols, spbm, srm, appliance based 
summary: ONTAP toolsでの機能、制限、VVOLのサポート。 
---
= VLSR/SRMおよびONTAPツールの新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
従来の仮想アプライアンスからの移行に対応した ONTAP ツールには、豊富な新機能と上限があり、 VVOL が新たにサポートされるようになりました。



== vSphere および Site Recovery Manager の最新バージョン

ネットアップは、約 20 年にわたり VMware との緊密なパートナーシップを共有し、できるだけ早く最新リリースのサポートを提供するよう努めています。ソフトウェアの認定された最新の組み合わせについては、必ずNetAppを確認してください https://mysupport.netapp.com/matrix/imt.jsp?components=84943;&solution=1777&isHWU&src=IMT["Interoperability Matrix Tool （ IMT ）"^]。



== IPv6 のサポート

IPv6 が次の制限付きでサポートされるようになりました。

* SRM 8.2 （ 8.1 、 8.3 、および 8 ）ではサポートされていません。4以降がサポートされています）
* 認定されている最新バージョンについては、を参照してください https://mysupport.netapp.com/matrix/imt.jsp?components=84943;&solution=1777&isHWU&src=IMT["Interoperability Matrix Tool （ IMT ）"^]。




== 拡張性の向上

ONTAP tools 10.4 SRAで、VLSR/SRMの最大スケールをサポートできるようになりました。

* 保護されているVMの総数= 5000
* 保護グループあたりのVM数= 1000
* リカバリプランの総数= 250
* リカバリプランあたりの保護グループの総数= 250
* レプリケートされたデータストアの総数= 255
* 同時に実行されているリカバリプランの総数。= 10




== 同期レプリケーション

待望の新機能として、 ONTAP 9.5 以降を搭載した SnapMirror Synchronous （ SM-S ）があります。この機能は、ミッションクリティカルなアプリケーションに対して、ボリュームレベルで RPO ゼロのデータレプリケーション解決策を提供します。SM-S には、 ONTAP ツール 9.8 以降が必要です。



== REST API をサポート

SRA サーバの設定を REST API で管理できるようになりました。自動化ワークフローの構築を支援するSwagger UIが追加されました。ONTAP toolsアプライアンスのにあります。 `https://<appliance>:8443/`
