---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-network.html 
keywords: vSphere, datastore, VMFS, FC, FCoE, NVMe-FC, iSCSI, NFS, vVols 
summary: このページでは、VMware vSphere環境にONTAPストレージ解決策を実装するためのベストプラクティスについて説明します。 
---
= ネットワーク構成：
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAPを実行するシステムでvSphereを使用する場合のネットワーク設定の構成は簡単で、他のネットワーク構成と同様です。

考慮すべき点をいくつか挙げます。

* ストレージネットワークのトラフィックを他のネットワークから分離します。専用の VLAN を使用するか、ストレージ用に別個のスイッチを使用することで、別のネットワークを実現できます。ストレージネットワークがアップリンクなどの物理パスを共有している場合は、十分な帯域幅を確保するために QoS または追加のアップリンクポートが必要になることがあります。ソリューションガイドで明確に指示されている場合を除き、ホストをストレージに直接接続しないでください。スイッチを使用して冗長パスを確保し、VMware HAが介入なしで動作できるようにします。
* ネットワークでサポートされている場合は、ジャンボフレームを使用してください。使用する場合は、ストレージと ESXi ホストの間のパスにあるすべてのネットワークデバイスや VLAN で設定が同じであることを確認してください。そうしないと、パフォーマンスや接続の問題が発生する可能性があります。MTU は、 ESXi 仮想スイッチ、 VMkernel ポート、および各 ONTAP ノードの物理ポートまたはインターフェイスグループでも同一の設定にする必要があります。
* NetAppでは、ONTAPクラスタ内のクラスタインターコネクトポートでのみネットワークフロー制御を無効にすることを推奨しています。NetAppでは、データトラフィックに使用される残りのネットワークポートのフロー制御に関するベストプラクティスについて、これ以外の推奨事項はありません。必要に応じて有効または無効にする必要があります。フロー制御の詳細については、を参照してください https://www.netapp.com/pdf.html?item=/media/16885-tr-4182pdf.pdf["TR-4182"^]。
* ESXi および ONTAP ストレージアレイをイーサネットストレージネットワークに接続するときは、接続先のイーサネットポートを Rapid Spanning Tree Protocol （ RSTP ；高速スパニングツリープロトコル）のエッジポートとして設定するか、 Cisco の PortFast 機能を使用して設定することを推奨します。ネットアップでは、 Cisco の PortFast 機能を使用していて、 ESXi サーバまたは ONTAP ストレージアレイへの 802.1Q VLAN トランキングが有効になっている環境では、 Spanning-Tree PortFast trunk 機能を有効にすることを推奨します。
* リンクアグリゲーションのベストプラクティスとして次を推奨します。
+
** CiscoのVirtual PortChannel（vPC）などのマルチシャーシリンクアグリゲーショングループアプローチを使用して、2つの別 々 のスイッチシャーシ上のポートのリンクアグリゲーションをサポートするスイッチを使用します。
** LACPが設定されたdvSwitches 5.1以降を使用していない場合、ESXiに接続されているスイッチポートのLACPを無効にします。
** LACPを使用して、IPハッシュを持つダイナミックマルチモードインターフェイスグループを持つONTAP ストレージシステムのリンクアグリゲートを作成します。
** ESXiでIPハッシュチーミングポリシーを使用します。




次の表に、ネットワーク設定項目とその適用先をまとめます。

|===
| 項目 | ESXi | スイッチ | ノード | SVM 


| IP アドレス | VMkernel | いいえ ** | いいえ ** | はい。 


| リンクアグリゲーション | 仮想スイッチ | はい。 | はい。 | いいえ * 


| VLAN | VMkernel と VM ポートグループ | はい。 | はい。 | いいえ * 


| フロー制御 | NIC | はい。 | はい。 | いいえ * 


| スパニングツリー | いいえ | はい。 | いいえ | いいえ 


| MTU （ジャンボフレーム用） | 仮想スイッチと VMkernel ポート（ 9000 ） | ○（最大に設定） | ○（ 9000 ） | いいえ * 


| フェイルオーバーグループ | いいえ | いいえ | ○（作成） | ○（選択） 
|===
* SVM LIFは、VLANやMTUなどが設定されたポート、インターフェイスグループ、またはVLANインターフェイスに接続します。ただし、設定の管理はSVMレベルではありません。

** これらのデバイスには管理用に独自の IP アドレスがありますが、 ESXi ストレージネットワークのコンテキストでは使用されません。



== SAN（FC、NVMe/FC、iSCSI、NVMe/TCP）、RDM

ONTAPは、従来のiSCSIとファイバチャネルプロトコル（FCP）を使用してVMware vSphere向けにエンタープライズクラスのブロックストレージを提供します。また、効率性とパフォーマンスに優れた次世代ブロックプロトコルであるNVMe over Fabrics（NVMe-oF）を使用し、NVMe/FCとNVMe/TCPの両方をサポートしています。

vSphereとONTAPを使用してVMストレージにブロックプロトコルを実装する場合の詳細なベストプラクティスについては、link:vmware-vsphere-datastores-san.html["データストアとプロトコル- SAN"]



== NFS

vSphere を使用すると、エンタープライズクラスの NFS アレイを使用して、 ESXi クラスタ内のすべてのノードへのデータストアへの同時アクセスを提供できます。セクションで説明したように、link:vmware-vsphere-datastores-top.html["データストア"]vSphereでNFSを使用すると、使いやすさとストレージ効率の可視化のメリットがいくつかあります。

推奨されるベストプラクティスについては、を参照してください。link:vmware-vsphere-datastores-nfs.html["データストアとプロトコル- NFS"]



== 直接接続ネットワーク

仮想化管理者は、ネットワークスイッチを構成から削除することでインフラストラクチャを簡素化することを好む場合があります。これにより、構成部品が少なく、ラック内の必要スペースも少ない、より自己完結型のソリューションを構築することが可能になります。使用するプロトコルによって、いくつかの重要な制約事項が存在します。



=== ファイバーチャネル

ONTAP 9.19.1 以降、従来型の FC-SAN（SCSI）と一部のストレージシステム FC アダプタを使用した NVMe/FC の両方で、ダイレクト接続 FC がサポートされています。HBA は標準的なポイントツーポイント FC 接続を確立します。

ONTAP 9.19.1 より前のバージョンでは、ONTAP ストレージシステムには NPIV が必要です。つまり、ストレージシステムは NPIV をサポートする FC スイッチに接続されている必要があります。



=== iSCSIとNVMe/TCP

iSCSIまたはNVMe/TCPを使用するホストは、ストレージシステムに直接接続して正常に動作することができます。その理由はパス設定です。2つの異なるストレージコントローラに直接接続すると、データフローが2つの独立したパスになります。パス、ポート、またはコントローラが失われても、他のパスの使用が妨げられることはありません。



=== NFS

直接接続されたNFSストレージも使用できますが、フェイルオーバーには大きな制限があります。スクリプト作成にはお客様の責任が伴います。

直接接続されたNFSストレージで無停止フェイルオーバーが複雑になるのは、ローカルOSで発生するルーティングが原因です。たとえば、ホストのIPアドレスが192.168.1.1/24で、IPアドレスが192.168.1.50/24のONTAPコントローラに直接接続されているとします。フェールオーバー中、192.168.1.50アドレスはもう一方のコントローラにフェールオーバーでき、ホストが使用できるようになりますが、ホストはそのアドレスの存在をどのように検出しますか。元の192.168.1.1アドレスは、動作中のシステムに接続されていないホストNICに残っています。192.168.1.50宛てのトラフィックは、動作不能なネットワークポートに引き続き送信されます。

2 番目の OS NIC は 192.168.1.2 として構成でき、フェイルオーバーした 192.168.1.50 アドレスと通信できますが、ローカル ルーティング テーブルはデフォルトで 1 つのアドレス*のみ*を使用して 192.168.1.0/24 サブネットと通信します。システム管理者は、ネットワーク接続の障害を検出し、ローカル ルーティング テーブルを変更したり、インターフェースを起動／停止したりするスクリプト フレームワークを作成できます。具体的な手順は、使用している OS によって異なります。

実際にはNetAppを使用していますが、通常はフェイルオーバー中のIO一時停止が許容されるワークロードのみが対象です。ハードマウントを使用する場合は、一時停止中にIOエラーが発生しないようにしてください。ホスト上のNIC間でIPアドレスを移動するためのフェイルバックまたは手動操作によって、サービスが復元されるまでIOはハングします。
