---
sidebar: sidebar 
permalink: vmware/vmware-srm-deployment_best_practices.html 
keywords: vmware, site, recovery manager, vsrm, svm, layout, segmentation, smt, best, practices, deploy, ontap, tools, vvols, srm, vlsr 
summary: ONTAP では、 Storage Virtual Machine （ SVM ）の概念を採用して、セキュアなマルチテナント環境で厳密にセグメント化します。 
---
= 導入のベストプラクティス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
次のセクションでは、ONTAPとVMware SRMを使用した導入のベストプラクティスについて説明します。



== 最新バージョンのONTAP toolsを使用する10

ONTAP tools 10では、以前のバージョンに比べて次の点が大幅に改善されています。

* テストフェイルオーバーが8倍高速*
* クリーンアップと再保護が2倍高速*
* フェイルオーバーが32%高速*
* 拡張性の向上
* 共有サイトレイアウトのネイティブサポート


*これらの改善点は内部テストに基づいており、環境によって異なる場合があります。



== SMT の SVM のレイアウトとセグメント化

ONTAP では、 Storage Virtual Machine （ SVM ）の概念を採用して、セキュアなマルチテナント環境で厳密にセグメント化します。ある SVM の SVM ユーザは、別の SVM のリソースにアクセスしたりリソースを管理したりすることはできませんこれにより、 ONTAP テクノロジを活用できます。ビジネスユニットごとに別々の SVM を作成して、同じクラスタ上で独自の SRM ワークフローを管理することで、全体的なストレージ効率を高めることができます。

SVM を対象としたアカウントと SVM 管理 LIF を使用して ONTAP を管理することを検討し、セキュリティ制御を強化するだけでなく、パフォーマンスも向上させます。SRA は、物理リソースを含むクラスタ全体のすべてのリソースを処理する必要がないため、 SVM を対象とした接続を使用する場合は本質的にパフォーマンスが向上します。その代わり、特定の SVM に抽象化された論理資産だけを認識する必要があります。



== ONTAP 9 システムの管理に関するベストプラクティス

前述したように、クラスタまたは SVM を対象としたクレデンシャルと管理 LIF を使用して ONTAP クラスタを管理できます。パフォーマンスを最適化するには、VVOLを使用しないときは常にSVMを対象としたクレデンシャルの使用を検討してください。ただし、その場合は、いくつかの要件について確認しておく必要があります。また、機能の一部は失われます。

* デフォルトの vsadmin SVM アカウントには、 ONTAP ツールのタスクを実行するために必要なアクセスレベルがありません。そのため、新しいSVMアカウントを作成する必要があります。 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-user-role-and-privileges.html["ONTAPユーザのロールと権限の設定"]含まれているJSONファイルを使用します。これは SVM またはクラスタを対象としたアカウントに使用できます。
* vCenter UIプラグイン、VASA Provider、SRAサーバはすべて完全に統合されたマイクロサービスであるため、ONTAP toolsのvCenter UIでストレージを追加する場合と同じ方法で、SRMでSRAアダプタにストレージを追加する必要があります。そうしないと、 SRA サーバが SRA アダプタ経由で SRM から送信された要求を認識しない可能性があります。
* SVMを対象としたクレデンシャルを使用している場合、最初にONTAP tools Managerを使用してvCenterに関連付けないかぎり、NFSパスのチェックは実行されませ https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["オンホオトクラスタ"]ん。これは、物理的な場所が SVM から論理的に抽象化されているためです。ただしこれは原因の問題ではありません。最新の ONTAP システムで間接パスを使用してもパフォーマンスが著しく低下することはなくなりました。
* Storage Efficiency によるアグリゲートのスペース削減量が報告されないことがあります。
* サポートされている場合、負荷共有ミラーを更新することはできません。
* SVM を対象としたクレデンシャルで管理されている ONTAP システムでは、 EMS ロギングが実行されない場合があり

