---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-sdrs.html 
keywords: Data protection, Space reclamation, VM and datastore cloning, Storage efficiency, thin provisioning, QoS, SIOC, Storage Distributed Resource Scheduler, DRS, Active IQ Unified Manager, Encryption 
summary: SnapCenter では、複数のジョブに適用可能なバックアップポリシーを作成できます。これらのポリシーでは、スケジュール、保持、レプリケーションなどの機能を定義できます。VMwareスナップショットを作成する前にI/Oを休止するハイパーバイザーの機能を活用して、VM整合性スナップショットをオプションで選択できます。 
---
= VMware Storage Distributed Resource Scheduler の略
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware Storage Distributed Resource Scheduler（SDRS）は、現在のI/Oレイテンシとスペース使用量に基づいてデータストアクラスタにVMを自動的に配置するvSphereの機能です。

その後、 VM や VMDK の配置先として最適なデータストアをデータストアクラスタ内から選択し、システムを停止することなくデータストアクラスタ（ポッドとも呼ばれます）内のデータストア間で VM や VMDK を移動します。データストアクラスタは、類似するデータストアをvSphere管理者から見た単一の消費単位に集約したものです。

SDRSとONTAP tools for VMware vSphereを使用する場合は、まずプラグインを使用してデータストアを作成し、vCenterを使用してデータストアクラスタを作成してから、そのデータストアにデータストアを追加する必要があります。データストアクラスタを作成したら、プロビジョニングウィザードの詳細ページからデータストアクラスタにデータストアを直接追加できます。

SDRS に関するその他の ONTAP のベストプラクティスは、次のとおりです。

* 特定の要件がない限り、SDRSを使用しないでください。
+
** ONTAPを使用する場合、SDRは必要ありません。SDRは重複排除や圧縮などのONTAPのStorage Efficiency機能を認識しないため、環境に最適でない判断を下す可能性があります。
** SDRはONTAP QoSポリシーを認識しないため、パフォーマンスに最適でない判断を下す可能性があります。
** SDRはONTAP Snapshotコピーを認識しないため、Snapshotが急増する原因となるような判断を下す可能性があります。たとえば、VMを別のデータストアに移動すると、新しいデータストアに新しいファイルが作成されるため、スナップショットが拡張されます。これは、大容量ディスクまたは多数のスナップショットを持つVMに特に当てはまります。その後、VMを元のデータストアに戻すと、元のデータストア上のスナップショットがさらに大きくなります。




SDRSを使用する場合は、次のベストプラクティスを考慮してください。

* クラスタ内のすべてのデータストアで同じタイプのストレージ（ SAS 、 SATA 、 SSD など）を使用し、すべて VMFS データストアまたは NFS データストアとし、レプリケーションと保護の設定を同じにします。
* デフォルト（手動）モードでは SDRS の使用を検討してください。このアプローチでは、推奨事項を確認し、適用するかどうかを決定できます。VMDK の移行による影響を次に示します。
+
** SDRSがデータストア間でVMDKを移動する場合、デスティネーションでの重複排除または圧縮の度合いに応じて、ONTAPのクローニングや重複排除によるスペース削減量が削減されることがあります。
** NetAppでは、VMDKを移動したあとに、移動したVMによってスペースがロックされるため、ソースデータストアでSnapshotを再作成することを推奨しています。
** 同じアグリゲート上のデータストア間で VMDK を移動してもメリットはほとんどなく、 SDRS はアグリゲートを共有する可能性のある他のワークロードを可視化できません。




SDRSの詳細については、VMwareのドキュメントを参照してください https://knowledge.broadcom.com/external/article/320864/storage-drs-faq.html["Storage DRS FAQ"^]。
