---
sidebar: sidebar 
permalink: vmware/vmware-srm-overview.html 
keywords: ontap, vsphere, srm, srm, hybrid, cloud, migration, vmware, site, recovery manager, vsrm,VLSR 
summary: VMware Live Site Recovery（VLSR）およびSite Recovery Manager（SRM）向けのONTAPソリューション 
---
= ONTAPを使用したVMwareライブサイトリカバリ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
20 年以上前に ESX が最新のデータセンターに導入されて以来、 ONTAP はVMware vSphere、そして最近では Cloud Foundation の主要なストレージ ソリューションとなっています。 NetApp は、 SnapMirrorアクティブ シンクなどの機能とともに、最新世代のASA A シリーズなどの革新的なシステムを継続的に導入しています。これらの進歩により、管理が簡素化され、回復力が強化され、IT インフラストラクチャの総所有コスト (TCO) が削減されます。

このドキュメントでは、VMware の業界をリードする災害復旧 (DR) ソフトウェアである VMware Live Site Recovery (VLSR) (旧称 Site Recovery Manager (SRM)) のONTAPソリューションについて紹介します。これには、導入の合理化、リスクの軽減、継続的な管理の簡素化を実現するための最新の製品情報とベスト プラクティスが含まれます。


NOTE: このドキュメントは、以前に公開された技術レポート_TR-4900: VMware Site Recovery Manager with ONTAP_に代わるものです。

ベストプラクティスは、ガイドや互換性ツールなどの他のドキュメントを補うものです。ラボテストに基づいて開発されており、ネットアップのエンジニアやお客様は広範な現場経験を積んでいます。推奨されるベストプラクティスがお客様の環境に適していない場合もありますが、一般に最もシンプルなソリューションであり、ほとんどのお客様のニーズに対応できます。

本ドキュメントでは、ONTAP tools for VMware vSphere 10.4（NetApp Storage Replication Adapter[SRA]およびVASA Provider[VP]を含む）およびVMware Live Site Recovery 9と組み合わせて使用した場合のONTAP 9の最近のリリースの機能について説明します。



== VLSRまたはSRMでONTAPを使用する理由

ONTAPを搭載したNetAppデータ管理プラットフォームは、VLSR で最も広く採用されているストレージ ソリューションの 1 つです。理由はたくさんあります。業界をリードするストレージ効率、マルチテナント、サービス品質の制御、スペース効率の高いスナップショットによるデータ保護、 SnapMirrorによるレプリケーションを提供する、安全で高性能な統合プロトコル (NAS と SAN の組み合わせ) のデータ管理プラットフォームです。これらすべては、ネイティブのハイブリッド マルチクラウド統合を活用して VMware ワークロードを保護し、豊富な自動化およびオーケストレーション ツールを簡単に利用できるようにします。

アレイベースのレプリケーションにSnapMirror を使用すると、ONTAP の最も実績があり成熟したテクノロジの 1 つを活用できます。 SnapMirror を使用すると、VM 全体またはデータストア全体ではなく、変更されたファイル システム ブロックのみをコピーすることで、安全で効率の高いデータ転送が可能になります。これらのブロックでも、重複排除、圧縮、コンパクト化などのスペース節約が活用されます。最新のONTAPシステムではバージョンに依存しないSnapMirrorが使用されるようになり、ソース クラスターと宛先クラスターを柔軟に選択できるようになりました。  SnapMirror は、災害復旧に利用できる最も強力なツールの 1 つになりました。

従来の NFS、iSCSI、またはファイバ チャネル接続データストア ( vVolsデータストアもサポートされるようになりました) を使用している場合でも、VLSR は、災害復旧やデータセンター移行の計画とオーケストレーションにONTAPの機能を最大限に活用する強力なファーストパーティ製品を提供します。



== VLSR での ONTAP 9 の活用方法

VLSR は、 ONTAP システムの高度なデータ管理テクノロジを活用して、 3 つの主要コンポーネントで構成される仮想アプライアンスである VMware vSphere 用 ONTAP ツールと統合します。

* ONTAP tools vCenterプラグイン（旧称Virtual Storage Console（VSC））は、SANとNASのどちらを使用している場合でも、ストレージ管理と効率化機能を簡易化し、可用性を高め、ストレージコストと運用オーバーヘッドを削減します。データストアのプロビジョニングのベストプラクティスを使用して、 NFS 環境およびブロックストレージ環境用の ESXi ホスト設定を最適化します。NetAppでは、ONTAPを実行しているシステムでvSphereを使用する際に、これらのメリットをすべて考慮してこのプラグインを推奨しています。
* ONTAP tools VASA Providerは、VMware vStorage APIs for Storage Awareness（VASA）フレームワークをサポートします。VASA Provider では、 VM ストレージのプロビジョニングと監視に役立つように vCenter Server と ONTAP を接続します。これにより、VMware Virtual Volumes（vVol）のサポート、VMストレージポリシーの管理、および個 々 のVM vVolのパフォーマンスの管理が可能になりました。また、容量の監視やプロファイルへの準拠に関するアラームも生成されます。
* SRA は VLSR と一緒に使用され、従来の VMFS データストアと NFS データストアの本番サイトとディザスタリカバリサイト間での VM データのレプリケーションを管理します。また、 DR レプリカの無停止テストにも使用できます。検出、リカバリ、再保護のタスクを自動化します。SRAサーバアプライアンスと、Windows SRMサーバおよびVLSRアプライアンス用のSRAアダプタの両方が含まれています。


非 vVols データストアを保護するために VLSR サーバーに SRA アダプタをインストールして構成したら、災害復旧用に vSphere 環境を構成するタスクを開始できます。

SRAは、VMware仮想マシン（VM）を含むONTAP FlexVolボリュームおよびそれらを保護するSnapMirrorレプリケーションを管理するためのVLSRサーバ用のコマンドおよび制御インターフェイスを提供します。

VLSR は、NetApp 独自のFlexCloneテクノロジーを使用して DR サイトの保護されたデータストアのクローンをほぼ瞬時に作成し、中断なく DR プランをテストできます。  VLSR は、実際の災害発生時に組織と顧客が保護されるように安全にテストするためのサンドボックスを作成し、災害時に組織がフェールオーバーを実行できることに自信を持たせます。

実際に災害が発生した場合や、計画的な移行の場合でも、 VLSR では、最終的な SnapMirror 更新（必要な場合）を使用して、データセットに最新の変更を送信できます。その後、ミラーを解除し、 DR ホストにデータストアをマウントします。この時点で、計画済みの戦略に基づいて、 VM の電源を任意の順序で自動的にオンにすることができます。


NOTE: ONTAPシステムではSnapMirrorレプリケーション用に同じクラスタ内のSVMをペアリングできますが、このシナリオのテストおよび認定はVLSRでは行われていません。したがって、VLSRを使用する場合は、異なるクラスタのSVMのみを使用することを推奨します。



== VLSR と ONTAP などのユースケース：ハイブリッドクラウドと移行

VLSR 展開をONTAP の高度なデータ管理機能と統合すると、ローカル ストレージ オプションと比較して、スケールとパフォーマンスが大幅に向上します。しかし、それ以上に、ハイブリッド クラウドの柔軟性がもたらされます。ハイブリッド クラウドでは、 FabricPoolを使用して、高性能アレイから使用されていないデータ ブロックを優先ハイパースケーラー ( NetApp StorageGRIDなどのオンプレミスの S3 ストアなど) に階層化することでコストを節約できます。また、ソフトウェア定義のONTAP SelectまたはクラウドベースのDRを備えたエッジベースのシステムにもSnapMirrorを使用できます。 https://www.equinix.com/partners/netapp["Equinix Metal 上のNetAppストレージ"^]、またはその他のホストされたONTAPサービス。

その後、FlexCloneを使用すれば、ストレージの設置面積をほぼゼロに抑えながら、クラウドサービスプロバイダのデータセンター内でテストフェイルオーバーを実行できます。組織を保護することで、かつてないほどコストを削減できます。

VLSR は、 SnapMirror を使用して、計画的な移行を実行することもできます。これにより、 VM を 1 つのデータセンターから別のデータセンターに効率的に転送したり、独自のデータセンターや、任意の数のネットアップパートナーサービスプロバイダを介して VM を転送したりできます。
