---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: ONTAP for vSphereは、SANとNASを統合したストレージソリューションと、最新のオールSANアレイに搭載された新しいシンプルな分離型ストレージアーキテクチャにより、お客様が自信を持って選択できるようになります。このプラットフォームは、優れたスナップショット保護と堅牢な管理ツールを提供します。ONTAPは、機能を専用ストレージにオフロードすることで、ホストリソースを最大化し、コストを削減し、最適なパフォーマンスを維持します。また、Storage vMotionを使用して、VMFS、NFS、またはVVOL間でワークロードを簡単に移行できます。 
---
= ONTAP for VMware vSphereを選ぶ理由
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
お客様は、SANとNASの両方のストレージソリューションにONTAP for vSphereを確実に選択できます。最新のオールSANアレイに搭載された新しいシンプルな分離型ストレージアーキテクチャにより、SANストレージ管理者になじみのあるシンプルな操作性が提供され、従来のONTAPシステムのほとんどの統合と機能セットが維持されます。ONTAPシステムは、優れたスナップショット保護と堅牢な管理ツールを提供します。ONTAPは、機能を専用ストレージにオフロードすることで、ホストリソースを最大化し、コストを削減し、最適なパフォーマンスを維持します。また、Storage vMotionを使用して、VMFS、NFS、またはVVOL間でワークロードを簡単に移行できます。



== ONTAP for vSphereを使用するメリット

ONTAPをvSphereのストレージ解決策として選択した理由は数多くあります。たとえば、SANとNASの両方のプロトコルをサポートするユニファイドストレージシステム、スペース効率に優れたSnapshotを使用した堅牢なデータ保護機能、アプリケーションデータの管理に役立つ豊富なツールなどです。ハイパーバイザーとは別のストレージシステムを使用すると、さまざまな機能をオフロードして、 vSphere ホストシステムへの投資を最大限に活用できます。このアプローチにより、ホストリソースをアプリケーションワークロードに集中できるだけでなく、ストレージ運用によるアプリケーションのランダムなパフォーマンスへの影響も回避できます。

vSphere と ONTAP を併用すると、ホストハードウェアと VMware ソフトウェアのコストを削減できます。また、一貫した高パフォーマンスを維持しながら、低コストでデータを保護することもできます。仮想化されたワークロードはモバイル対応であるため、 Storage vMotion を使用して、 VMFS 、 NFS 、または VVOL データストア間で VM を移動するさまざまなアプローチを、すべて同じストレージシステム上で検討できます。

お客様が現在重視している主な要因は次のとおりです。

* *ユニファイドストレージ*ONTAPを実行するシステムは、いくつかの重要な方法で統合されています。当初、このアプローチは NAS プロトコルと SAN プロトコルの両方を指していましたが、 ONTAP は業界をリードする SAN プラットフォームであり続けており、 NAS における従来の強みもあります。vSphere 環境では、このアプローチは仮想デスクトップインフラ（ VDI ）向けのユニファイドシステムと仮想サーバインフラ（ VSI ）の組み合わせを意味する場合もあります。ONTAPを実行するシステムは、従来のエンタープライズアレイよりもVSIの方が一般的に安価であり、VDIを処理するための高度なStorage Efficiency機能を同じシステム内で備えています。また、 ONTAP は、 SSD から SATA までさまざまなストレージメディアを統合し、クラウドへの拡張を容易にします。パフォーマンスのためにストレージオペレーティングシステムを1つ、アーカイブ用にストレージオペレーティングシステムをもう1つ、クラウド用にストレージオペレーティングシステムを購入する必要はありません。ONTAP は、これらすべてを 1 つにまとめます。
* *オールSANアレイ（ASA）*最新のONTAP ASAシステム（A1K、A90、A70、A50、A30、A20以降）は、アグリゲートとボリュームの管理という従来のONTAPストレージのパラダイムを排除する新しいストレージアーキテクチャを基盤として構築されています。ファイルシステム共有がないため、ボリュームは必要ありません。HAペアに接続されたすべてのストレージは共通のStorage Availability Zone（SAZ；ストレージアベイラビリティゾーン）として扱われ、そのゾーン内でLUNおよびNVMeネームスペースが「Storage Unit」（SUS；ストレージユニット）としてプロビジョニングされます。最新のASAシステムは管理が容易になるように設計されており、SANストレージ管理者は使い慣れた環境を利用できます。この新しいアーキテクチャは、ストレージリソースの管理を容易にし、SANストレージ管理者の操作を簡易化できるため、vSphere環境に最適です。ASAアーキテクチャは最新のNVMe over Fabrics（NVMe-oF）テクノロジもサポートしているため、vSphereワークロードのパフォーマンスと拡張性がさらに向上します。
* * Snapshotテクノロジ。*ONTAPは、データ保護のためのスナップショットテクノロジを業界で初めて提供し、現在も業界で最も先進的なテクノロジです。スペース効率に優れたこのデータ保護アプローチは、VMware vSphere APIs for Array Integration（VAAI）をサポートするために拡張されました。この統合により、ONTAPのスナップショット機能をバックアップおよびリストア操作に活用し、本番環境への影響を軽減できます。このアプローチでは、スナップショットを使用してVMを迅速にリカバリできるため、データのリストアに必要な時間と労力が軽減されます。さらに、ONTAPのスナップショットテクノロジは、VMwareのライブサイトリカバリ（VLSR、旧Site Recovery Manager [SRM]）ソリューションと統合されており、仮想化環境に包括的なデータ保護戦略を提供します。
* *仮想ボリュームとストレージポリシーベースの管理*ネットアップは、 vSphere Virtual Volumes （ VVol ）の開発において VMware と初期の設計パートナーとして、アーキテクチャに関する情報提供と、 VVol および VMware vSphere APIs for Storage Awareness （ VASA ）のサポートを提供していました。このアプローチにより、VMFSでVMストレージをきめ細かく管理できるだけでなく、ストレージポリシーベースの管理によるストレージプロビジョニングの自動化もサポートされました。このアプローチにより、ストレージアーキテクトは、 VM 管理者が簡単に利用できるさまざまな機能を備えたストレージプールを設計できます。ONTAP は VVOL 規模でストレージ業界をリードし、 1 つのクラスタで数十万もの VVol をサポートします。一方、エンタープライズアレイや小規模なフラッシュアレイベンダーは、アレイあたり数千の VVol をサポートします。NetAppは、今後提供される機能できめ細かなVM管理の進化も推進しています。
* *ストレージ効率*NetAppは本番ワークロードに重複排除機能を初めて提供しましたが、このイノベーションはこの分野で初めてでも最後でもありませんでした。まず、パフォーマンスに影響を与えないスペース効率に優れたデータ保護メカニズムであるSnapshotと、本番環境およびバックアップ用にVMの読み取り/書き込みコピーを瞬時に作成するFlexCloneテクノロジから始まりました。ネットアップは、重複排除、圧縮、ゼロブロック重複排除などのインライン機能を提供し、高価な SSD のストレージを最後まで絞ります。ONTAPでは、コンパクションを使用して、小さなI/O処理やファイルをディスクブロックにまとめる機能も追加されました。これらの機能を組み合わせることで、VSIでは最大5：1、VDIでは最大30：1のコスト削減が実現しています。最新世代のONTAPシステムには、ハードウェアアクセラレーションによる圧縮と重複排除も含まれています。これにより、ストレージ効率がさらに向上し、コストが削減されます。このアプローチにより、より少ないスペースにより多くのデータを格納できるため、ストレージの全体的なコストが削減され、パフォーマンスが向上します。NetAppはStorage Efficiency機能に自信を持っており、https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [ストレージ容量削減保証^]へのリンクを提供しています。
* *マルチテナンシー*ONTAPは、長年にわたってマルチテナンシーの分野をリードしてきました。1つのクラスタに複数のStorage Virtual Machine（SVM）を作成できます。このアプローチでは、ワークロードを分離し、異なるテナントに異なるレベルのサービスを提供できるため、サービスプロバイダや大企業に最適です。最新世代のONTAPシステムには、テナント型の容量管理もサポートされています。この機能を使用すると、各テナントに容量制限を設定して、使用可能なすべてのリソースを単一のテナントが使用できないようにすることができます。このアプローチにより、すべてのテナントが期待どおりのサービスレベルを確実に受けられると同時に、高いレベルのセキュリティとテナント間の分離を実現できます。さらに、ONTAPのマルチテナンシー機能はVMwareのvSphereプラットフォームと統合されているため、および https://docs.netapp.com/us-en/data-infrastructure-insights/["データインフラの分析情報"]を使用して仮想環境を簡単に管理および監視でき https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["VMware vSphere 用の ONTAP ツール"]ます。
* * ハイブリッド・クラウド。 * オンプレミスのプライベート・クラウド、パブリック・クラウド・インフラストラクチャー、または両方の利点を組み合わせたハイブリッド・クラウドのいずれに使用しても、 ONTAP ソリューションはデータ管理を合理化し、最適化するためのデータ・ファブリックの構築を支援します。まずハイパフォーマンスのオールフラッシュシステムを導入し、データ保護とクラウドコンピューティングのためにディスクストレージシステムとクラウドストレージシステムのどちらかと組み合わせます。Azure 、 AWS 、 IBM 、 Google のクラウドから選択して、コストを最適化し、ロックインを回避できます。必要に応じて、 OpenStack とコンテナテクノロジの高度なサポートを活用できます。ネットアップ ONTAP では、クラウドベースのバックアップ（ SnapMirror クラウド、 Cloud Backup Service 、 Cloud Sync ）やストレージ階層化 / アーカイブツール（ FabricPool ）も提供しており、運用コストの削減とクラウドの幅広いリーチの活用を支援します。
* * その他。 * NetApp AFF A シリーズアレイの卓越したパフォーマンスを活用して、コストを管理しながら仮想インフラを高速化できます。スケールアウト ONTAP クラスタを使用して、ストレージシステムのメンテナンスからアップグレード、完全な交換まで、完全なノンストップオペレーションを実現します。ネットアップの暗号化機能を追加コストなしで使用して、保存データを保護できます。きめ細かいサービス品質機能により、パフォーマンスがビジネスサービスレベルを満たしていることを確認します。これらはすべて、業界をリードするエンタープライズデータ管理ソフトウェアであるONTAPに付属する幅広い機能の一部です。

