---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: ONTAP for vSphereは、SANとNASを統合したストレージソリューションと、最新のオールSANアレイに搭載された新しいシンプルな分離型ストレージアーキテクチャにより、お客様が自信を持って選択できるようになります。このプラットフォームは、優れたスナップショット保護と堅牢な管理ツールを提供します。ONTAPは、機能を専用ストレージにオフロードすることで、ホストリソースを最大化し、コストを削減し、最適なパフォーマンスを維持します。また、Storage vMotionを使用して、VMFS、NFS、またはVVOL間でワークロードを簡単に移行できます。 
---
= ONTAP for VMware vSphereを選ぶ理由
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
お客様は、SAN と NAS の両方のストレージ ソリューションとして、自信を持ってONTAP for vSphere を選択しています。最新の All SAN Arrays に搭載されている新しい簡素化された分散型ストレージ アーキテクチャは、従来のONTAPシステムの統合と機能セットのほとんどを維持しながら、SAN ストレージ管理者に馴染みのある簡素化されたエクスペリエンスを提供します。  ONTAPシステムは、優れたスナップショット保護と強力な管理ツールを提供します。 ONTAP は機能を専用ストレージにオフロードすることで、ホスト リソースを最大限に活用し、コストを削減し、最適なパフォーマンスを維持します。さらに、Storage vMotion を使用して、VMFS、NFS、またはvVols間でワークロードを簡単に移行できます。



== ONTAP for vSphereを使用するメリット

ONTAPをvSphereのストレージ解決策として選択した理由は数多くあります。たとえば、SANとNASの両方のプロトコルをサポートするユニファイドストレージシステム、スペース効率に優れたSnapshotを使用した堅牢なデータ保護機能、アプリケーションデータの管理に役立つ豊富なツールなどです。ハイパーバイザーとは別のストレージシステムを使用すると、さまざまな機能をオフロードして、 vSphere ホストシステムへの投資を最大限に活用できます。このアプローチにより、ホストリソースをアプリケーションワークロードに集中できるだけでなく、ストレージ運用によるアプリケーションのランダムなパフォーマンスへの影響も回避できます。

ONTAP をvSphere と併用すると、ホスト ハードウェアと VMware ソフトウェアの費用を削減できる優れた組み合わせになります。一貫した高いパフォーマンスを維持しながら、低コストでデータを保護することもできます。仮想化されたワークロードはモバイルであるため、Storage vMotion を使用して、同じストレージ システム上の VMFS、NFS、またはvVolsデータストア間で VM を移動するさまざまなアプローチを検討できます。

現在、顧客が重視する重要な要素は次のとおりです。

* *統合ストレージ* ONTAP を実行するシステムは、いくつかの重要な方法で統合されています。もともとこのアプローチは NAS プロトコルと SAN プロトコルの両方を指しており、 ONTAP はNAS における本来の強みとともに、SAN の主要プラットフォームであり続けています。  vSphere の世界では、このアプローチは、仮想デスクトップ インフラストラクチャ (VDI) と仮想サーバー インフラストラクチャ (VSI) を統合したシステムを意味することもあります。  ONTAP を実行するシステムは、通常、従来のエンタープライズ アレイよりも VSI が安価でありながら、同じシステムで VDI を処理できる高度なストレージ効率機能を備えています。 ONTAP は、SSD から SATA まで、さまざまなストレージ メディアを統合し、クラウドに簡単に拡張できます。パフォーマンス用にストレージ オペレーティング システムを購入したり、アーカイブ用に別のストレージ オペレーティング システムを購入したり、クラウド用にさらに別のストレージ オペレーティング システムを購入したりする必要はありません。  ONTAP はこれらすべてを結び付けます。
* *オールSANアレイ（ASA）*最新のONTAP ASAシステム（A1K、A90、A70、A50、A30、A20以降）は、アグリゲートとボリュームの管理という従来のONTAPストレージのパラダイムを排除する新しいストレージアーキテクチャを基盤として構築されています。ファイルシステム共有がないため、ボリュームは必要ありません。HAペアに接続されたすべてのストレージは共通のStorage Availability Zone（SAZ；ストレージアベイラビリティゾーン）として扱われ、そのゾーン内でLUNおよびNVMeネームスペースが「Storage Unit」（SUS；ストレージユニット）としてプロビジョニングされます。最新のASAシステムは管理が容易になるように設計されており、SANストレージ管理者は使い慣れた環境を利用できます。この新しいアーキテクチャは、ストレージリソースの管理を容易にし、SANストレージ管理者の操作を簡易化できるため、vSphere環境に最適です。ASAアーキテクチャは最新のNVMe over Fabrics（NVMe-oF）テクノロジもサポートしているため、vSphereワークロードのパフォーマンスと拡張性がさらに向上します。
* * Snapshotテクノロジ。*ONTAPは、データ保護のためのスナップショットテクノロジを業界で初めて提供し、現在も業界で最も先進的なテクノロジです。スペース効率に優れたこのデータ保護アプローチは、VMware vSphere APIs for Array Integration（VAAI）をサポートするために拡張されました。この統合により、ONTAPのスナップショット機能をバックアップおよびリストア操作に活用し、本番環境への影響を軽減できます。このアプローチでは、スナップショットを使用してVMを迅速にリカバリできるため、データのリストアに必要な時間と労力が軽減されます。さらに、ONTAPのスナップショットテクノロジは、VMwareのライブサイトリカバリ（VLSR、旧Site Recovery Manager [SRM]）ソリューションと統合されており、仮想化環境に包括的なデータ保護戦略を提供します。
* *仮想ボリュームとストレージのポリシーベースの管理。* NetApp は、vSphere Virtual Volumes (vVols) の開発において VMware の初期の設計パートナーであり、 vVolsと VMware vSphere APIs for Storage Awareness (VASA) に対するアーキテクチャ上のインプットと初期サポートを提供しました。このアプローチにより、VMFS にきめ細かな VM ストレージ管理がもたらされただけでなく、ストレージ ポリシー ベースの管理によるストレージ プロビジョニングの自動化もサポートされました。このアプローチにより、ストレージ アーキテクトは、VM 管理者が簡単に使用できるさまざまな機能を備えたストレージ プールを設計できます。  ONTAP はvVol スケールにおいてストレージ業界をリードしており、単一のクラスタで数十万のvVols をサポートしています。一方、エンタープライズ アレイや小規模フラッシュ アレイ ベンダーは、アレイあたりわずか数千のvVolsしかサポートしていません。  NetAppは、今後の機能により、きめ細かな VM 管理の進化も推進しています。
* *ストレージ効率。* NetApp は実稼働ワークロードの重複排除を初めて実現しましたが、このイノベーションはこの分野における最初でも最後でもありません。それは、パフォーマンスに影響を与えないスペース効率の高いデータ保護メカニズムであるスナップショットと、実稼働およびバックアップ用に VM の読み取り/書き込みコピーを即座に作成するFlexCloneテクノロジーから始まりました。  NetApp は、重複排除、圧縮、ゼロブロック重複排除などのインライン機能を提供し、高価な SSD から最大限のストレージ容量を絞り出しました。 ONTAP、圧縮を使用して、より小さな I/O 操作とファイルをディスク ブロックにパックする機能も追加されました。これらの機能の組み合わせにより、お客様は一般的に VSI で最大 5:1、VDI で最大 30:1 の節約を実現しています。最新世代のONTAPシステムには、ハードウェア アクセラレーションによる圧縮と重複排除も含まれており、これによりストレージ効率がさらに向上し、コストが削減されます。このアプローチにより、より少ないスペースに多くのデータを保存できるため、全体的なストレージコストが削減され、パフォーマンスが向上します。  NetAppはストレージ効率機能に非常に自信を持っているため、リンクを提供しています:https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [効率保証^]。
* *マルチテナント* ONTAP は長年マルチテナンシーのリーダーであり、単一のクラスタ上に複数のストレージ仮想マシン (SVM) を作成できます。このアプローチにより、ワークロードを分離し、テナントごとに異なるレベルのサービスを提供できるため、サービス プロバイダーや大企業に最適です。最新世代のONTAPシステムには、テナント容量管理のサポートも含まれています。この機能を使用すると、各テナントに容量制限を設定できるため、単一のテナントが利用可能なリソースをすべて消費することがなくなります。このアプローチにより、すべてのテナントが期待するレベルのサービスを確実に受けられるようになると同時に、テナント間の高度なセキュリティと分離も実現できます。さらに、ONTAPのマルチテナント機能はVMwareのvSphereプラットフォームと統合されており、仮想化環境を簡単に管理および監視できます。 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["VMware vSphere 用の ONTAP ツール"]そして https://docs.netapp.com/us-en/data-infrastructure-insights/["データインフラの分析情報"]。
* *ハイブリッドクラウド*オンプレミスのプライベート クラウド、パブリック クラウド インフラストラクチャ、またはその両方の長所を組み合わせたハイブリッド クラウドのいずれに使用する場合でも、 ONTAPソリューションはデータ ファブリックを構築してデータ管理を合理化し、最適化するのに役立ちます。高性能オールフラッシュ システムから始めて、データ保護とクラウド コンピューティングのためにディスク システムまたはクラウド ストレージ システムと組み合わせます。  Azure、AWS、IBM、Google Cloud からお選びいただくことで、コストを最適化し、ベンダーロックインを回避できます。必要に応じて、OpenStack とコンテナテクノロジーの高度なサポートを活用できます。  NetApp は、運用コストを削減し、クラウドの広範な範囲を活用できるように、 ONTAP向けのクラウドベースのバックアップ ( SnapMirror Cloud、 Cloud Backup Service、 Cloud Sync) とストレージ階層化およびアーカイブ ツール (FabricPool ) も提供しています。
* * その他。 * NetApp AFF A シリーズアレイの卓越したパフォーマンスを活用して、コストを管理しながら仮想インフラを高速化できます。スケールアウト ONTAP クラスタを使用して、ストレージシステムのメンテナンスからアップグレード、完全な交換まで、完全なノンストップオペレーションを実現します。ネットアップの暗号化機能を追加コストなしで使用して、保存データを保護できます。きめ細かいサービス品質機能により、パフォーマンスがビジネスサービスレベルを満たしていることを確認します。これらはすべて、業界をリードするエンタープライズデータ管理ソフトウェアであるONTAPに付属する幅広い機能の一部です。

