---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-datastores-top.html 
keywords: vSphere, datastore, VMFS, FC, NVMe/FC, NVMe/TCP, iSCSI, NFS, vVols 
summary: このページでは、VMware vSphere環境にONTAPストレージ解決策を実装するためのベストプラクティスについて説明します。 
---
= vSphereデータストアとプロトコルの機能の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware vSphereをONTAPを実行するシステム上のデータストアに接続するには、次の6つのプロトコルを使用します。

* FCP
* NVMe/FC
* NVMe/FC
* iSCSI
* NFS v3
* NFS v4.1


FCP、NVMe/FC、NVMe/TCP、およびiSCSIはブロックプロトコルで、vSphere Virtual Machine File System（VMFS）を使用して、ONTAP FlexVol volumeに含まれるONTAP LUNまたはNVMeネームスペースにVMを格納します。NFS はファイルプロトコルで、 VM をデータストア（ ONTAP ボリューム）に配置し、 VMFS を必要としません。SMB（CIFS）、iSCSI、NVMe/FC、NFSもゲストOSからONTAP に直接使用できます。

次の表は、ONTAPでサポートされるvSphereの従来のデータストア機能を示しています。この情報はvVolsデータストアには適用されませんが、サポートされるONTAPリリースを使用するvSphere 6.x以降のリリースには一般的に適用されます。link:https://configmax.broadcom.com/guest?vmwareproduct=vSphere&release=vSphere%208.0&categories=2-0["VMware Configuration Maximumsツール"^]を参照して、特定のvSphereリリースの具体的な制限を確認することもできます。

|===
| 機能 / 特徴 | FC | iSCSI | NVMe-oF | NFS 


| の形式で入力し | VMFS または raw デバイスマッピング（ RDM ） | VMFS または RDM | VMFS | N/A 


| データストアまたは LUN の最大数 | ESXiホストあたり1024個のLUN、LUNあたり最大32個のパス、ホストあたり最大4096個のパス、データストアあたり最大128個のホスト | ESXiホストあたり1024個のLUN、LUNあたり最大32個のパス、ホストあたり最大4096個のパス、データストアあたり最大128個のホスト | ESXiホストあたり256の名前空間、ホストあたりの名前空間あたり最大32のパス、ホストあたり合計2048のパス、データストアあたり最大16のホスト | ホストあたり256のNFS接続（nconnectとセッショントランキングの影響を受ける）、デフォルトのNFS。MaxVolumes は 8 です。VMware vSphere 用の ONTAP ツールを使用して 256 まで増やす。 


| データストアの最大サイズ | 64TB | 64TB | 64TB | 300TB 以上の FlexVol ボリュームと FlexGroup ボリューム 


| データストアの最大ファイルサイズ | 62TB | 62TB | 62TB | 62TB（ONTAP 9.12.1P2以降使用時） 


| LUN またはファイルシステムごとのキューの深さの最適値 | 64 ~ 256 | 64 ~ 256 | 自動ネゴシエーション | のNFS.MaxQueueDepthを参照してください link:vmware-vsphere-settings.html["推奨される ESXi ホストとその他の ONTAP 設定"^]。 
|===
次の表に、サポートされる VMware ストレージ関連機能を示します。

|===
| 容量 / 機能 | FC | iSCSI | NVMe-oF | NFS 


| vMotion | はい。 | はい。 | はい。 | はい。 


| Storage vMotion の機能です | はい。 | はい。 | はい。 | はい。 


| VMware HA | はい。 | はい。 | はい。 | はい。 


| ストレージ分散リソーススケジューラ（ SDRS ） | はい。 | はい。 | はい。 | はい。 


| VMware vStorage APIs for Data Protection（VADP）対応のバックアップソフトウェア | はい。 | はい。 | はい。 | はい。 


| VM 内の Microsoft Cluster Service （ MSCS ）またはフェイルオーバークラスタリング | はい。 | はい^1^ | はい^1^ | サポート対象外 


| フォールトトレランス | はい。 | はい。 | はい。 | はい。 


| ライブサイトリカバリ/サイトリカバリマネージャ | はい。 | はい。 | いいえ^2^ | v3のみ^2^ 


| シンプロビジョニングされた VM （仮想ディスク） | はい。 | はい。 | はい。 | はい。
VAAIを使用しない場合、NFS上のすべてのVMに対してこの設定がデフォルトになります。 


| VMware 標準マルチパス | はい。 | はい。 | はい。 | NFS v4.1セッショントランキングにはONTAP 9.14.1以降が必要 
|===
次の表に、サポートされる ONTAP ストレージ管理機能を示します。

|===
| 機能 / 特徴 | FC | iSCSI | NVMe-oF | NFS 


| データ重複排除 | アレイ内での容量削減 | アレイ内での容量削減 | アレイ内での容量削減 | データストア内での容量削減 


| シンプロビジョニング | データストアまたは RDM | データストアまたは RDM | データストア | データストア 


| データストアのサイズを変更 | 拡張のみ | 拡張のみ | 拡張のみ | 拡張、自動拡張、縮小 


| Windows 、 Linux アプリケーション用の SnapCenter プラグイン（ゲスト内） | はい。 | はい。 | はい。 | はい。 


| VMware vSphere 用の ONTAP ツールを使用した監視とホストの設定 | はい。 | はい。 | はい。 | はい。 


| VMware vSphere 用の ONTAP ツールを使用したプロビジョニング | はい。 | はい。 | はい。 | はい。 
|===
次の表に、サポートされるバックアップ機能を示します。

|===
| 機能 / 特徴 | FC | iSCSI | NVMe-oF | NFS 


| ONTAPノSnapshot | はい。 | はい。 | はい。 | はい。 


| 複製バックアップでサポートされる SRM | はい。 | はい。 | いいえ^2^ | v3のみ^2^ 


| Volume SnapMirror の略 | はい。 | はい。 | はい。 | はい。 


| VMDK イメージアクセス | SnapCenterおよびVADP対応のバックアップソフトウェア | SnapCenterおよびVADP対応のバックアップソフトウェア | SnapCenterおよびVADP対応のバックアップソフトウェア | SnapCenterおよびVADP対応のバックアップソフトウェア、vSphere Client、vSphere Web Clientデータストアブラウザ 


| VMDK のファイルレベルアクセス | SnapCenterおよびVADP対応のバックアップソフトウェア、Windowsのみ | SnapCenterおよびVADP対応のバックアップソフトウェア、Windowsのみ | SnapCenterおよびVADP対応のバックアップソフトウェア、Windowsのみ | SnapCenterおよびVADP対応のバックアップソフトウェアとサードパーティ製アプリケーション 


| NDMP の単位 | データストア | データストア | データストア | データストアまたはVM 
|===
^1^ *NetAppの推奨事項*：VMFSデータストア内のマルチライター対応VMDKではなく、Microsoftクラスタ用のゲスト内iSCSIを使用してください。このアプローチはMicrosoftとVMwareによって完全にサポートされており、ONTAP（オンプレミスまたはクラウドのONTAPシステムへのSnapMirror）で優れた柔軟性を提供し、設定と自動化が容易で、SnapCenterで保護できます。vSphere 7では、新しいクラスタ化されたVMDKオプションが追加されました。これは、クラスタ化されたVMDKサポートが有効になっているVMFS 6データストアを必要とする、マルチライター対応VMDKとは異なります。その他の制限事項が適用されます。設定ガイドラインについては、VMwareのlink:https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/setup-for-windows-server-failover-clustering.html["Windows Server フェールオーバークラスタリングのセットアップ"^]ドキュメントを参照してください。

^2^NVMe-oFおよびNFS v4.1を使用するデータストアでは、vSphereレプリケーションが必要です。NFS v4.1のアレイベースのレプリケーションは、現在SRMでサポートされていません。NVMe-oFを使用したアレイベースのレプリケーションは、現在ONTAP tools for VMware vSphere Storage Replication Adapter（SRA）ではサポートされていません。



== ストレージプロトコルを選択

ONTAPを実行しているシステムは、すべての主要なストレージプロトコルをサポートしているため、既存および計画中のネットワークインフラストラクチャとスタッフのスキルに応じて、お客様は環境に最適なものを選択できます。歴史的に、NetAppのテストでは、一般的に、同様の回線速度と接続数で実行されるプロトコル間にほとんど違いがないことが示されています。しかし、NVMe-oF（NVMe/TCPおよびNVMe/FC）は、IOPSの顕著な向上、レイテンシの削減、そしてストレージIOによるホストCPU消費の最大50％以上の削減を実現しています。一方、NFSは、特に多数のVMの場合に、最大限の柔軟性と管理の容易さを提供します。これらのプロトコルはすべて、ONTAP tools for VMware vSphereで使用および管理でき、データストアを作成および管理するためのシンプルなインターフェースを提供します。

プロトコルの選択を検討する際には、次の要素が役立ちます。

* *現在の動作環境*一般に、ITチームはイーサネットIPインフラの管理に精通していますが、FC SANファブリックの管理に精通しているわけではありません。ただし、ストレージトラフィック用に設計されていない汎用IPネットワークを使用すると、うまく機能しない場合があります。現在利用しているネットワークインフラストラクチャ、計画的な改善点、およびそれらを管理するためのスタッフのスキルと可用性を考慮します。
* * セットアップの容易さ * FC ファブリックの初期構成（追加のスイッチとケーブル配線、ゾーニング、 HBA とファームウェアの相互運用性の検証）に加えて、ブロックプロトコルを使用するには、 LUN の作成とマッピング、ゲスト OS による検出とフォーマットも必要です。作成およびエクスポートされた NFS ボリュームは、 ESXi ホストによってマウントされ、使用可能な状態になります。NFS では、ハードウェアの認定や管理に関する特別なファームウェアはありません。
* *管理のしやすさ*SANプロトコルでは、より多くのスペースが必要な場合、LUNの拡張、新しいサイズを検出するための再スキャン、ファイルシステムの拡張など、いくつかの手順が必要になります。LUNを拡張することは可能ですが、LUNのサイズを縮小することはできません。NFSではサイズを簡単に拡大または縮小することができ、このサイズ変更はストレージシステムによって自動化できます。SANは、ゲストOSのDEALLOCATE/TRIM/UNMAPコマンドを通じてスペースの再利用を提供し、削除されたファイルのスペースをアレイに戻すことを可能にします。このタイプのスペース再利用はNFSデータストアでは不可能です。
* * ストレージスペースの透過性。 * シンプロビジョニングによって削減効果が即座に現れるため、 NFS 環境では一般にストレージ利用率が見やすくなります。同様に、重複排除とクローニングによる削減効果は、同じデータストア内の他の VM や他のストレージシステムボリュームで即座に利用できます。一般に、 VM の密度は NFS データストア内でも高くなります。管理するデータストアが少ないため、重複排除による削減効果が向上すると同時に管理コストも削減されます。




== データストアのレイアウト

ONTAP ストレージシステムは、 VM および仮想ディスク用のデータストアを柔軟に作成できます。ONTAPツールを使用してvSphere（の項を参照link:vmware-vsphere-settings.html["推奨される ESXi ホストとその他の ONTAP 設定"]）にデータストアをプロビジョニングする場合は、多くのONTAPのベストプラクティスが適用されますが、次のガイドラインも考慮する必要があります。

* vSphereをONTAP NFSデータストアとともに導入すると、ブロックベースのストレージプロトコルでは実現できないVMとデータストアの比率を実現する、高性能で管理しやすい実装が可能になります。このアーキテクチャにより、データストアの密度が10倍に増加し、それに応じてデータストアの数が削減されます。データストアを大きくするとストレージ効率が向上し、運用上のメリットも得られますが、ハードウェアリソースから最大のパフォーマンスを引き出すために、単一のONTAPコントローラにVMを格納する場合は、ノードごとに少なくとも4つのデータストア（FlexVolボリューム）を使用することを検討してください。このアプローチにより、異なるリカバリポリシーを持つデータストアを確立することもできます。ビジネスニーズに基づいて、一部のデータストアは他のデータストアよりも頻繁にバックアップまたはレプリケートできます。FlexGroupボリュームは設計上スケールするため、パフォーマンスのために複数のデータストアは必要ありません。
* *NetApp は* ほとんどのNFSデータストアに対して FlexVol ボリュームの使用を推奨しています。ONTAP 9.8以降では、FlexGroup ボリュームもデータストアとしてサポートされており、特定のユースケースで一般的に推奨されています。qtreeなどの他のONTAPストレージコンテナは、ONTAP tools for VMware vSphere や NetApp SnapCenter プラグイン for VMware vSphere で現在サポートされていないため、一般的には推奨されません。
* FlexVol ボリュームデータストアの適切なサイズは 4~8TB です。このサイズは、パフォーマンス、管理のしやすさ、データ保護のバランスが取れた適切なサイズです。小規模構成から開始して（ 4TB など）、必要に応じてデータストアを拡張します（最大 300TB まで）。小規模なデータストアは、バックアップや災害からのリカバリにかかる時間が短く、クラスタ間で迅速に移動できます。使用済みスペースの変化に応じてボリュームを自動的に拡張または縮小するには、 ONTAP のオートサイズを使用することを検討してください。ONTAP tools for VMware vSphereデータストアプロビジョニングウィザードでは、新しいデータストアに対してデフォルトでオートサイズが使用されます。拡張および縮小のしきい値と最大および最小サイズは、 System Manager またはコマンドラインを使用して追加でカスタマイズできます。
* また、VMFSデータストアには、FC、iSCSI、NVMe/FC、NVMe/TCPからアクセスするLUNまたはNVMeネームスペース（新しいASAシステムではストレージユニットと呼ばれます）を設定することもできます。VMFSを使用すると、クラスタ内のすべてのESXサーバから同時にデータストアにアクセスできます。VMFS データストアは、最大 64TB まで拡張でき、最大 32 個の 2TB LUN （ VMFS 3 ）または単一の 64TB LUN （ VMFS 5 ）で構成できます。ONTAPの最大LUNサイズは、AFF、ASA、およびFASシステムで128TBです。NetAppでは、エクステントを使用するのではなく、データストアごとに大容量のLUNを1つ使用することを常に推奨しています。NFSの場合と同様に、複数のデータストア（ボリュームまたはストレージユニット）を使用して、1台のONTAPコントローラのパフォーマンスを最大化することを検討してください。
* 古いゲストオペレーティングシステム（ OS ）では、パフォーマンスとストレージ効率を最大化するために、ストレージシステムとのアライメントが必要でした。しかし、 Microsoft や Linux ディストリビュータ（ Red Hat など）が提供する、ベンダーがサポートする最新の OS では、ファイルシステムのパーティションを仮想環境の基盤となるストレージシステムのブロックにアライメントするように調整する必要はありません。アライメントが必要な古いOSを使用している場合は、NetAppサポートナレッジベースで「VMアライメント」と記載された記事を検索するか、NetAppの営業担当者またはパートナー担当者にTR-3747のコピーをリクエストしてください。
* デフラグユーティリティはゲストOS内では使用しないでください。パフォーマンス上のメリットはなく、ストレージ効率とスナップショット容量の使用にも影響します。また、仮想デスクトップのゲスト OS で検索インデックスを無効にすることを検討してください。
* ONTAP は、革新的な Storage Efficiency 機能で業界をリードし、使用可能なディスクスペースを最大限に活用できるようにしています。AFF システムでは、デフォルトのインライン重複排除機能と圧縮機能により、この効率性がさらに向上しています。データはアグリゲート内のすべてのボリュームにわたって重複排除されるため、類似するオペレーティングシステムやアプリケーションを 1 つのデータストア内にまとめて、最大限の削減効果を得る必要はありません。
* 場合によっては、データストアが不要なこともあります。ゲストが所有するファイルシステム（ゲストが管理するNFS、SMB、NVMe/TCP、iSCSIのファイルシステムなど）を検討します。アプリケーションに関する具体的なガイダンスについては、ご使用のアプリケーションに関するネットアップのテクニカルレポートを参照してください。たとえば、にlink:../oracle/oracle-overview.html["ONTAP を基盤にした Oracle データベース"]は仮想化に関するセクションがあり、役立つ詳細情報が記載されています。
* 第 1 クラスのディスク（または強化された仮想ディスク）を使用すると、 vSphere 6.5 以降を搭載した VM に関係なく、 vCenter で管理されるディスクを使用できます。主に API で管理されますが、 VVol では特に OpenStack ツールや Kubernetes ツールで管理する場合に便利です。ONTAP および VMware vSphere 用の ONTAP ツールでサポートされています。




== データストアと VM 移行

別のストレージシステム上の既存のデータストアから ONTAP に VM を移行する際は、いくつか注意しておくべきプラクティスがあります。

* Storage vMotion を使用して、仮想マシンの大部分を ONTAP に移動します。このアプローチでは、実行中の VM を停止する必要がなくなるだけでなく、インラインの重複排除や圧縮などの ONTAP の Storage Efficiency 機能を使用して、移行時にデータを処理できます。vCenter 機能を使用してインベントリリストから複数の VM を選択し、適切なタイミングで移行をスケジュール（ Ctrl キーを押しながら [ アクション ] をクリック）することを検討します。
* 適切な宛先データストアへの移行を慎重に計画することもできますが、一括して移行し、後で必要に応じて整理する方が簡単な場合がよくあります。異なるSnapshotスケジュールなど、特定のデータ保護のニーズがある場合は、このアプローチを使用して、異なるデータストアへの移行をガイドすることができます。さらに、VMがNetAppクラスタ上にある場合、ストレージvMotionはVAAIオフロードを使用して、ホストベースのコピーを必要とせずに、クラスタ上のデータストア間でVMを移動できます。NFSは電源がオンになっているVMのストレージvMotionをオフロードしないことに注意してください。ただし、VMFSはオフロードします。
* より慎重な移行が必要な仮想マシンには、接続されたストレージを使用するデータベースやアプリケーションなどがあります。一般的に、移行を管理するためにアプリケーションのツールを使用することを検討してください。Oracle の場合は、 RMAN や ASM などの Oracle ツールを使用してデータベース・ファイルを移行することを検討してください。詳細については、を参照してください https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-migration-overview.html["ONTAPストレージシステムへのOracleデータベースの移行"^] 。同様に、 SQL Server の場合は、 SQL Server Management Studio を使用するか、 SnapManager for SQL Server や SnapCenter などのネットアップのツールを使用することを検討します。




== VMware vSphere 用の ONTAP ツール

ONTAPを実行しているシステムでvSphereを使用する際の最も重要なベストプラクティスは、ONTAP tools for VMware vSphereプラグイン（以前はVirtual Storage Consoleとして知られていました）をインストールして使用することです。このvCenterプラグインは、ストレージ管理を簡素化し、可用性を向上させ、ストレージコストと運用上のオーバーヘッドを削減します。SANまたはNAS、ASA、AFF、FAS、さらにはONTAP Select（VMwareまたはKVMのVM上で動作するソフトウェアで定義されるONTAPバージョン）を使用している場合でも同様です。このプラグインは、データストアのプロビジョニングに関するベストプラクティスを使用し、マルチパスおよびHBAタイムアウトのためにESXiホスト設定を最適化します（これらは付録Bで説明されています）。これはvCenterプラグインであるため、vCenterサーバーに接続するすべてのvSphereウェブクライアントで利用できます。

このプラグインは、 vSphere 環境で他の ONTAP ツールを使用する場合にも役立ちます。NFS Plug-in for VMware VAAIをインストールできます。これにより、VMのクローニング処理、シック仮想ディスクファイルのスペースリザベーション、ONTAPスナップショットのオフロードのために、ONTAPへのコピーオフロードが可能になります。


NOTE: 画像ベースのvSphereクラスタでは、ONTAP tools でインストールする際にコンプライアンス違反にならないように、NFS プラグインをイメージに追加する必要があります。

ONTAPツールは、VASA Provider for ONTAPの多くの機能の管理インターフェイスでもあり、VVOLを使用したポリシーベースのストレージ管理をサポートします。

一般に、* NetAppでは* vCenter内でONTAP Tools for VMware vSphereインターフェイスを使用して従来のデータストアとVVOLデータストアをプロビジョニングし、ベストプラクティスに従うことを推奨*しています。



== 一般的なネットワーク

vSphereとONTAPを実行しているシステムを使用する場合のネットワーク設定の構成は簡単で、他のネットワーク構成と同様です。考慮すべき事項は次のとおりです：

* ストレージネットワークのトラフィックを他のネットワークから分離します。専用の VLAN を使用するか、ストレージ用に別個のスイッチを使用することで、別のネットワークを実現できます。ストレージネットワークがアップリンクなどの物理パスを共有している場合は、十分な帯域幅を確保するために QoS または追加のアップリンクポートが必要になることがあります。ホストをストレージに直接接続しないでください。スイッチを使用して冗長パスを確保し、VMware HAが介入なしで機能できるようにします。を参照してください link:vmware-vsphere-network.html["直接接続ネットワーク"] 追加情報 の場合。
* ジャンボフレームは、必要に応じてネットワークでサポートされていれば、特に iSCSI を使用している場合に使用できます。使用する場合は、ストレージと ESXi ホストの間のパスにあるすべてのネットワークデバイスや VLAN で設定が同じであることを確認してください。そうしないと、パフォーマンスや接続の問題が発生する可能性があります。MTU は、 ESXi 仮想スイッチ、 VMkernel ポート、および各 ONTAP ノードの物理ポートまたはインターフェイスグループでも同一の設定にする必要があります。
* NetAppでは、ONTAPクラスタ内のクラスタインターコネクトポートでのみネットワークフロー制御を無効にすることを推奨しています。データトラフィックに使用される残りのネットワークポートについては、推奨されるベストプラクティスはありません。必要に応じて有効または無効にしてください。フロー制御の詳細については、を参照してください https://www.netapp.com/pdf.html?item=/media/16885-tr-4182pdf.pdf["TR-4182"^]。
* ESXiおよびONTAPストレージアレイをイーサネットストレージネットワークに接続する場合は、NetApp接続先のイーサネットポートをRapid Spanning Tree Protocol（RSTP;高速スパニングツリープロトコル）エッジポートとして設定するか、Cisco PortFast機能を使用して設定することを推奨します。* NetAppでは、Cisco PortFast機能を使用し、ESXiサーバまたはONTAPストレージアレイへの802.1Q VLANトランキングが有効になっている環境で、スパニングツリーPortFastトランク機能を有効にすることを推奨*しています。
* * NetAppでは*リンクアグリゲーションに次のベストプラクティスを推奨しています。
+
** マルチシャーシリンクアグリゲーショングループアプローチを使用して、2つの別々のスイッチシャーシ上のポートのリンクアグリゲーションをサポートするスイッチを使用します（Ciscoの Virtual PortChannel（vPC）など）。
** LACPが設定されたdvSwitches 5.1以降を使用していない場合、ESXiに接続されているスイッチポートのLACPを無効にします。
** LACPを使用して、ポートハッシュまたはIPハッシュを使用したダイナミックマルチモードインターフェイスグループを使用するONTAPストレージシステムのリンクアグリゲートを作成します。を参照してください https://docs.netapp.com/us-en/ontap/networking/combine_physical_ports_to_create_interface_groups.html#dynamic-multimode-interface-group["Network Management の略"^] を参照してください。
** ESXiで静的リンクアグリゲーション（EtherChannelなど）と標準vSwitchを使用する場合、またはvSphere Distributed Switchを使用するLACPベースのリンクアグリゲーションを使用する場合は、IPハッシュチーミングポリシーを使用します。リンクアグリゲーションを使用しない場合は、代わりに[Route based on the originating virtual port ID]を使用します。



