---
sidebar: sidebar 
permalink: vmware/vmware-vvols-resources.html 
keywords: tr-4400, vvols, ontap, virtual volumes, protect 
summary: VVOLに関するその他のリソース 
---
= トラブルシューティング
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
追加情報 には、いくつかのトラブルシューティングリソースが用意されています。



== NetApp Support Site

NetAppサポートサイトでは、NetApp仮想化製品に関するさまざまなナレッジベース記事に加えて、製品の便利なランディングページも提供して https://mysupport.netapp.com/site/products/all/details/otv/docs-tab["VMware vSphere 用の ONTAP ツール"]います。このポータルには、ネットアップコミュニティの記事、ダウンロード、テクニカルレポート、VMwareソリューションに関するディスカッションへのリンクが掲載されています。次のURLから入手できます。

https://mysupport.netapp.com/site/products/all/details/otv/docs-tab["_ NetApp Support Site _"]

その他の解決策 ドキュメントは、次のURLから入手できます。

https://docs.netapp.com/us-en/netapp-solutions/vmware/index.html["_BroadcomによるVMwareによる仮想化向けNetAppソリューション_"]



== 製品のトラブルシューティング

vCenterプラグイン、VASA Provider、Storage Replication Adapterなど、ONTAP ツールのさまざまなコンポーネントは、いずれもネットアップのドキュメントリポジトリにまとめられています。ただし、それぞれにKnowledge Baseのサブセクションがあり、特定のトラブルシューティング手順が記載されている場合があります。これらは、VASA Providerで発生する可能性のある最も一般的な問題に対処します。



=== VASA ProviderのUIの問題

vCenter vSphere Web ClientでSerenityのコンポーネントに関する問題が発生し、VASA Provider for ONTAP のメニュー項目が表示されないことがあります。導入ガイドまたはこのナレッジベースのVASA Provider登録の問題の解決を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/VSC_and_VASA_Provider/How_to_resolve_display_issues_with_the_vSphere_Web_Client["記事"]。



=== vVolデータストアのプロビジョニングが失敗する

vVolデータストアの作成時にvCenterサービスがタイムアウトすることがあります。修正するには、vmware-spsサービスを再起動し、vCenterのメニュー（[Storage]>[New Datastore]）を使用してvVolデータストアを再マウントします。この問題については、『Administration Guide』のvCenter Server 6.5でvVolデータストアのプロビジョニングが失敗するという項を参照してください。



=== Unified Applianceをアップグレードすると、ISOのマウントに失敗します

vCenterのバグが原因で、Unified Applianceをあるリリースから次のリリースへアップグレードするために使用されるISOがマウントに失敗する可能性があります。ISOをvCenterのアプライアンスに接続できる場合は、このナレッジベースの手順に従ってください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/VSC_and_VASA_Provider/Virtual_Storage_Console_(VSC)%3A_Upgrading_VSC_appliance_fails_%22failed_to_mount_ISO%22["記事"] 解決するために。
