---
sidebar: sidebar 
permalink: vmware/vmware-srm-overview.html 
keywords: ontap, vsphere, srm, srm, hybrid, cloud, migration, vmware, site, recovery manager, vsrm,VLSR 
summary: VMware Live Site Recovery（VLSR）およびSite Recovery Manager（SRM）向けのONTAPソリューション 
---
= ONTAPを使用したVMwareライブサイトリカバリ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAPは、2002年に最新のデータセンターに導入されて以来、VMware vSphereおよび最近ではCloud Foundation環境向けの主要なストレージソリューションとして機能してきました。管理を簡易化し、コストを削減する革新的な機能を継続的に導入しています。

このドキュメントでは、VMwareの業界をリードするディザスタリカバリ（DR）ソフトウェアであるVMware Live Site Recovery（VLSR）向けONTAPソリューションについて説明します。これには、導入の合理化、リスクの軽減、継続的な管理の簡素化を実現する最新の製品情報やベストプラクティスが含まれます。


NOTE: このドキュメントは、以前に公開されていたテクニカルレポート「TR-4900：VMware Site Recovery Manager」をONTAPに置き換えます。

ベストプラクティスは、ガイドや互換性ツールなどの他のドキュメントを補うものです。ラボテストに基づいて開発されており、ネットアップのエンジニアやお客様は広範な現場経験を積んでいます。推奨されるベストプラクティスがお客様の環境に適していない場合もありますが、一般に最もシンプルなソリューションであり、ほとんどのお客様のニーズに対応できます。

本ドキュメントでは、ONTAP tools for VMware vSphere 10.4（NetApp Storage Replication Adapter[SRA]およびVASA Provider[VP]を含む）およびVMware Live Site Recovery 9と組み合わせて使用した場合のONTAP 9の最近のリリースの機能について説明します。



== VLSRまたはSRMでONTAPを使用する理由

ONTAPを基盤とするNetAppデータ管理プラットフォームは、VLSRに最も広く採用されているストレージソリューションの一部です。理由はそれだけではありません。セキュアでハイパフォーマンスなユニファイドプロトコル（NASとSANを併用）データ管理プラットフォームで、業界を定義するストレージ効率、マルチテナンシー、サービス品質管理、スペース効率に優れたSnapshotによるデータ保護、SnapMirrorによるレプリケーションを実現します。VMware ワークロードを保護するためにネイティブのハイブリッドマルチクラウド統合を活用し、多数の自動化ツールやオーケストレーションツールを簡単に利用できます。

SnapMirrorをアレイベースのレプリケーションに使用すると、実績のある成熟したONTAPのテクノロジを活用できます。SnapMirror を使用すると、 VM やデータストア全体ではなく、変更されたファイルシステムブロックのみをコピーして、データを安全かつ効率的に転送できます。重複排除、圧縮、コンパクションなどのスペース削減効果を活用できます。最新の ONTAP システムで、バージョンに依存しない SnapMirror が使用されるようになり、ソースとデスティネーションのクラスタを柔軟に選択できるようになりました。SnapMirror は、災害復旧のための最も強力なツールの 1 つとなりました。

従来の NFS 、 iSCSI 、ファイバチャネル接続データストア（現在は VVOL データストアをサポート）のいずれを使用している場合でも、 VLSR は、ディザスタリカバリやデータセンター移行の計画とオーケストレーションに ONTAP の機能のメリットを活用する堅牢なファーストパーティ製品を提供します。



== VLSR での ONTAP 9 の活用方法

VLSR は、 ONTAP システムの高度なデータ管理テクノロジを活用して、 3 つの主要コンポーネントで構成される仮想アプライアンスである VMware vSphere 用 ONTAP ツールと統合します。

* ONTAP tools vCenterプラグイン（旧称Virtual Storage Console（VSC））は、SANとNASのどちらを使用している場合でも、ストレージ管理と効率化機能を簡易化し、可用性を高め、ストレージコストと運用オーバーヘッドを削減します。データストアのプロビジョニングのベストプラクティスを使用して、 NFS 環境およびブロックストレージ環境用の ESXi ホスト設定を最適化します。NetAppでは、ONTAPを実行しているシステムでvSphereを使用する際に、これらのメリットをすべて考慮してこのプラグインを推奨しています。
* ONTAP tools VASA Providerは、VMware vStorage APIs for Storage Awareness（VASA）フレームワークをサポートします。VASA Provider では、 VM ストレージのプロビジョニングと監視に役立つように vCenter Server と ONTAP を接続します。これにより、VMware Virtual Volumes（vVol）のサポート、VMストレージポリシーの管理、および個 々 のVM vVolのパフォーマンスの管理が可能になりました。また、容量の監視やプロファイルへの準拠に関するアラームも生成されます。
* SRA は VLSR と一緒に使用され、従来の VMFS データストアと NFS データストアの本番サイトとディザスタリカバリサイト間での VM データのレプリケーションを管理します。また、 DR レプリカの無停止テストにも使用できます。検出、リカバリ、再保護のタスクを自動化します。SRAサーバアプライアンスと、Windows SRMサーバおよびVLSRアプライアンス用のSRAアダプタの両方が含まれています。


vVol以外のデータストアを保護するためにVLSRサーバにSRAアダプタをインストールして設定したら、ディザスタリカバリ用にvSphere環境を設定するタスクを開始できます。

SRAは、VMware仮想マシン（VM）を含むONTAP FlexVolボリュームおよびそれらを保護するSnapMirrorレプリケーションを管理するためのVLSRサーバ用のコマンドおよび制御インターフェイスを提供します。

VLSRでは、ネットアップ独自のFlexCloneテクノロジを使用して、システムを停止することなくDR計画をテストし、保護されたデータストアのクローンをDRサイトにほぼ瞬時に作成できます。VLSR はサンドボックスを作成して安全にテストし、真の災害が発生した場合に組織とお客様を保護します。そのため、組織は災害時にフェイルオーバーを実行できます。

実際に災害が発生した場合や、計画的な移行の場合でも、 VLSR では、最終的な SnapMirror 更新（必要な場合）を使用して、データセットに最新の変更を送信できます。その後、ミラーを解除し、 DR ホストにデータストアをマウントします。この時点で、計画済みの戦略に基づいて、 VM の電源を任意の順序で自動的にオンにすることができます。


NOTE: ONTAPシステムではSnapMirrorレプリケーション用に同じクラスタ内のSVMをペアリングできますが、このシナリオのテストおよび認定はVLSRでは行われていません。したがって、VLSRを使用する場合は、異なるクラスタのSVMのみを使用することを推奨します。



== VLSR と ONTAP などのユースケース：ハイブリッドクラウドと移行

VLSR 環境に ONTAP の高度なデータ管理機能を統合することで、ローカルストレージオプションに比べて、拡張性とパフォーマンスが大幅に向上します。それだけではありませんが、ハイブリッドクラウドの柔軟性を備えています。ハイブリッドクラウドを使用すると、 FabricPool を使用して、未使用のデータブロックをハイパフォーマンスアレイから希望するハイパースケーラに階層化してコストを削減できます。これは、 NetApp StorageGRID などのオンプレミスの S3 ストアである可能性があります。SnapMirrorは、ソフトウェアで定義されるONTAP Selectを備えたエッジベースのシステムや、Cloud Volumes ONTAP（CVO）やその他のホスト型ONTAPサービスを使用したクラウドベースのDRにも使用できます https://www.equinix.com/partners/netapp["Equinix Metal®上のNetAppストレージ"^]。

その後、FlexCloneを使用すれば、ストレージの設置面積をほぼゼロに抑えながら、クラウドサービスプロバイダのデータセンター内でテストフェイルオーバーを実行できます。組織を保護することで、かつてないほどコストを削減できます。

VLSR は、 SnapMirror を使用して、計画的な移行を実行することもできます。これにより、 VM を 1 つのデータセンターから別のデータセンターに効率的に転送したり、独自のデータセンターや、任意の数のネットアップパートナーサービスプロバイダを介して VM を転送したりできます。
