---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-vvols_and_spbm.html 
keywords: vSphere, vVols, virtual volumes, SPBM, storage police based management, ONTAP 
summary: このページでは、VMware vSphere環境にONTAPストレージ解決策を実装するためのベストプラクティスについて説明します。 
---
= Virtual Volumes （ VVol ）と Storage Policy Based Management （ SPBM ）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
2012年に最初に発表されたNetAppは、VMware vSphere APIs for Storage Awareness（VASA）の開発におけるVMwareの初期の設計パートナーであり、エンタープライズストレージアレイを使用するストレージポリシーベース管理（SPBM）の基盤となっています。このアプローチにより、VMFSおよびNFSストレージでVMのきめ細かなストレージ管理が制限されました。

テクノロジ設計パートナーとして、NetAppはアーキテクチャに関する情報を提供し、2015年にVVOLのサポートを発表しました。この新しいテクノロジにより、SPBMを使用してVM単位で真にアレイネイティブなストレージプロビジョニングを自動化できるようになりました。



== 仮想ボリューム（VVol）

VVOLは、VMのきめ細かなストレージ管理を可能にする革新的なストレージアーキテクチャです。ストレージは、VM単位（VMメタデータを含む）だけでなく、VMDK単位でも管理できます。VVOLは、VMware Cloud Foundation（VCF）の基盤となるSoftware-Defined Data Center（SDDC）戦略の重要なコンポーネントであり、仮想環境向けのより効率的で拡張性に優れたストレージアーキテクチャを提供します。

VVOLを使用すると、各VMストレージオブジェクトはNetApp ONTAP内で一意のエンティティであるため、VMはVM単位でストレージを消費できます。ボリューム管理が不要になったASA R2システムでは、各VMストレージオブジェクトがアレイ上の一意のストレージユニット（SU）であり、個別に制御できます。これにより、個 々 のVMまたはVMDK（つまり個別のSUS）に適用できるストレージポリシーを作成して、パフォーマンス、可用性、データ保護などのストレージサービスをきめ細かく制御できます。



== Storage Policy Based Management（SPBM；ストレージポリシーベースの管理）

SPBM は、仮想化環境で使用できるストレージサービスと、プロビジョニングされたストレージ要素の間の抽象化レイヤとして機能するフレームワークを、ポリシーを通じて提供します。このアプローチにより、ストレージアーキテクトはさまざまな機能を備えたストレージプールを設計できます。これらのプールは、VM管理者が簡単に使用できます。管理者は、プロビジョニングされたストレージプールと仮想マシンのワークロード要件を照合できます。このアプローチにより、ストレージ管理が簡易化され、ストレージリソースの使用効率が向上します。

SPBMはVVOLの主要コンポーネントであり、ストレージサービスを管理するためのポリシーベースのフレームワークを提供します。ポリシーは、vSphere管理者が、ベンダーのVASA Provider（VP）が公開するルールと機能を使用して作成します。パフォーマンス、可用性、データ保護など、さまざまなストレージサービスに対してポリシーを作成できます。ポリシーは個 々 のVMまたはVMDKに割り当てることができるため、ストレージサービスをきめ細かく制御できます。



== NetApp ONTAPとVVOL

NetApp ONTAPはVVOLの規模でストレージ業界をリードしており、1つのクラスタ*で数十万のVVOLをサポートしています。一方、エンタープライズアレイや小規模なフラッシュアレイベンダーでは、アレイあたり数千のVVolしかサポートしていません。ONTAPは、VMware vSphere環境向けの拡張性と効率性に優れたストレージソリューションを提供します。データ重複排除、圧縮、シンプロビジョニング、データ保護などの豊富なストレージサービスでVVOLをサポートします。SPBMを使用すると、VMware vSphere環境とのシームレスな統合が可能になります。

前述したように、VM管理者は容量をストレージプールとして利用できるということです。これには、vSphereで論理データストアとして表されるストレージコンテナを使用します。

ストレージコンテナは、ストレージ管理者が作成し、VM管理者が使用できるストレージリソースをグループ化するために使用されます。ストレージコンテナは、使用しているONTAPシステムのタイプに応じて作成できます。従来のONTAP 9クラスタでは、コンテナに1つ以上の元のFlexVolボリュームが割り当てられ、ストレージプールを形成します。ASA R2システムでは、クラスタ全体がストレージプールになります。


NOTE: VMware vSphere Virtual Volumes 、 SPBM 、および ONTAP の詳細については、を参照してください link:vmware-vvols-overview.html["TR-4400 ：『 VMware vSphere Virtual Volumes with ONTAP 』"^]。

*プラットフォームとプロトコルによって異なる
