---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-datastores-fg.html 
keywords: vSphere, datastore, VMFS, FC, FCoE, NVMe/FC, iSCSI, NFS, vVols 
summary: このページでは、 VMware vSphere 環境に NetApp ONTAP ストレージ解決策を実装するためのベストプラクティスについて説明します。 
---
= FlexGroup ボリューム
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.8では、vSphereでのFlexGroupボリュームデータストアのサポートに加え、ONTAP Tools for VMware vSphereおよびSnapCenter Plugin for VMware vSphereがサポートされるようになりました。FlexGroup を使用すると、大容量のデータストアを簡単に作成でき、複数のコンスティチュエントボリュームを自動的に作成して、 ONTAP システムのパフォーマンスを最大限に高めることができます。ONTAPクラスタ全体の機能を備えた拡張性に優れた単一のvSphereデータストアが必要な場合や、非常に大規模なクローニングワークロードがあり、新しいFlexGroupクローニングメカニズムのメリットが得られる場合は、vSphereでFlexGroupを使用します。

ONTAP 9.8 では、 vSphere のワークロードを使用した広範なシステムテストに加えて、 FlexGroup データストアのコピーオフロードメカニズムも新たに追加されました。更新されたコピーエンジンが使用され、最初の数個のクローンを使用して各コンスティチュエントボリュームにローカルキャッシュが格納されます。このローカルキャッシュを使用して、VMクローンをオンデマンドで迅速にインスタンス化します。

次のシナリオを考えてみましょう。

* 8つのコンスティチュエントで新しいFlexGroupを作成しました
* 新しいFlexGroupのキャッシュタイムアウトが160分に設定されている


このシナリオでは、ローカルファイルクローンではなく、最初に完了する8つのクローンがフルコピーになります。160秒のタイムアウトが経過する前にそのVMをクローニングすると、各コンスティチュエント内のファイルクローンエンジンがラウンドロビン方式で使用され、コンスティチュエントボリューム間でほぼ瞬時に均等に分散されたコピーが作成されます。

ボリュームが新しいクローンジョブを受信するたびに、タイムアウトがリセットされます。この例のFlexGroup内のコンスティチュエントボリュームがタイムアウトまでにクローン要求を受信しなかった場合、そのVMのキャッシュはクリアされ、ボリュームに再度データを入力する必要があります。また、元のクローンのソースが変更された場合（テンプレートを更新した場合など）、競合を防ぐために各構成要素のローカルキャッシュが無効になります。キャッシュは調整可能で、環境のニーズに合わせて設定できます。

FlexGroupキャッシュを十分に活用できないものの、ボリューム間での高速クローニングが必要な環境では、VVOLの使用を検討してください。VVolを使用したボリューム間クローニングは、従来のデータストアよりもはるかに高速で、キャッシュに依存しません。

VAAIでFlexGroupを使用する方法の詳細については、次の技術情報アーティクルを参照してください。 https://kb.netapp.com/?title=onprem%2Fontap%2Fdm%2FVAAI%2FVAAI%3A_How_does_caching_work_with_FlexGroups%253F["VAAI：FlexGroupボリュームでのキャッシュの仕組みを教えてください。"^]

ONTAP 9.8では、FlexGroupボリュームファイル用のファイルベースのパフォーマンス指標（IOPS、スループット、レイテンシ）も新たに追加されており、これらの指標はONTAP tools for VMware vSphereのダッシュボードとVMレポートで確認できます。VMware vSphere プラグイン用の ONTAP ツールでは、最大 IOPS と最小 IOPS の組み合わせを使用してサービス品質（ QoS ）ルールを設定することもできます。これらは、データストア内のすべての VM に対して個別に設定することも、特定の VM に対して個別に設定することもできます。

ネットアップが新たに開発したベストプラクティスをいくつかご紹介します。

* FlexGroupボリュームプロビジョニングのデフォルト設定を使用します。VMware vSphere 用の ONTAP ツールは vSphere 内で FlexGroup を作成およびマウントするため推奨されますが、 ONTAP System Manager やコマンドラインを使用すると特別なニーズを満たすことができます。その場合も、ノードあたりのコンスティチュエントメンバー数などのデフォルト値を使用してください。これはvSphereで最も徹底的にテストされているためです。ただし、コンスティチュエントの数や配置の変更など、デフォルト以外の設定も引き続き完全にサポートされます。
* FlexGroupベースのデータストアをサイジングする場合は、FlexGroupが複数の小規模なFlexVolで構成され、より大きなネームスペースが作成されることに注意してください。そのため、8つのコンスティチュエントでFlexGroupを使用する場合は、データストアのサイズを最大の仮想マシンの8倍以上にする必要があります。たとえば、使用している環境に 6TB の VM がある場合、 FlexGroup データストアのサイズは 48TB 以上にする必要があります。
* FlexGroup によるデータストアスペースの管理を許可します。オートサイズと Elastic サイジングは、 vSphere データストアでテスト済みです。データストアの容量がフルに近くなった場合は、 VMware vSphere 用の ONTAP ツールまたは別のツールを使用して、 FlexGroup ボリュームのサイズを変更します。FlexGroup は、容量と inode をコンスティチュエント間で分散して維持し、容量が許容される場合はフォルダ（ VM ）内のファイルに同じコンスティチュエントへの優先順位を付けます。
* VMwareとNetAppでは、ONTAP 9.14.1以降で現在NFSv4.1セッショントランキングがサポートされています。特定のバージョンの詳細については、NetApp NFS 4.1のInteroperability Matrixの注意事項を参照してください。NFSv3では、ボリュームへの複数の物理パスはサポートされませんが、vSphere 8.0U2以降ではnconnectがサポートされます。nconnectの詳細については、 https://docs.netapp.com/us-en/netapp-solutions_nconnect/virtualization/vmware-vsphere8-nfsv3-nconnect.html["NetAppおよびVMwareでのNFSv3 nconnect機能"]。ONTAP 9.8を搭載したでは、ONTAP tools for VMware vSphereでFlexGroupを作成することを推奨しますが、クラスタ全体に負荷を分散するためには、そのFlexGroupをアンマウントし、ラウンドロビンDNSを使用して再マウントすることを推奨します。ONTAP toolsでデータストアのマウント時に使用されるLIFは1つだけです。データストアを再マウントしたら、ONTAPツールを使用してデータストアを監視および管理できます。
* FlexGroup vSphere データストアのサポートは、 9.8 リリースで最大 1500 台の VM でテスト済みです。
* コピーオフロードには、 NFS Plug-in for VMware VAAI を使用します。前述したように、クローニングはFlexGroupデータストア内で強化されますが、FlexVolボリュームとFlexGroupボリュームの間でVMをコピーする場合、ONTAPはESXiホストのコピーに比べてパフォーマンス上の大きなメリットはありません。そのため、VAAIとFlexGroupのどちらを使用するかを決定する際は、ワークロードのクローニングを検討してください。コンスティチュエントボリュームの数の変更は、FlexGroupベースのクローニングを最適化する1つの方法です。キャッシュタイムアウトの調整も同様です。
* VMware vSphere 9.8 用の ONTAP ツールを使用すると、 ONTAP メトリック（ダッシュボードと VM レポート）を使用して FlexGroup VM のパフォーマンスを監視し、個々の VM の QoS を管理できます。現時点では、これらの指標は ONTAP コマンドや API では使用できません。
* QoS （最大 / 最小 IOPS ）は、個々の VM に対して、またはデータストア内のすべての VM に対して設定できます。すべての VM に QoS を設定すると、 VM ごとに個別に設定する必要がなくなります。今後は、新規または移行された VM には適用されません。新しい VM に QoS を設定するか、データストア内のすべての VM に QoS を再適用してください。また、別のデータストアに移行されたVMには、FlexGroup QoSポリシーも適用されません。これに対し、VVOLでは、別のデータストアに移行してもQoSポリシーの設定を維持できます。
* SnapCenter Plug-in for VMware vSphereリリース4.4以降では、プライマリストレージシステム上のFlexGroupデータストアのVMのバックアップとリカバリがサポートされます。SCV 4.6では、FlexGroupベースのデータストアに対するSnapMirrorのサポートが追加されています。

