---
sidebar: sidebar 
permalink: vmware/vsphere/flexgroups.html 
keywords: vSphere, datastore, VMFS, FC, FCoE, NVMe/FC, iSCSI, NFS, vVols 
summary: このページでは、 VMware vSphere 環境に NetApp ONTAP ストレージ解決策を実装するためのベストプラクティスについて説明します。 
---
= FlexGroup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
ONTAP 9.8 では、 vSphere で FlexGroup データストアがサポートされるようになり、 VMware vSphere 9.8 リリース用の ONTAP ツールも追加されています。

FlexGroup を使用すると、大容量のデータストアを簡単に作成でき、複数のコンスティチュエントボリュームを自動的に作成して、 ONTAP システムのパフォーマンスを最大限に高めることができます。フル機能の ONTAP クラスタを利用して、拡張性に優れた単一の vSphere データストアで FlexGroup を使用できます。

ONTAP 9.8 では、 vSphere のワークロードを使用した広範なシステムテストに加えて、 FlexGroup データストアのコピーオフロードメカニズムも新たに追加されました。強化されたコピーエンジンを使用して、バックグラウンドのコンスティチュエント間でファイルをコピーすると同時に、ソースとデスティネーションの両方でアクセスを許可します。複数のコピーを使用すると、構成要素内で、スペース効率に優れた使用可能なファイルクローンを、大規模に応じて即座に利用できます。

ONTAP 9.8 では、 FlexGroup ファイルの新しいファイルベースのパフォーマンス指標（ IOPS 、スループット、レイテンシ）も追加されました。これらの指標は、 VMware vSphere ダッシュボードや VM レポート用の ONTAP ツールで確認できます。VMware vSphere プラグイン用の ONTAP ツールでは、最大 IOPS と最小 IOPS の組み合わせを使用してサービス品質（ QoS ）ルールを設定することもできます。これらは、データストア内のすべての VM に対して個別に設定することも、特定の VM に対して個別に設定することもできます。

ネットアップが新たに開発したベストプラクティスをいくつかご紹介します。

* FlexGroup プロビジョニングのデフォルトを使用する。VMware vSphere 用の ONTAP ツールは vSphere 内で FlexGroup を作成およびマウントするため推奨されますが、 ONTAP System Manager やコマンドラインを使用すると特別なニーズを満たすことができます。さらに、ノードあたりのコンスティチュエントメンバー数などのデフォルトも使用します。これは、 vSphere でテスト済みの構成メンバー数であるためです。
* FlexGroup データストアのサイジングを行う場合、 FlexVol は、より大容量のネームスペースを作成する複数の小さい FlexGroup で構成されることに注意してください。そのため、最大の仮想マシンの 8 倍以上のサイズのデータストアに設定してください。たとえば、使用している環境に 6TB の VM がある場合、 FlexGroup データストアのサイズは 48TB 以上にする必要があります。
* FlexGroup によるデータストアスペースの管理を許可します。オートサイズと Elastic サイジングは、 vSphere データストアでテスト済みです。データストアの容量がフルに近くなった場合は、 VMware vSphere 用の ONTAP ツールまたは別のツールを使用して、 FlexGroup ボリュームのサイズを変更します。FlexGroup は、容量と inode をコンスティチュエント間で分散して維持し、容量が許容される場合はフォルダ（ VM ）内のファイルに同じコンスティチュエントへの優先順位を付けます。
* VMware とネットアップは、現在、一般的なマルチパスネットワークアプローチをサポートしていません。NFSv4.1 では、ネットアップは pNFS をサポートしていますが、 VMware はセッショントランキングをサポートしています。NFSv3 は、ボリュームへの複数の物理パスをサポートしていません。ONTAP 9.8 を使用した FlexGroup の場合、 VMware vSphere 用の ONTAP ツールを 1 つのマウントにすることを推奨します。これは、間接アクセスによる影響が通常は最小限（マイクロ秒）であるためです。ラウンドロビンDNSを使用して、FlexGroup内の異なるノード上のLIFにESXiホストを分散することは可能ですが、その場合はONTAP tools for VMware vSphereを使用せずにFlexGroupを作成してマウントする必要があります。その場合、パフォーマンス管理機能は使用できません。
* FlexGroup vSphere データストアのサポートは、 9.8 リリースで最大 1500 台の VM でテスト済みです。
* コピーオフロードには、 NFS Plug-in for VMware VAAI を使用します。クローニングは FlexGroup データストア内で強化 ONTAP されますが、 FlexVol ボリュームと FlexGroup ボリュームの間で VM をコピーする場合に、 ESXi ホストコピーと比べてパフォーマンス面で大きなメリットはありません。
* VMware vSphere 9.8 用の ONTAP ツールを使用すると、 ONTAP メトリック（ダッシュボードと VM レポート）を使用して FlexGroup VM のパフォーマンスを監視し、個々の VM の QoS を管理できます。現時点では、これらの指標は ONTAP コマンドや API では使用できません。
* QoS （最大 / 最小 IOPS ）は、個々の VM に対して、またはデータストア内のすべての VM に対して設定できます。すべての VM に QoS を設定すると、 VM ごとに個別に設定する必要がなくなります。今後は、新規または移行された VM には適用されません。新しい VM に QoS を設定するか、データストア内のすべての VM に QoS を再適用してください。
* SnapCenter Plug-in for VMware vSphere リリース 4.4 では、プライマリストレージシステム上の FlexGroup データストア内の VM のバックアップとリカバリがサポートされています。SnapMirror を手動で使用して FlexGroup をセカンダリシステムにレプリケートできるが、 SCV 4.4 ではセカンダリコピーが管理されない。

