---
sidebar: sidebar 
permalink: epic/epic-example-overview.html 
keywords: epic,cache,iris 
summary: Epic on ONTAPの導入例 
---
= Epic on ONTAPの導入例
:allow-uri-read: 


[role="lead"]
このセクションでは、ONTAPクラスタの完全な高度な設定、およびEpicサーバへのストレージのプロビジョニングと提供について説明します。

詳細を取得し、文書化を容易にするために、コマンドラインを使用します。GUIを使用する場合は、System Managerですべての設定をプロビジョニングできます。

これまで、大規模なプロジェクトの初期一括セットアップは、表1に示すコマンドを使用することで高速化されていました。特に、ワークシートでコマンドを連結する場合に便利です。このコマンドのリストは、優れたビルドドキュメントとしても機能します。

もう1つのプロビジョニングオプションとして、Ansibleを使用した導入日と導入日の自動化スクリプトを使用する方法があります。NetAppには、Ansible-galaxy collection install NetApp . ONTAPコマンドを使用したAnsible Galaxyコレクションを含む、何百もの既存のAnsibleプレイブックがダウンロード可能です。

GUIは、シンプルな単一ページLUNおよび共有プロビジョニングでも優れた機能を発揮します。GUIは、ストレージを追加、変更、または削除する際の処理に最適です。表1のストレージのベストプラクティス設定を適用する場合は、どちらのオプションでも問題ありません。

クラスタセットアップの完了とストレージ/ホストのプロビジョニングが完了するまでに1時間以上かかることはありません。

*ベストプラクティスのストレージ設定*

[cols="1,1"]
|===


| 設定 | 値 


| アグリゲート | デフォルトの自動プロビジョニング、RAID DEPを使用したノードあたりADPアグリゲート1つ 


| SVM | マルチプロトコルを使用する場合は2つのSVM（ブロックSVMとSMB / NFS SVM）Epicとプロトコルの命名規則を使用します。適切なセキュリティ形式を使用する 


| ボリュームのスペースギャランティ | なし 


| ボリュームSnapshotポリシー | なし 


| ボリュームのオートサイズ | 成長 


| ボリューム最大オートサイズ | LUNサイズが2Tまたは2 X 


| ボリュームSnapshotの自動削除 | 有効 


| ボリュームサイズ | LUNサイズの1.5倍 


| ボリュームのレイアウト | コントローラ間で均等に分散 


| igroup タイプ | 物理サーバで使用する場合はOS、ESXで使用する場合はVMwareタイプ。 
|===