---
sidebar: sidebar 
permalink: epic/epic-overview.html 
keywords: epic,cache,iris 
summary: Epic on ONTAPの概要 
---
= ONTAPのEpic
:allow-uri-read: 


[role="lead"]
デジタル変革の鍵となるのは、データをより有効に活用することです。


NOTE: 本ドキュメントは、以前に公開されていたテクニカルレポート（TR-3923：『NetApp Best Practices for Epic_』）に代わるものです。

病院では、デジタル変革を始めるために大量のデータを必要としています。患者の治療、スタッフスケジュールおよび医療リソースの管理プロセスの一部として、情報が収集および処理されることがあります。ただし、多くのアクションは手動または古いシステムを通じて実行されます。1つ目は、データの量が急激に増加し続けているため、管理がますます困難になっていることです。

この問題の主な原因は、病院のデータが多くの場合、データサイロに保存されていることです。手動による入力や更新に時間がかかりすぎるため、バーンアウトやエラーが発生します。このドキュメントは、医療データの一部であるEpic Electronic Health Records（EHR）について説明しています。ただし、ここで説明するデータ管理戦略は、すべての医療データに適用でき、適用する必要があります。NetAppには、デジタルインフラの刷新と簡易化に取り組んできた実績があります。ネットアップのインテリジェントなデータインフラは、デジタル変革の基盤を形成します。

NetAppは、ヘルスケアのあらゆるニーズに対応する単一のデータ管理ソリューションを提供します。ネットアップは、病院のデジタル変革への道のりを支援することができます。構造とスマートなソリューションで基盤を構築することで、医療はこの貴重な情報の価値を最大限に引き出すことができます。このフレームワークは、医療提供者が病気を迅速に診断し、緊急事態における意思決定プロセスをより適切にサポートするための個別の治療計画を策定するのに役立ちます。また、独自のインテリジェントなデータインフラを構築し、病院がデータサイロを解消し、データの相互運用性を促進し、機密性の高い患者情報を保護できるようにすることもできます。

このドキュメントは、Epic EHRの構築と実装を成功させるためのガイドとして使用してください。Epicの複数のサイロを構築するのではなく、単一のEpicデータインフラを構築して病院を変革しましょう。



== 目的

このドキュメントでは、NetAppストレージをEpicソフトウェア環境に統合するためのベストプラクティスについて説明します。次のセクションで構成されています。

* さまざまな構成におけるEpicソフトウェア環境とそのストレージ要件に関する技術的な知識。
* Epicのストレージに関する考慮事項。Epicソリューションの重要な意思決定要因を説明しています。
* NetAppストレージの推奨事項。Epicストレージの要件を満たすためのNetAppストレージ構成のベストプラクティスが記載されています。




== 適用範囲

このドキュメントでは、次の項目は取り上げません。

* 定量的なパフォーマンス要件とサイジングガイダンスについては、を参照してください（NetAppへのログインが必要）。 https://fieldportal.netapp.com/content/192412?assetComponentId=192510["TR-3930i ：『 NetApp Sizing Guidelines for Epic 』"^]




== 対象読者

ネットアップは、読者が次の知識を有していることを前提としています。

* SANとNASの概念を十分に理解している
* ONTAPストレージシステムに関する技術的な知識
* ONTAPの構成と管理に関する技術的知識

