---
sidebar: sidebar 
permalink: epic/epic-arch-storage.html 
keywords: epic,cache,iris 
summary: Epicのストレージ要件 
---
= Epicのストレージ要件
:allow-uri-read: 


[role="lead"]
通常、本番環境のデータベースには専用のストレージリソースが提供されますが、ミラーデータベースインスタンスは、セカンダリストレージリソースをClarityレポートツールなどのEpicソフトウェア関連の他のコンポーネントと共有します。

アプリケーションファイルやシステムファイルに使用されるその他のソフトウェアストレージ環境も、セカンダリストレージリソースによって提供されます。

Epicでは、サイジング以外にも、次のストレージレイアウトルールと主な考慮事項があります。

* 2020年以降、運用データベース（ODB）のワークロードはすべてオールフラッシュアレイ上に配置する必要があります。
* Epicでは、ストレージの各プールを、pool1、pool2、pool3、NAS1、NAS2などの別 々 の物理ハードウェアに配置することを推奨しています。



NOTE: クラスタ内のノードは、ストレージプールとみなすことができます。ONTAP 9 .4以降およびAQoSでは、ポリシーを使用して保護されたプールを作成できます。

* Epic 3-2-1バックアップに関する新たな推奨事項
+
.. コピーをリモートサイトに配置（ディザスタリカバリ）
.. いずれかのコピーは、プライマリコピーとは別のストレージプラットフォームに配置する必要があります。
.. データのコピー





NOTE: NetApp SnapMirrorを使用してNetAppをバックアップしているお客様は、3-2-1の推奨事項を満たしていません。これは、ONTAP to ONTAPが上記の2番目の要件を満たしていないためです。SnapMirrorは、ONTAPからオンプレミスのオブジェクトストレージ（StorageGRIDなどを介して）に直接使用することも、クラウドに使用することもでき、Epicの要件を満たすことができます。

ストレージ要件の詳細については、Galaxyで利用可能な次のEpicガイドを参照してください。

* SAN に関する考慮事項
* ストレージ製品とテクノロジのステータス（SPAT）
* ハードウェア構成ガイド

