---
sidebar: sidebar 
permalink: epic/epic-config-efficiency.html 
keywords: epic,cache,iris 
summary: EpicのStorage Efficiency設定 
---
= EpicのStorage Efficiency設定
:allow-uri-read: 


[role="lead"]
ONTAPのインライン効率化機能はデフォルトで有効になっており、ストレージプロトコル、アプリケーション、ストレージ階層に関係なく機能します。

効率化機能により、高価なフラッシュストレージに書き込まれるデータ量が削減され、必要なドライブ数も削減されます。ONTAPはレプリケーションでも効率性を維持します。Epicのようなレイテンシの影響を受けやすいアプリケーションであっても、それぞれの効率化機能がパフォーマンスにほとんど、またはまったく影響しません。

[TIP]
====
* NetAppでは、ディスク使用率を最大化するために、すべての効率化設定をオンにすることを推奨これらの設定は、AFFおよびASAベースのシステムではデフォルトでオンになっています。

====
このストレージ効率化は次の機能によって実現されます。

* 重複排除は、LUNをホストするボリューム内のブロックの冗長コピーを削除することで、プライマリストレージのスペースを削減します。この推奨オプションは、デフォルトでオンになっています。
* インライン圧縮はディスクに書き込むデータの量を削減し、Epicワークロードではスペースの大幅な削減を実現します。この推奨オプションは、デフォルトでオンになっています。
* インラインコンパクションでは、使用量が半分未満の4Kブロックが1つのブロックに統合されます。この推奨オプションは、デフォルトでオンになっています。
* シンレプリケーションは、NetApp SnapMirrorソフトウェアを含むNetAppデータ保護ソフトウェアポートフォリオの中心です。また、SnapMirrorのシンレプリケーション機能では、必要なストレージ容量を最小限に抑えて、ビジネスクリティカルなデータを保護できます。* NetAppでは*このオプションをオンにすることを推奨しています。
* アグリゲートの重複排除：重複排除は常にボリュームレベルで実行されます。ONTAP 9 .2では、アグリゲート重複排除機能が利用できるようになり、ディスク削減効果がさらに向上しました。ONTAP 9では、ポストプロセスアグリゲート重複排除が追加されました。3.* NetAppでは*このオプションをオンにすることを推奨しています。

