---
sidebar: sidebar 
permalink: epic/epic-ontap-scalability.html 
keywords: epic,cache,iris 
summary: ONTAP上でのEpicの拡張性 
---
= ONTAP上でのEpicの拡張性
:allow-uri-read: 


[role="lead"]
Epic Hardware Configuration Guideは、3年間で年間約20%の成長を達成しています。ただし、環境が予期せず拡大することもあります。

NetAppは、NAS、SAN、オブジェクトクラスタのパフォーマンスと容量を最大12ノードまでシームレスに拡張できます。そのため、ビジネスの成長に合わせて、システムを停止することなくスケールアップ/スケールアウトできます。

Epic Irisは拡張機能を提供します。複数のEpicインスタンスを所有している大規模なお客様は、単一のインスタンスに統合できます。link:https://www.netapp.com/media/27905-nva-1159-design.pdf["NetApp Verified Architecture Epic on Modern SAN"^]このドキュメントでは、Epicが統合ワークロードを単一のHAで72万IOPSまでシームレスに拡張し、クラスタ内で400万IOPSを超えるまでスケールアウトできることを実証しています。コントローラをアップグレードするか、既存のクラスタにディスクを追加することで、無停止でスケールアップできます。

NAS、SAN、オブジェクトデータも、クラスタ内のノード間で無停止で移動できます。クラスタ内の各HAペアには、ONTAP FASシステムとAFFシステムのタイプとサイズを任意に組み合わせて使用できます。単一のクラスタ間でワークロードを分散して、ストレージへの投資を最大限に活用できます。

ONTAPには、StorageGRIDやクラウドのオブジェクトストレージをバックアップターゲットや自動コールドストレージ階層化のターゲットとして使用するオプションもあります。高価なオールフラッシュディスクを解放し、Snapshot、コールドデータをオブジェクトに自動的に階層化できます。

その結果、Epicは、ONTAP、複数のプロトコル、StorageGRID、任意のクラウドを活用して、NetApp製品ポートフォリオを活用することで、より優れた運用を実現できます。これらの製品は、ディザスタリカバリ、アーカイブ、分析、階層化などのオプションを提供します。
