---
sidebar: sidebar 
permalink: mysql/mysql-overview.html 
keywords: MySQL,MariaDB,TR-4722 
summary: ONTAPでのMySQLの運用 
---
= ONTAPノMySQLテタヘス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MariaDBやPercona MySQLを含むMySQLとその変種は、世界で最も人気のあるデータベースです。


NOTE: ONTAPとMySQLデータベースに関するこのドキュメントは、以前に公開されていた_TR-4722：『MySQL database on NetApp ONTAP best practices』に代わるものです。_

MySQLには次のような機能があります。

* * TCOの削減* MySQLは、強力で無料のオープンソースのデータベース管理システムで、数年前から提供されています。非常に安定しています。コミュニティサポートがあり、新機能の保守、デバッグ、追加に役立ちます。Webアプリケーションに複数のデータベースが必要な場合や、ロードバランシングやシャーディングが必要な場合は、インスタンスごとに単一のライセンスを必要とする商用データベースではなく、ハードウェアコストのみでデータベースインスタンスを簡単にセットアップできます。
* *信頼性、パフォーマンス、使いやすさ。* MySQLの特徴の1つは、優れたパフォーマンスとスケーラビリティです。そのため、多くのWebベースの企業がそれを使用しています。MySQLは、高速なパフォーマンスを実現するためにいくつかの主要な強みを活用競争は常にマウスクリック(またはスクリーンタッチ)で行われるため、顧客からの問い合わせや活動への迅速な対応が最も重要です。Webベースのアプリケーションを処理するデータベースは、読み取り（単純なクエリと複雑なクエリ）処理と書き込み処理の両方で、卓越したパフォーマンスを提供する必要があります。
* *データベースの開発、設計、および管理。* MySQL Workbenchは、開発、設計、および管理を統合した環境を提供し、開発者およびDBAの生産性を高めます。異なる開発者がデータベースで異なる機能を探していますが、MySQLはさまざまな機能を提供しています。ラップトップとデスクトップの両方で適切に実行できます。既存のWebサーバやアプリケーションと衝突しないように、環境に簡単に適応できます。
* *包括的なトランザクション・サポート。* MySQLは、利用可能な最も堅牢なトランザクション・データベース・エンジンの1つです。完全なデータ整合性を実現する解決策であり、完全なアトミック、一貫性、分離、永続性トランザクションのサポート、マルチバージョントランザクションのサポートなどの機能を提供します。 および無制限のローレベルロック。サーバーによって強制された参照整合性により、即時デッドロック識別が可能になります。
* *データセキュリティ。* MySQLは、WordPress、Drupal、Joomla、Facebook、Google、 そしてtwitter。MySQLの最新バージョンに付随するデータセキュリティとトランザクション処理のサポートは、あらゆるビジネス、特に頻繁な送金を伴うEコマースビジネスに利益をもたらす可能性があります。
* *プラガブル・アーキテクチャー。* MySQLプラガブル・ストレージ・エンジン・アーキテクチャーにより、データベースの専門家は、アプリケーションのコーディング要件を管理することなく、特定のアプリケーションのニーズに特化したストレージ・エンジンを選択できます。MySQLサーバアーキテクチャは、アプリケーションプログラマとDBAを、ストレージレベルでの低レベルの実装の詳細から分離し、一貫性のある簡単なアプリケーションモデルとAPIを提供します。さまざまなストレージエンジンにはさまざまな機能がありますが、アプリケーションはこれらの違いから保護されています。


MySQLの効率的でモジュール化されたアーキテクチャは、1つのストレージエンジンから独立したインターフェイスとサービスを使用しながら、データウェアハウス、トランザクション処理、HA状況など、特定のアプリケーションのニーズに対応したい場合に大きなメリットをもたらします。
