---
sidebar: sidebar 
permalink: mysql/mysql-mysql-over-nfs.html 
keywords: MySQL,MariaDB,NFS 
summary: MySQLとNFS 
---
= MySQLとNFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MySQLのドキュメントでは、NAS環境にはNFSv4を使用することを推奨しています。



== ONTAP NFS転送サイズ

ONTAPでは、デフォルトでNFS IOサイズが64Kに制限されます。MySQLデータベースでランダムIOを使用する場合、ブロックサイズは64Kの最大値よりもはるかに小さくなります。ラージブロックIOは通常並列化されるため、64Kの最大値も制限ではありません。

一部のワークロードでは、最大64Kに制限があります。特に、フルテーブルスキャンバックアップ処理などのシングルスレッド処理は、データベースで実行するI/Oが少なくても大容量であれば、より高速かつ効率的に実行されます。データベースワークロードを使用するONTAPに最適なIO処理サイズは256Kです。以下のオペレーティングシステムのNFSマウントオプションは、それに応じて64Kから256Kに更新されています。

特定のONTAP SVMの最大転送サイズは、次のように変更できます。

[listing]
----
Cluster01::> set advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.

Do you want to continue? {y|n}: y

Cluster01::*> nfs server modify -vserver vserver1 -tcp-max-xfer-size 262144
----

CAUTION: ONTAPで許容される最大転送サイズを、現在マウントされているNFSファイルシステムのrsize/wsizeの値より小さくしないでください。これにより、一部のオペレーティングシステムでハングしたり、データが破損したりする可能性があります。たとえば、NFSクライアントのrsize / wsizeが65536に設定されている場合は、クライアント自体が制限されているため、ONTAPの最大転送サイズを65536~1048576の間で調整しても効果はありません。最大転送サイズを65536未満に縮小すると、可用性やデータが損傷する可能性があります。

[TIP]
====
* NetAppの推奨事項*

次のNFSv4 fstab（/etc/fstab）設定を設定します。

`nfs4 rw, hard,nointr,bg,vers=4,proto=tcp,noatime,rsize=262144,wsize=262144`

====

NOTE: NFSv3を使用する一般的な問題は、停電後にロックされたInnoDBログファイルでした。時間または切り替えログファイルを使用して、この問題を解決しました。ただし、NFSv4にはロック処理があり、開いているファイルや委譲が追跡されます。
