---
sidebar: sidebar 
permalink: oracle/dr/metrocluster/mc-mcc-nvfail.html 
keywords: oracle, metrocluster, extended rac, rac, nvfail, switchover 
summary: Oracle on MetroCluster - NVFAIL 
---
= MetroClusterとNVFAIL
:allow-uri-read: 


[role="lead"]
NVFailは、ONTAPの一般的なデータ整合性機能で、データベースワークロードに特に重要です。詳細については、 link:../ontap-configuration/oracle_and_nvfail.html["NVFail"]。NVFAILに関するMetroCluster固有の考慮事項もあります。



== 手動で強制NVFAILを使用した拡張RAC

拡張RACクラスタでスイッチオーバーを強制的に実行する最も安全なオプションは、 `-force-nvfail-all` コマンドラインで。このオプションは、キャッシュされたすべてのデータが確実にフラッシュされるようにするための緊急措置として使用できます。災害が発生したサイトにもともと配置されていたストレージリソースをホストが使用している場合、I/Oエラーまたは古いファイルハンドルのいずれかを受信します。 (`ESTALE`）エラー。Oracleデータベースがクラッシュし、ファイルシステムが完全にオフラインになるか、読み取り専用モードに切り替わります。

スイッチオーバーが完了すると、 `in-nvfailed-state` フラグをクリアし、LUNをオンラインにする必要があります。このアクティビティが完了したら、データベースを再起動できます。これらのタスクを自動化してRTOを短縮できます。



== dr-force-nvfailを使用した拡張RAC

最も安全な設定は、 `dr-force-nvfail` リモートサイトからアクセスするすべてのボリュームにフラグを設定します。そのため、ボリュームが開始されたときに使用できなくなります。 `in-nvfailed-state` スイッチオーバー中。スイッチオーバーが完了すると、 `in-nvfailed-state` フラグをクリアし、LUNをオンラインにする必要があります。これらのアクティビティが完了したら、データベースを再起動できます。これらのタスクを自動化してRTOを短縮できます。

結果は、 `-force-nvfail-all` フラグ。ただし、影響を受けるボリュームの数は、古いキャッシュを使用するアプリケーションまたはオペレーティングシステムから保護する必要があるボリュームだけに制限される場合があります。



== dr-force-nvfailを使用しない拡張RAC

を使用しない環境には、次の2つの重要な要件があります。 `dr-force-nvfail` データベースボリューム：

* 強制スイッチオーバーは、プライマリサイトの障害から30秒以内に実行する必要があります。
* メンテナンスタスクの実行中や、SyncMirrorプレックスまたはNVRAMレプリケーションが同期されていないその他の状態のときは、スイッチオーバーを実行しないでください。最初の要件を満たすには、サイト障害から30秒以内にスイッチオーバーを実行するように設定されたTiebreakerソフトウェアを使用します。これは、サイト障害が検出されてから30秒以内にスイッチオーバーを実行する必要があるという意味ではありません。これは、サイトが動作していることが確認されてから30秒が経過した場合に強制的にスイッチオーバーを実行しても安全ではないことを意味します。


2つ目の要件は、MetroCluster構成が同期されていないことが判明した場合に、自動スイッチオーバー機能をすべて無効にすることで部分的に満たすことができます。NVRAMレプリケーションとSyncMirrorプレックスの健常性を監視できるTiebreaker解決策を使用することを推奨します。クラスタが完全に同期されていない場合、Tiebreakerはスイッチオーバーをトリガーしません。

NetApp MCTBソフトウェアは同期ステータスを監視できないため、何らかの理由でMetroClusterが同期されていない場合は無効にする必要があります。ClusterLionにはNVRAM監視機能とプレックス監視機能が搭載されており、MetroClusterシステムが完全に同期されていることが確認されないかぎり、スイッチオーバーをトリガーしないように設定できます。
