---
sidebar: sidebar 
permalink: microsoft/win_deploy_hyperv.html 
keywords: Windows,Hyper-V,VHDX,VM,Virtual 
summary: この付録では、高可用性Hyper-VクラスタをNetAppストレージに導入する方法について説明します。 
---
= Hyper-Vクラスタの導入
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
この付録では、Hyper-Vクラスタの導入について説明します。



== 前提条件

* 2台以上のHyper-Vサーバが相互に接続されている。
* 各Hyper-Vサーバに少なくとも1つの仮想スイッチが設定されている。
* フェイルオーバークラスタ機能は、各Hyper-Vサーバで有効になっています。
* SMB共有（CSV）は、Hyper-VクラスタリングのためにVMとそのディスクを格納する共有ストレージとして使用されます。
* 異なるクラスタ間でストレージを共有しないでください。クラスタごとにCSV / CIFS共有を1つだけ設定する必要があります。
* SMB共有を共有ストレージとして使用する場合は、SMB共有に対する権限を設定して、クラスタ内のすべてのHyper-Vサーバのコンピュータアカウントにアクセスを許可する必要があります。




== 導入

. いずれかのWindows Hyper-Vサーバに管理者グループのメンバーとしてログインします。
. Server Managerの起動**。**
. [Tools]セクションで、[Failover][Cluster Manager]をクリックします。
. [Actions]メニューから[Create Cluster]をクリックします。
. このクラスタに含まれるHyper-Vサーバの詳細を指定します。
. クラスタ構成を検証クラスタ構成の検証を求められたら[Yes]を選択し、Hyper-Vサーバがクラスタに参加するための前提条件を満たしているかどうかを検証するために必要なテストを選択します。
. 検証に成功すると、クラスタ作成ウィザードが開始されます。ウィザードで、新しいクラスタのクラスタ名とクラスタのIPアドレスを入力します。次に、Hyper-Vサーバ用の新しいフェイルオーバークラスタが作成されます。
. フェイルオーバークラスタマネージャで、新しく作成したクラスタをクリックして管理します。
. クラスタで使用する共有ストレージを定義します。SMB共有またはCSVのいずれかです。
. SMB共有を共有ストレージとして使用する場合、特別な手順は必要ありません。
+
** NetAppストレージコントローラにCIFS共有を設定します。これを行うには、「link:win_smb.html["SMB環境でのプロビジョニング"]"。


. CSVを共有ストレージとして使用するには、次の手順を実行します。
+
.. NetAppストレージコントローラでLUNを設定します。これを行うには、「SAN環境でのプロビジョニング」を参照してください。
.. フェイルオーバークラスタ内のすべてのHyper-VサーバがNetApp LUNを認識できることを確認します。フェイルオーバークラスタに含まれるすべてのHyper-Vサーバに対してこの処理を実行するには、それぞれのイニシエータがNetAppストレージのイニシエータグループに追加されていることを確認します。また、LUNが検出され、MPIOが有効になっていることを確認してください。
.. クラスタ内のいずれかのHyper-Vサーバで、次の手順を実行します。
+
... LUNをオンラインにし、ディスクを初期化し、新しいシンプルボリュームを作成し、NTFSまたはReFSを使用してフォーマットします。
... フェイルオーバークラスタマネージャで、クラスタを展開し、ストレージを展開し、ディスクを右クリックして、ディスクの追加をクリックします。追加すると、クラスタへのディスクの追加ウィザードが開き、LUNがディスクとして表示されます。[OK]をクリックしてLUNをディスクとして追加します。
... これで、LUNの名前がClustered Diskになり、[Disks]に[Available Storage]と表示されます。


.. LUN（クラスタディスク）を右クリックし、[Add to Cluster Shared Volumes]をクリックします。これで、LUNがCSVとして表示されます。
.. CSVは、ローカルの場所C：\ClusterStorage\にあるフェイルオーバークラスタのすべてのHyper-Vサーバから同時に認識およびアクセスできます。


. 高可用性VMを作成します。
+
.. フェイルオーバークラスタマネージャで、前の手順で作成したクラスタを選択して展開します。
.. [Roles]をクリックし、[Actions]で[Virtual Machines]をクリックします。[New Virtual Machine]をクリックします。
.. VMを配置するクラスタからノードを選択します。
.. [Virtual Machine Creation]ウィザードで、VMとそのディスクを格納するパスとして共有ストレージ（SMB共有またはCSV）を指定します。
.. Hyper-V Managerを使用して、VMとそのディスクをHyper-Vサーバ用に格納するためのデフォルトパスとして共有ストレージ（SMB共有またはCSV）を設定します。


. 計画的フェイルオーバーをテストする。ライブマイグレーション、クイックマイグレーション、またはストレージマイグレーション（移動）を使用して、VMを別のノードに移動します。レビュー link:win_deploy_hyperv_lmce.html["クラスタ環境でのライブマイグレーション"] 詳細：
. 計画外フェイルオーバーをテストVMを所有するサーバでクラスタサービスを停止します。

