---
sidebar: sidebar 
permalink: microsoft/win_deploy_hyperv_lmce.html 
keywords: Windows,Hyper-V,VHDX,VM,Virtual 
summary: この付録では、クラスタ環境へのライブマイグレーションの導入について説明します。 
---
= クラスタ環境でのHyper-Vライブマイグレーションの導入
:allow-uri-read: 


[role="lead"]
この付録では、クラスタ環境へのライブマイグレーションの導入について説明します。



== 前提条件

ライブマイグレーションを導入するには、共有ストレージを使用するフェイルオーバークラスタでHyper-Vサーバを構成する必要があります。セクションを確認します。 link:win_deploy_hyperv.html["Hyper-Vクラスタリング"] 詳細：



== 導入

クラスタ環境でライブマイグレーションを使用するには、次の手順を実行します。

. フェイルオーバークラスタマネージャで、クラスタを選択して展開します。クラスタが表示されない場合は、[Failover][Cluster Manager]をクリックし、[Connect to Cluster]をクリックしてクラスタ名を指定します。
. [Roles]をクリックします。クラスタで使用可能なすべてのVMが表示されます。
. VMを右クリックし、[Move]をクリックします。これにより、次の3つのオプションが提供されます。
+
** *ライブマイグレーション。*手動でノードを選択することも、クラスタが最適なノードを選択できるようにすることもできます。ライブマイグレーションでは、クラスタはVMで使用されているメモリを現在のノードから別のノードにコピーします。そのため、VMを別のノードに移行すると、VMに必要なメモリと状態の情報がVMにすでに用意されています。この移行方法はほぼ瞬時ですが、一度に移行できるVMは1つだけです。
** *クイック移行。*ノードを手動で選択することも、クラスタが最適なノードを選択できるようにすることもできます。クイックマイグレーションでは、クラスタはVMで使用されているメモリをストレージ内のディスクにコピーします。そのため、VMを別のノードに移行すると、VMに必要なメモリと状態の情報を、もう一方のノードがディスクからすばやく読み取ることができます。クイックマイグレーションでは、複数のVMを同時に移行できます。
** *仮想マシンストレージの移行。*この方法では、仮想マシンストレージの移動ウィザードを使用します。このウィザードでは、VMディスクと他のファイルを選択して、別の場所（CSV共有またはSMB共有）に移動できます。



