---
sidebar: sidebar 
permalink: postgres/postgres-snapshot-dp.html 
keywords: PostgreSQL,database,postgres 
summary: PostgreSQLデータベースとストレージスナップショット 
searchtitle: PostgreSQLデータベースとストレージスナップショット 
---
= Snapshot
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
PostgreSQLを使用したスナップショットベースのバックアップでは、フルリカバリまたはポイントインタイムリカバリを提供するために、データファイル、WALファイル、およびアーカイブされたWALファイルのスナップショットを構成する必要があります。

PostgreSQLデータベースの場合、Snapshotを使用した平均バックアップ時間は数秒~数分です。このバックアップ速度は、 `pg_basebackup` その他のファイル・システム・ベースのバックアップ・アプローチ

NetAppストレージ上のSnapshotは、crash-consistentとアプリケーション整合性の両方が可能です。crash-consistent Snapshotはデータベースを休止せずにストレージ上に作成されますが、アプリケーション整合性Snapshotはデータベースがバックアップモードの間に作成されます。NetAppでは、後続のスナップショットが永久増分バックアップとなるため、ストレージの節約とネットワークの効率化が促進されます。

スナップショットは高速で、システムのパフォーマンスに影響を与えないため、他のストリーミングバックアップテクノロジのように1日1回のバックアップを作成するのではなく、1日に複数のスナップショットをスケジュールできます。リストアとリカバリの処理が必要な場合は、次の2つの主な機能によってシステムのダウンタイムが短縮されます。

* NetApp SnapRestoreのデータリカバリテクノロジにより、リストア処理が数秒で実行されます。
* Recovery Point Objective（RPO；目標復旧時点）が頻繁に発生するため、適用するデータベースログの数が減り、フォワードリカバリも高速化されます。


PostgreSQLをバックアップするには、データボリュームが（コンシステンシグループ）WALとアーカイブログと同時に保護されていることを確認する必要があります。Snapshotテクノロジを使用してWALファイルをコピーする場合は、次のコマンドを実行してください： `pg_stop` アーカイブする必要があるすべてのWALエントリをフラッシュします。リストア中にWALエントリをフラッシュする場合は、データベースを停止するか、既存のデータディレクトリをアンマウントまたは削除し、ストレージでSnapRestore操作を実行するだけで済みます。リストアが完了したら、システムをマウントして現在の状態に戻すことができます。ポイントインタイムリカバリの場合は、WALとアーカイブログをリストアすることもできます。次に、PostgreSQLは最も整合性のあるポイントを決定し、自動的にリカバリします。

整合グループはONTAPの機能であり、1つのインスタンスまたは複数の表領域を含むデータベースに複数のボリュームがマウントされている場合に推奨されます。整合性グループSnapshotを使用すると、すべてのボリュームがグループ化されて保護されます。整合グループはONTAP System Managerから効率的に管理できます。また、整合グループをクローニングして、テストや開発用にデータベースのインスタンスコピーを作成することもできます。
